const peliculas = [
  // ===============================
// 📚 BASADAS EN LIBROS (VERSIÓN EXTENDIDA)
// ===============================

{
  id: 1,
  titulo: "Harry Potter y la Piedra Filosofal",
  anio: 2001,
  genero: "Fantasía / Aventura",
  categoria: "Basadas en Libros",
  imagen: "https://m.media-amazon.com/images/M/MV5BYTkyYjVkNDItODc1Ny00NzA1LTkwY2YtZDUwNTlhMDk3MTZiXkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "+7",
  autor: "J.K. Rowling (Libro)",
  reseña: "Una adaptación mágica que captura la esencia de la amistad y la lucha contra el mal, perfecta para iniciar una saga épica.",
  descripcion: "En una noche lluviosa, un bebé huérfano llega a la puerta de unos tíos que jamás imaginaron que criaban al niño más famoso del mundo mágico. Años después, Harry Potter descubre que no es un chico común: es un mago destinado a cambiar el destino del mundo. Al ingresar a Hogwarts, una escuela de magia repleta de secretos, encantamientos y criaturas fascinantes, deberá enfrentarse a los misterios de su pasado y al oscuro nombre que nadie se atreve a pronunciar: Voldemort. Con una mezcla perfecta de inocencia, aventura y descubrimiento, esta película marca el inicio de una de las sagas más queridas del cine.",
  recomendacion: "Imprescindible para quienes aman los universos de fantasía llenos de imaginación y amistad.",
  detalles: "Basada en el libro 'Harry Potter y la Piedra Filosofal'. Dirigida por Chris Columbus.",
  duracion: "2h 32min",
},

{
  id: 2,
  titulo: "Orgullo y Prejuicio",
  anio: 2005,
  genero: "Romance / Drama",
  categoria: "Basadas en Libros",
  imagen: "https://m.media-amazon.com/images/M/MV5BZjBlODgwZWEtODcxMi00OTY5LWEyOTItODE2MDBjZjU0ZDU3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+12",
  autor: "Jane Austen (Libro)",
  reseña: "Una hermosa adaptación visualmente impactante que honra el clásico literario de Jane Austen.",
  descripcion: "En la campiña inglesa del siglo XIX, la inteligente y decidida Elizabeth Bennet se enfrenta a las normas sociales que definen el valor de una mujer por su matrimonio. Cuando conoce al enigmático y aparentemente arrogante Sr. Darcy, una batalla de orgullo, prejuicios y emociones reprimidas comienza. A través de bailes elegantes, diálogos agudos y paisajes que reflejan las tensiones internas de los personajes, la película nos sumerge en una historia atemporal sobre la independencia, el amor y la superación de las apariencias.",
  recomendacion: "Ideal para los amantes del drama de época, el romance contenido y las historias de crecimiento emocional.",
  detalles: "Protagonizada por Keira Knightley y Matthew Macfadyen. Dirigida por Joe Wright.",
  duracion: "2h 9min",
},

{
  id: 3,
  titulo: "El Señor de los Anillos: La Comunidad del Anillo",
  anio: 2001,
  genero: "Fantasía / Épico",
  categoria: "Basadas en Libros",
  imagen: "https://es.web.img2.acsta.net/c_310_420/medias/nmedia/18/89/67/45/20061512.jpg",
  rangoEdad: "+13",
  autor: "J.R.R. Tolkien (Libro)",
  reseña: "Una obra maestra del cine de fantasía, con un mundo inmersivo y personajes inolvidables.",
  descripcion: "En la apacible Tierra Media, un joven hobbit llamado Frodo Bolson recibe una herencia que podría destruir el mundo: un anillo con el poder de corromper incluso los corazones más puros. Acompañado por magos, elfos, enanos y hombres, emprende una peligrosa misión para destruirlo en el fuego donde fue forjado. Con una escala épica, paisajes imponentes y una profunda reflexión sobre el poder, la amistad y el sacrificio, esta primera entrega cimentó un antes y un después en el cine de aventuras y fantasía.",
  recomendacion: "La adaptación definitiva del género épico. Obligatoria para los fans del cine fantástico.",
  detalles: "Dirigida por Peter Jackson. Ganadora de 4 Premios Óscar.",
  duracion: "2h 58min",
},

{
  id: 4,
  titulo: "Crepúsculo",
  anio: 2008,
  genero: "Romance / Fantasía",
  categoria: "Basadas en Libros",
  imagen: "https://m.media-amazon.com/images/M/MV5BOGEwYWIzOGEtMzY2Ny00NzE0LTkwZmQtYjk5NTE2ZmZiM2QxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+14",
  autor: "Stephenie Meyer (Libro)",
  reseña: "Un fenómeno cultural que definió el romance sobrenatural adolescente de su generación.",
  descripcion: "Bella Swan, una joven reservada que se muda al lluvioso pueblo de Forks, no imagina que su vida cambiará al conocer a Edward Cullen, un misterioso estudiante con secretos oscuros y una belleza inhumana. Lo que comienza como una atracción imposible se convierte en una historia de amor prohibido entre un humano y un vampiro. Con una estética melancólica, una atmósfera envolvente y una intensidad emocional juvenil, *Crepúsculo* marcó una generación y redefinió el amor sobrenatural en el cine moderno.",
  recomendacion: "Perfecta para quienes buscan pasión, misterio y un toque de peligro en el romance.",
  detalles: "Basada en la novela homónima de Stephenie Meyer. Protagonizada por Kristen Stewart y Robert Pattinson.",
  duracion: "2h 2min",
},

{
  id: 5,
  titulo: "Yo Antes de Ti",
  anio: 2016,
  genero: "Romance / Drama",
  categoria: "Basadas en Libros",
  imagen: "https://www.libreriasur.com.pe/imagenes/9789870/978987043466.webp",
  rangoEdad: "+16",
  autor: "Jojo Moyes (Libro)",
  reseña: "Una película emotiva que explora el amor, la vida y las decisiones difíciles. Prepárate para llorar.",
  descripcion: "Louisa Clark, una joven alegre y sin rumbo, consigue trabajo como cuidadora de Will Traynor, un exbanquero de espíritu rebelde que quedó paralizado tras un accidente. Lo que inicia como una relación profesional se convierte en una conexión profunda que desafía las barreras del dolor y las decisiones sobre la vida misma. *Yo Antes de Ti* es un retrato conmovedor sobre cómo el amor puede transformar incluso los destinos más rotos y cómo, a veces, amar significa saber dejar ir.",
  recomendacion: "Ideal para los amantes de los romances emotivos que dejan una huella en el corazón.",
  detalles: "Protagonizada por Emilia Clarke y Sam Claflin. Dirigida por Thea Sharrock.",
  duracion: "1h 50min",
},

{
  id: 6,
  titulo: "El Padrino",
  anio: 1972,
  genero: "Crimen / Drama",
  categoria: "Basadas en Libros",
  imagen: "https://m.media-amazon.com/images/M/MV5BZmNiNzM4MTctODI5YS00MzczLWE2MzktNzY4YmNjYjA5YmY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+18",
  autor: "Mario Puzo (Libro)",
  reseña: "Considerada una de las mejores películas de la historia. Un estudio magistral sobre la familia, el poder y la corrupción.",
  descripcion: "En el corazón de Nueva York, la familia Corleone reina desde las sombras. Cuando Vito Corleone, el respetado patriarca, es atacado, su hijo Michael —un joven reacio al mundo criminal— se ve obligado a asumir un papel que cambiará su destino. *El Padrino* es un retrato devastador del poder, la lealtad y la pérdida de la inocencia, donde los lazos familiares se entrelazan con el crimen y la tragedia. Su guion, dirección y actuaciones la convirtieron en una joya eterna del séptimo arte.",
  recomendacion: "Obligatoria para todo amante del cine. Una lección de dirección y narrativa impecable.",
  detalles: "Dirigida por Francis Ford Coppola. Ganadora de 3 Premios Óscar, incluido Mejor Película.",
  duracion: "2h 55min",
},
{
  id: 7,
  titulo: "Los Juegos del Hambre",
  anio: 2012,
  genero: "Ciencia Ficción / Acción",
  categoria: "Basadas en Libros",
  imagen: "https://es.web.img2.acsta.net/medias/nmedia/18/86/46/05/19945375.jpg",
  rangoEdad: "+13",
  autor: "Suzanne Collins (Libro)",
  reseña: "Una distopía feroz que muestra hasta dónde puede llegar la humanidad cuando el poder se vuelve espectáculo.",
  descripcion: "En un futuro posapocalíptico, la nación de Panem se levanta sobre las ruinas de lo que fue Estados Unidos. Cada año, el gobierno obliga a los distritos a enviar a dos jóvenes a una batalla televisada a muerte: los Juegos del Hambre. Katniss Everdeen, una chica fuerte y decidida, se ofrece voluntariamente para salvar a su hermana menor, sin imaginar que se convertirá en el símbolo de una revolución. Con una historia cargada de crítica social, sacrificio y esperanza, esta película combina acción intensa con una poderosa reflexión sobre la libertad y la resistencia.",
  recomendacion: "Perfecta para quienes disfrutan de la acción con trasfondo político y emocional.",
  detalles: "Protagonizada por Jennifer Lawrence, Josh Hutcherson y Woody Harrelson. Dirigida por Gary Ross.",
  duracion: "2h 22min",
},

{
  id: 8,
  titulo: "Bajo la Misma Estrella",
  anio: 2014,
  genero: "Drama / Romance",
  categoria: "Basadas en Libros",
  imagen: "https://m.media-amazon.com/images/M/MV5BYzJkNTQ1MmUtZjliYi00OGQwLTgyY2UtOTk3MTM1Mzk4NmRjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "John Green (Libro)",
  reseña: "Una historia desgarradora sobre el amor joven, la enfermedad y la belleza de lo efímero.",
  descripcion: "Hazel Grace, una adolescente brillante que vive conectada a un tanque de oxígeno, ve su vida cambiar cuando conoce a Augustus Waters, un chico carismático que ha sobrevivido al cáncer. Juntos emprenden un viaje emocional hacia Ámsterdam para conocer al autor de su novela favorita, pero lo que realmente encuentran es una verdad universal: el amor puede ser eterno, incluso en una vida demasiado corta. *Bajo la Misma Estrella* es una oda a la fragilidad humana y a la fuerza de amar pese al dolor.",
  recomendacion: "Una película que te hará llorar, reflexionar y valorar los pequeños momentos de la vida.",
  detalles: "Protagonizada por Shailene Woodley y Ansel Elgort. Dirigida por Josh Boone.",
  duracion: "2h 6min",
},

{
  id: 9,
  titulo: "It",
  anio: 2017,
  genero: "Terror / Suspenso",
  categoria: "Basadas en Libros",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdbXLtpf0dZyDCeZOKmbygEaiAKEcXManfow&s",
  rangoEdad: "+16",
  autor: "Stephen King (Libro)",
  reseña: "El clásico del terror reinventado con un equilibrio perfecto entre miedo, nostalgia y amistad.",
  descripcion: "En el tranquilo pueblo de Derry, un mal ancestral despierta cada 27 años para alimentarse del miedo de los niños. Cuando el pequeño Georgie desaparece, su hermano Bill y un grupo de amigos marginados, autodenominados 'El Club de los Perdedores', se enfrentan al terror encarnado en Pennywise, un payaso que se alimenta de sus peores pesadillas. *It* no solo es una historia de horror sobrenatural, sino una metáfora sobre el paso de la infancia a la madurez, y el valor de enfrentar lo que más tememos.",
  recomendacion: "Recomendada para quienes disfrutan del terror psicológico con un toque nostálgico al estilo ochentero.",
  detalles: "Dirigida por Andy Muschietti. Basada en la novela homónima de Stephen King.",
  duracion: "2h 15min",
},

{
  id: 10,
  titulo: "El Código Da Vinci",
  anio: 2006,
  genero: "Misterio / Thriller",
  categoria: "Basadas en Libros",
  imagen: "https://m.media-amazon.com/images/S/pv-target-images/b6308a567ef29464d38ae06d17d7efc6460dece1f500947ac64df8950e668d27.jpg",
  rangoEdad: "+13",
  autor: "Dan Brown (Libro)",
  reseña: "Un thriller intrigante que mezcla arte, religión y conspiración en una carrera contra el tiempo.",
  descripcion: "Cuando el profesor Robert Langdon es convocado al Museo del Louvre tras el asesinato de su curador, se ve envuelto en un enigma que podría cambiar el curso de la historia. Junto a la criptóloga Sophie Neveu, sigue una serie de pistas ocultas en las obras de Leonardo Da Vinci, descubriendo una red de secretos que desafía la fe y el poder de la Iglesia. *El Código Da Vinci* combina ritmo vertiginoso, historia y simbolismo en una aventura intelectual que atrapó al mundo entero.",
  recomendacion: "Ideal para amantes de los misterios, acertijos y teorías ocultas.",
  detalles: "Protagonizada por Tom Hanks y Audrey Tautou. Dirigida por Ron Howard.",
  duracion: "2h 29min",
},

{
  id: 11,
  titulo: "Las Ventajas de Ser Invisible",
  anio: 2012,
  genero: "Drama / Adolescente",
  categoria: "Basadas en Libros",
  imagen: "https://m.media-amazon.com/images/M/MV5BYzM0MDI3MjQtZTc0MC00YzNlLWExYjUtNjFlOTg3NmI5ZWUyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "Stephen Chbosky (Libro)",
  reseña: "Una historia honesta sobre crecer, sanar y encontrar un lugar donde uno pertenece.",
  descripcion: "Charlie, un joven tímido y solitario, inicia su primer año de secundaria marcado por la ansiedad y un pasado doloroso. Todo cambia cuando conoce a Sam y Patrick, dos hermanos que lo introducen en un mundo de libertad, amistad y música. A través de cartas íntimas, Charlie narra su viaje emocional, descubriendo el valor de sentirse 'infinito'. *Las Ventajas de Ser Invisible* captura la esencia de la adolescencia con sensibilidad, sinceridad y esperanza.",
  recomendacion: "Recomendada para quienes buscan una película íntima, emocional y profundamente humana.",
  detalles: "Protagonizada por Logan Lerman, Emma Watson y Ezra Miller. Dirigida por Stephen Chbosky.",
  duracion: "1h 43min",
},

{
  id: 12,
  titulo: "Cazadores de Sombras: Ciudad de Hueso",
  anio: 2013,
  genero: "Fantasía / Aventura",
  categoria: "Basadas en Libros",
  imagen: "https://m.media-amazon.com/images/M/MV5BNzQyZWMzNTAtM2U4YS00ODAxLTkyYjEtM2M5YjQ1N2U0ZGI2XkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "+13",
  autor: "Cassandra Clare (Libro)",
  reseña: "Un viaje al submundo oculto donde ángeles y demonios libran una guerra secreta.",
  descripcion: "Clary Fray lleva una vida normal hasta que presencia un asesinato en una discoteca que nadie más parece ver. Pronto descubre que pertenece a una antigua raza de guerreros conocida como los Cazadores de Sombras, encargados de proteger al mundo humano de los demonios. Entre batallas, revelaciones familiares y un amor prohibido, Clary deberá aceptar su destino en un universo oculto bajo las sombras de Nueva York. *Ciudad de Hueso* mezcla acción, misterio y romance en un mundo lleno de mitología moderna.",
  recomendacion: "Perfecta para los fans de la fantasía urbana con un toque romántico y juvenil.",
  detalles: "Protagonizada por Lily Collins y Jamie Campbell Bower. Dirigida por Harald Zwart.",
  duracion: "2h 10min",
},

  // ===============================
// 🔥 TOP 10 DE 2025 (PREVISIONES)
// ===============================
{
  id: 21,
  titulo: "Cómo entrenar a tu dragón",
  anio: 2025,
  genero: "Animación / Aventura / Fantasía",
  categoria: "Top 10",
  imagen: "https://m.media-amazon.com/images/S/pv-target-images/d6c3d19442144f7678ae5a96a91b6b8759dbb2404b889e2470cafceacbc11438.jpg",
  rangoEdad: "Apta para todos",
  autor: "Dean DeBlois (Director Original)",
  paisRodaje: "Estados Unidos / Islandia",
  reseña: "Una emotiva reimaginación en *live-action* del clásico animado que conquistó a una generación.",
  descripcion: "En una remota isla vikinga donde los dragones y los humanos han convivido en conflicto durante siglos, Hipo, un joven soñador e inventor, desafía las tradiciones de su pueblo al descubrir una amistad inesperada con un dragón herido al que llama Chimuelo. A través de su vínculo, ambos demostrarán que la comprensión puede ser más poderosa que la fuerza. En esta versión *live-action*, la historia amplía el universo de Berk con paisajes reales de Islandia y efectos visuales revolucionarios que dan vida a los dragones de forma nunca antes vista. Una historia sobre el crecimiento, la empatía y el valor de creer en lo imposible.",
  recomendacion: "Ideal para toda la familia y los fans de la trilogía original. Emotiva, visualmente majestuosa y llena de corazón.",
  detalles: "Adaptación *live-action* de DreamWorks. Dirigida por Dean DeBlois. Estreno mundial en junio de 2025.",
  duracion: "2h 10min",
},
{
  id: 22,
  titulo: "Superman",
  anio: 2025,
  genero: "Acción / Superhéroes / Ciencia Ficción",
  categoria: "Top 10",
  imagen: "https://i.ebayimg.com/00/s/MTYwMFgxMDY2/z/GU0AAOSw-6RoXMdt/$_57.JPG?set_id=880000500F",
  rangoEdad: "+13",
  autor: "DC Comics",
  paisRodaje: "Estados Unidos / Canadá",
  reseña: "Una nueva era comienza: un Superman más humano, más inspirador y más cercano a sus raíces.",
  descripcion: "Clark Kent, dividido entre su vida como periodista en Metrópolis y su deber como protector de la Tierra, enfrenta un mundo que ha perdido la fe en los héroes. Con un tono esperanzador y una estética moderna, esta versión reinventa al Hombre de Acero como símbolo de luz en tiempos de oscuridad. Mientras enfrenta amenazas tanto físicas como ideológicas, Superman debe redescubrir lo que realmente significa ser humano. Entre acción épica, romance clásico y dilemas morales, esta nueva entrega marca el renacimiento del Universo DC bajo la dirección de James Gunn.",
  recomendacion: "Perfecta para quienes buscan un regreso emocional a los valores clásicos del héroe más icónico del cine.",
  detalles: "Dirigida por James Gunn. Primera entrega del nuevo DC Universe (DCU). Protagonizada por David Corenswet y Rachel Brosnahan.",
  duracion: "2h 30min",
},
{
  id: 23,
  titulo: "La Hora De La Desaparición",
  anio: 2025,
  genero: "Suspenso / Misterio / Drama",
  categoria: "Top 10",
  imagen: "https://www.cinestar.com.pe/bucket/images/cine/e4b5c078-a175-4875-aaab-57dafe7c9dae.png/w=250",
  rangoEdad: "+16",
  autor: "Guion Original",
  paisRodaje: "Reino Unido",
  reseña: "Un thriller atmosférico que mezcla el misterio clásico con un terror psicológico inquietante.",
  descripcion: "En un pequeño pueblo costero donde la niebla nunca se disipa, un detective con un oscuro pasado investiga una serie de desapariciones que parecen ocurrir exactamente a la misma hora cada noche. A medida que profundiza, descubre conexiones entre los desaparecidos, un experimento científico secreto y su propia tragedia familiar. Con una narrativa cargada de tensión, fotografía melancólica y un ritmo envolvente, 'La Hora de la Desaparición' combina el misterio y la ciencia ficción de manera magistral, ofreciendo una experiencia que mantiene al espectador al borde del abismo hasta el último segundo.",
  recomendacion: "Para los amantes de los thrillers con atmósferas densas y giros inesperados.",
  detalles: "Producción británica dirigida por Sam Hargrave, con música de Ben Salisbury y Geoff Barrow.",
  duracion: "1h 55min",
},
{
  id: 24,
  titulo: "Caught Stealing",
  anio: 2025,
  genero: "Acción / Crimen / Thriller",
  categoria: "Top 10",
  imagen: "https://m.media-amazon.com/images/M/MV5BZjc3Y2I0M2YtZDY5NS00MGU5LWI5ZTEtOGNhMTZiZWFkMTljXkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "+18",
  autor: "Charlie Huston (Libro)",
  paisRodaje: "Estados Unidos",
  reseña: "Violenta, intensa y con estilo. Una adaptación *noir* que mezcla desesperación y redención.",
  descripcion: "Hank Thompson, un exjugador de béisbol con una vida arruinada por las malas decisiones, se ve envuelto en un violento laberinto criminal cuando un simple favor a un viejo amigo se convierte en una pesadilla. Perseguido por mafiosos, policías corruptos y sus propios demonios, Hank deberá usar toda su astucia para sobrevivir una sola noche en las calles de Nueva York. Con el sello visual de Darren Aronofsky, la película combina un tono sucio y realista con una exploración existencial del fracaso y la culpa.",
  recomendacion: "Ideal para quienes disfrutan de thrillers intensos con un toque filosófico y un ritmo implacable.",
  detalles: "Dirigida por Darren Aronofsky. Protagonizada por Patrick Wilson y Jennifer Jason Leigh. Basada en la novela de Charlie Huston.",
  duracion: "2h 05min",
},
{
  id: 25,
  titulo: "Thunderbolts",
  anio: 2025,
  genero: "Acción / Superhéroes / Marvel",
  categoria: "Top 10",
  imagen: "https://m.media-amazon.com/images/M/MV5BYWE2NmNmYTItZGY0ZC00MmY2LTk1NDAtMGUyMGEzMjcxNWM0XkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "+13",
  autor: "Marvel Studios",
  paisRodaje: "Estados Unidos / Canadá",
  reseña: "El lado oscuro del Universo Marvel cobra protagonismo con un equipo de antihéroes impredecibles.",
  descripcion: "Tras los eventos que sacudieron a los Vengadores, un grupo de exvillanos y agentes caídos en desgracia es reclutado por el gobierno para misiones que nadie más se atrevería a aceptar. Yelena Belova, Bucky Barnes, Taskmaster y Red Guardian deberán enfrentar una amenaza global mientras lidian con sus pasados y sus heridas emocionales. Pero en un equipo donde todos guardan secretos, la lealtad se convierte en un lujo. Con acción explosiva, humor ácido y dilemas morales profundos, 'Thunderbolts' explora el precio de la redención en un mundo que ya no cree en los héroes.",
  recomendacion: "Perfecta para quienes buscan una visión más madura y ambigua del Universo Marvel.",
  detalles: "Dirigida por Jake Schreier. Parte oficial del nuevo UCM. Producción de Kevin Feige.",
  duracion: "2h 15min",
},
{
  id: 26,
  titulo: "Los 4 Fantásticos: Primeros Pasos",
  anio: 2025,
  genero: "Superhéroes / Ciencia Ficción / Aventura",
  categoria: "Top 10",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSx8zTKC7w4mt1g4xYjCcXdSb1kX_D1SgPC2Q&s",
  rangoEdad: "+13",
  autor: "Marvel Comics",
  paisRodaje: "Estados Unidos / Canadá",
  reseña: "El esperado debut de la 'Primera Familia' del Universo Marvel. Ciencia, corazón y aventura.",
  descripcion: "Cuatro brillantes exploradores del espacio se ven transformados por un accidente cósmico que les otorga habilidades fuera de toda lógica. Mientras intentan comprender su nueva condición, deberán aprender a actuar como una familia para proteger la Tierra de una amenaza que proviene del mismo universo que los cambió. Con un tono de descubrimiento y asombro, esta versión presenta una visión más científica y emocional, mostrando a Reed Richards y Susan Storm como pioneros que desafían los límites de la física y la humanidad.",
  recomendacion: "Ideal para quienes aman las historias de ciencia ficción con corazón y épica visual.",
  detalles: "Dirigida por Matt Shakman. Parte del nuevo UCM. Se rodó parcialmente en Vancouver y Londres.",
  duracion: "2h 18min",
},
{
  id: 27,
  titulo: "Misión: Imposible – Sentencia Final (Parte 2)",
  anio: 2025,
  genero: "Acción / Espionaje / Aventura",
  categoria: "Top 10",
  imagen: "https://m.media-amazon.com/images/M/MV5BZTg0YzRkNDMtZTJjZS00Mjk0LTgwNGQtZWIzMTM3ZDRmZTQwXkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "+13",
  autor: "Christopher McQuarrie",
  paisRodaje: "Italia / Noruega / Reino Unido",
  reseña: "Tom Cruise lleva el riesgo a otro nivel en la conclusión más ambiciosa de la saga.",
  descripcion: "Ethan Hunt enfrenta su misión más peligrosa hasta la fecha: detener una inteligencia artificial fuera de control que amenaza con colapsar el orden mundial. Entre persecuciones imposibles, traiciones y sacrificios, Hunt debe decidir cuánto está dispuesto a perder por salvar al mundo. Con secuencias rodadas sin CGI, acrobacias reales y un tono emocionalmente más profundo, 'Sentencia Final' cierra una era de cine de acción práctica que redefine el género. La tensión no solo se mide en explosiones, sino en las decisiones que definen a un héroe.",
  recomendacion: "Una experiencia cinematográfica imprescindible para los amantes de la acción real.",
  detalles: "Dirigida por Christopher McQuarrie. Protagonizada por Tom Cruise, Rebecca Ferguson y Hayley Atwell.",
  duracion: "2h 40min",
},
{
  id: 28,
  titulo: "Blade",
  anio: 2025,
  genero: "Acción / Terror / Fantasía Oscura",
  categoria: "Top 10",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTe54HuJNspuNkUmcp-SyuK7UbUlOJ4hEFJQ&s",
  rangoEdad: "+16",
  autor: "Marvel Comics",
  paisRodaje: "Reino Unido / Marruecos",
  reseña: "Oscura, sangrienta y estilizada: el regreso del cazavampiros que redefinió el género.",
  descripcion: "Eric Brooks, conocido como Blade, es mitad humano, mitad vampiro. Un 'caminante diurno' que posee todas las fortalezas de los vampiros pero ninguna de sus debilidades... excepto su sed. En un mundo donde los clanes vampíricos dominan desde las sombras, Blade se convierte en la única barrera entre los humanos y la extinción. Esta reinvención del personaje ofrece una mezcla de acción gótica, terror moderno y temas existenciales sobre la identidad y el sacrificio. Con una fotografía oscura y una banda sonora que mezcla jazz con electrónica industrial, 'Blade' promete ser una de las películas más estilizadas del UCM.",
  recomendacion: "Perfecta para los fans del terror sobrenatural con un toque de superhéroes.",
  detalles: "Protagonizada por Mahershala Ali. Dirigida por Yann Demange. Parte del UCM Fase 6.",
  duracion: "1h 58min",
},
{
  id: 30,
  titulo: "F1",
  anio: 2025,
  genero: "Acción / Deporte / Drama",
  categoria: "Top 10",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMR_rBMZBVN6jJ4swPvcSlRqVYjl19riN9Ew&s",
  rangoEdad: "+13",
  autor: "Guion Original",
  paisRodaje: "Reino Unido / Italia / Mónaco",
  reseña: "Velocidad, pasión y peligro: una mirada al corazón humano detrás del rugido de los motores.",
  descripcion: "Cuando un legendario piloto de Fórmula 1 (Brad Pitt) decide salir del retiro para entrenar a un joven prodigio, ambos deben enfrentar el feroz mundo del automovilismo moderno, donde la velocidad no solo se mide en segundos, sino en decisiones que pueden costar la vida. Filmada en circuitos reales de la F1 con la colaboración oficial de las escuderías, 'F1' mezcla adrenalina pura con drama emocional, explorando la soledad del éxito, la rivalidad y el precio de la gloria. Cada curva, cada choque y cada victoria están grabados con una autenticidad que solo el cine puede transmitir.",
  recomendacion: "Imprescindible para los amantes de la velocidad, el realismo y las historias de redención.",
  detalles: "Dirigida por Joseph Kosinski ('Top Gun: Maverick'). Producida por Apple Studios y coproducida por Lewis Hamilton.",
  duracion: "2h 12min",
},


  // ===============================
// 🎬 KIDS
// ===============================
{
  id: 31,
  titulo: "Toy Story",
  anio: 1995,
  genero: "Animación / Aventura",
  categoria: "Kids",
  imagen: "https://xl.movieposterdb.com/15_10/1995/114709/xl_114709_70786505.jpg",
  rangoEdad: "Apta para todos",
  autor: "John Lasseter (Director)",
  reseña: "Un clásico atemporal de Pixar que celebra la amistad, la lealtad y el poder de la imaginación.",
  descripcion:
    "Cuando Andy, un niño lleno de imaginación, recibe un nuevo juguete llamado Buzz Lightyear, su viejo favorito Woody se siente replazado. Pero cuando los dos rivales se pierden lejos de casa, deberán trabajar juntos para regresar antes de que Andy los extrañe. Llena de humor, emoción y momentos inolvidables, Toy Story revolucionó el cine de animación y se convirtió en un emblema de la amistad y el crecimiento.",
  recomendacion: "Una película obligatoria para todas las edades. Divertida, emotiva e innovadora.",
  detalles: "La primera película de Pixar realizada completamente por ordenador. Un hito en la animación.",
  duracion: "1h 21min",
},
{
  id: 32,
  titulo: "Buscando a Nemo",
  anio: 2003,
  genero: "Animación / Familiar",
  categoria: "Kids",
  imagen: "https://images.cdn3.buscalibre.com/fit-in/360x360/9e/7d/9e7d0d7d4254b88e2ffad7245672b32a.jpg",
  rangoEdad: "Apta para todos",
  autor: "Andrew Stanton (Director)",
  reseña: "Una aventura acuática inolvidable que habla sobre la sobreprotección y el valor de soltar.",
  descripcion:
    "Marlin, un pez payaso demasiado protector, ve su vida cambiar cuando su hijo Nemo es capturado por un buzo. Emprende un viaje épico a través del océano acompañado por Dory, una pez azul con poca memoria pero mucho corazón. A lo largo del camino, enfrentan tiburones, medusas y corrientes marinas, aprendiendo que dejar ir también es una forma de amar. Una historia visualmente impresionante que combina humor, emoción y valentía.",
  recomendacion: "Un clásico moderno de Pixar. Visualmente hermoso y con mucho humor.",
  detalles: "Ganadora del Oscar a Mejor Película de Animación.",
  duracion: "1h 40min",
},
{
  id: 33,
  titulo: "Shrek",
  anio: 2001,
  genero: "Animación / Comedia",
  categoria: "Kids",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJYba3ne5xgEyCp1b-Jno526rKBljRLgg0jFx4Fj-CInGGaxrUCI0gEGOkNt7qmt2ESm0&usqp=CAU",
  rangoEdad: "Apta para todos",
  autor: "Andrew Adamson y Vicky Jenson (Directores)",
  reseña: "Una parodia inteligente de los cuentos de hadas que se convirtió en un éxito instantáneo.",
  descripcion:
    "Shrek, un ogro solitario que vive feliz en su pantano, ve su vida interrumpida cuando su hogar se llena de criaturas de cuentos de hadas expulsadas por el malvado Lord Farquaad. Para recuperar su tranquilidad, Shrek acepta rescatar a la princesa Fiona, sin saber que ella guarda un secreto. Con la ayuda de un burro parlante y mucho humor irreverente, esta aventura rompe los estereotipos de los cuentos clásicos con corazón y risas.",
  recomendacion: "Humor para adultos y niños. Muy recomendable.",
  detalles: "Primera película en ganar el Oscar a Mejor Película de Animación (categoría recién creada).",
  duracion: "1h 30min",
},
{
  id: 34,
  titulo: "Frozen",
  anio: 2013,
  genero: "Animación / Musical",
  categoria: "Kids",
  imagen: "https://cdn.shopify.com/s/files/1/0398/4202/1535/files/oRmfdrPmK85jCMDRCp9U2Q96sfq2HhhFl_LnqsraFlA_30b2a58c-bb9d-4c54-aff5-f6d7ca5c33e5_300x.png?v=1755166298",
  rangoEdad: "Apta para todos",
  autor: "Chris Buck y Jennifer Lee (Directores)",
  reseña: "El fenómeno de Disney que redefinió la narrativa de princesas, centrándose en el amor fraternal.",
  descripcion:
    "Cuando los poderes de Elsa escapan de su control y sumen al reino de Arendelle en un invierno eterno, su hermana Anna se embarca en un peligroso viaje junto a Kristoff, Sven y Olaf para traerla de vuelta. 'Frozen' combina una animación deslumbrante, canciones memorables y un mensaje poderoso sobre la aceptación y el amor entre hermanas. Una historia mágica que derrite corazones incluso en medio del hielo.",
  recomendacion: "Sus canciones son un éxito mundial. Imprescindible en Disney.",
  detalles: "Basada vagamente en el cuento de 'La Reina de las Nieves'. Ganó 2 Oscars.",
  duracion: "1h 42min",
},
{
  id: 35,
  titulo: "Kung Fu Panda",
  anio: 2008,
  genero: "Animación / Aventura",
  categoria: "Kids",
  imagen: "https://images.justwatch.com/poster/312538889/s718/kung-fu-panda.jpg",
  rangoEdad: "Apta para todos",
  autor: "Mark Osborne y John Stevenson (Directores)",
  reseña: "Divertida y con un gran mensaje de superación, mezclando acción de artes marciales con comedia.",
  descripcion:
    "Po, un panda torpe pero soñador, trabaja en la tienda de fideos de su padre hasta que, por accidente, es elegido como el legendario Guerrero Dragón. A pesar de su falta de destreza, Po demuestra que la fuerza interior y la perseverancia son las claves del verdadero héroe. Con espectaculares escenas de acción y humor encantador, 'Kung Fu Panda' combina artes marciales, filosofía y comedia en una lección de confianza en uno mismo.",
  recomendacion: "Excelente animación y peleas de artes marciales aptas para niños.",
  detalles: "Producida por Dreamworks Animation.",
  duracion: "1h 30min",
},
{
  id: 36,
  titulo: "Los Increíbles",
  anio: 2004,
  genero: "Animación / Superhéroes",
  categoria: "Kids",
  imagen: "https://es.web.img2.acsta.net/medias/nmedia/18/89/87/86/20070947.jpg",
  rangoEdad: "+7",
  autor: "Brad Bird (Director)",
  reseña: "Una película de superhéroes que funciona como una gran historia familiar y un thriller de acción.",
  descripcion:
    "Bob Parr, antes conocido como Mr. Increíble, vive frustrado en una vida normal tras la prohibición de los superhéroes. Pero cuando recibe una misteriosa misión secreta, él y su familia descubren que la verdadera fuerza está en trabajar juntos. 'Los Increíbles' combina acción trepidante, humor inteligente y un mensaje sobre la importancia de la familia, redefiniendo el género de superhéroes con estilo y corazón.",
  recomendacion: "Considerada una de las mejores películas de superhéroes de la historia, animada o no.",
  detalles: "Dirigida por Brad Bird, conocido por su trabajo en 'El gigante de hierro'.",
  duracion: "1h 55min",
},
{
  id: 37,
  titulo: "Coco",
  anio: 2017,
  genero: "Animación / Musical",
  categoria: "Kids",
  imagen: "https://lumiere-a.akamaihd.net/v1/images/p_coco_19736_fd5fa537.jpeg?region=0,0,540,810",
  rangoEdad: "Apta para todos",
  autor: "Lee Unkrich (Director)",
  reseña: "Una celebración visual y emocional de la cultura mexicana, la familia y el Día de Muertos.",
  descripcion:
    "Miguel, un niño apasionado por la música, desafía la prohibición familiar y, accidentalmente, cruza al colorido Mundo de los Muertos. Allí, emprende un viaje para descubrir la historia de su familia y el verdadero significado del recuerdo. Con canciones conmovedoras, una animación vibrante y un mensaje universal sobre el legado y el amor familiar, 'Coco' toca el corazón de grandes y pequeños por igual.",
  recomendacion: "Una de las películas más emotivas de Pixar. Hermosa y culturalmente rica.",
  detalles: "Ganadora del Oscar a Mejor Película de Animación y Mejor Canción Original.",
  duracion: "1h 45min",
},
{
  id: 38,
  titulo: "Encanto",
  anio: 2021,
  genero: "Animación / Musical",
  categoria: "Kids",
  imagen: "https://lumiere-a.akamaihd.net/v1/images/encanto_ka_las_pay1_92ad7410.jpeg?region=0%2C0%2C1080%2C1350",
  rangoEdad: "Apta para todos",
  autor: "Byron Howard y Jared Bush (Directores)",
  reseña: "Una explosión de color y música inspirada en la cultura colombiana, con un fuerte mensaje sobre el legado familiar.",
  descripcion:
    "En una mágica casa escondida en las montañas de Colombia, cada miembro de la familia Madrigal tiene un don especial, excepto Mirabel. Sin embargo, cuando la magia que los rodea comienza a desvanecerse, Mirabel será la única capaz de descubrir el origen del problema y salvar a su familia. 'Encanto' es una carta de amor a la cultura latina, con canciones vibrantes, colores deslumbrantes y una historia que enseña que todos tenemos un valor único.",
  recomendacion: "Un éxito de Disney con canciones pegadizas y un enfoque moderno en la dinámica familiar.",
  detalles: "La banda sonora incluye canciones de Lin-Manuel Miranda.",
  duracion: "1h 42min",
},
{
  id: 39,
  titulo: "Ratatouille",
  anio: 2007,
  genero: "Animación / Comedia",
  categoria: "Kids",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLdN29MakwxGl8AQ0HuwkLIxaFASaSB72H9w&s",
  rangoEdad: "Apta para todos",
  autor: "Brad Bird (Director)",
  reseña: "Una comedia encantadora que demuestra que cualquiera puede lograr sus sueños, incluso una rata chef.",
  descripcion:
    "Remy, una rata con un extraordinario sentido del gusto, sueña con convertirse en chef en el corazón de París. Cuando conoce a Linguini, un joven sin talento culinario, ambos se asocian en secreto para conquistar el mundo de la alta cocina. 'Ratatouille' mezcla humor, pasión y una exquisita animación que celebra la creatividad, el trabajo duro y la búsqueda de los sueños, sin importar de dónde vengas.",
  recomendacion: "Visualmente exquisita y un deleite para los amantes de la gastronomía.",
  detalles: "Ganadora del Oscar a Mejor Película de Animación.",
  duracion: "1h 51min",
},
{
  id: 40,
  titulo: "Monsters Inc",
  anio: 2001,
  genero: "Animación / Fantasía",
  categoria: "Kids",
  imagen: "https://upload.wikimedia.org/wikipedia/en/6/63/Monsters_Inc.JPG",
  rangoEdad: "Apta para todos",
  autor: "Pete Docter (Director)",
  reseña: "Una idea original y divertida que convierte a los monstruos del armario en personajes adorables.",
  descripcion:
    "En la ciudad de Monstruópolis, los gritos de los niños son la fuente de energía. Sulley y Mike, los mejores asustadores de la compañía, ven su mundo trastocado cuando una pequeña niña llamada Boo entra accidentalmente en su mundo. Con humor y ternura, 'Monsters Inc' demuestra que la risa puede ser más poderosa que el miedo y que incluso los monstruos tienen un gran corazón.",
  recomendacion: "Una de las películas más tiernas y divertidas de Pixar.",
  detalles: "Nominada a 4 Oscars, ganando el de Mejor Canción Original.",
  duracion: "1h 32min",
},
{
  id: 41,
  titulo: "Zootopia",
  anio: 2016,
  genero: "Animación / Aventura",
  categoria: "Kids",
  imagen: "https://lumiere-a.akamaihd.net/v1/images/movie_poster_zootopia_866a1bf2.jpeg?region=0%2C0%2C300%2C450",
  rangoEdad: "Apta para todos",
  autor: "Byron Howard y Rich Moore (Directores)",
  reseña: "Una aventura de detectives con un mensaje social sutil y relevante para todas las edades.",
  descripcion:
    "En una metrópoli habitada por animales de todas las especies, Judy Hopps, una conejita determinada, se convierte en la primera policía de su clase. Junto a un zorro estafador llamado Nick Wilde, deberá resolver un misterioso caso que podría cambiar la ciudad para siempre. 'Zootopia' combina acción, humor y crítica social en una historia tan entretenida como inspiradora.",
  recomendacion: "Inteligente, divertida y con una gran animación. Ganadora del Oscar.",
  detalles: "Ganadora del Oscar a Mejor Película de Animación.",
  duracion: "1h 48min",
},
{
  id: 42,
  titulo: "Moana",
  anio: 2016,
  genero: "Animación / Aventura",
  categoria: "Kids",
  imagen: "https://i.pinimg.com/474x/e0/ae/48/e0ae489f31577f6c185ee9b13f39582c.jpg",
  rangoEdad: "Apta para todos",
  autor: "Ron Clements y John Musker (Directores)",
  reseña: "Una aventura marítima llena de mitología polinesia, personajes fuertes y canciones inolvidables.",
  descripcion:
    "Moana, una joven valiente de una isla del Pacífico, siente el llamado del océano y se embarca en una travesía para restaurar el corazón robado de una diosa. Con la ayuda del carismático semidiós Maui, enfrentará criaturas míticas y descubrirá su verdadero destino. 'Moana' es una historia épica de autodescubrimiento, empoderamiento y respeto por la naturaleza, acompañada por una de las mejores bandas sonoras de Disney.",
  recomendacion: "Perfecta para los fans de las historias de heroínas y la aventura en el mar.",
  detalles: "Canciones de Lin-Manuel Miranda. Un éxito de crítica y público.",
  duracion: "1h 47min",
},
{
  id: 43,
  titulo: "Intensamente",
  anio: 2015,
  genero: "Animación / Emocional",
  categoria: "Kids",
  imagen: "https://mx.web.img3.acsta.net/pictures/17/08/07/21/43/466493.jpg",
  rangoEdad: "Apta para todos",
  autor: "Pete Docter (Director)",
  reseña: "Una obra maestra conceptual que explica la complejidad de las emociones humanas de forma sencilla y profunda.",
  descripcion:
    "Dentro de la mente de Riley, una niña de 11 años, viven cinco emociones que controlan sus reacciones: Alegría, Tristeza, Miedo, Furia y Desagrado. Cuando la familia se muda a otra ciudad, Alegría y Tristeza se pierden, dejando el equilibrio emocional en caos. 'Intensamente' es una de las películas más originales y conmovedoras de Pixar, que enseña a aceptar todas las emociones como parte esencial del crecimiento.",
  recomendacion: "Una película esencial para niños y adultos. Educativa y muy conmovedora.",
  detalles: "Ganadora del Oscar a Mejor Película de Animación.",
  duracion: "1h 35min",
},
{
  id: 44,
  titulo: "Luca",
  anio: 2021,
  genero: "Animación / Amistad",
  categoria: "Kids",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl2B5oqGa40uuvMiA8rNF-PlsjWg2DfR3DRtVXsa6RCjRbBsUIRHmiSi2ua5yq5OxdPB8&usqp=CAU",
  rangoEdad: "Apta para todos",
  autor: "Enrico Casarosa (Director)",
  reseña: "Una carta de amor a la amistad, la aceptación y la cultura italiana, con un toque de fantasía veraniega.",
  descripcion:
    "En un pequeño pueblo costero italiano, Luca y su amigo Alberto esconden un gran secreto: son monstruos marinos que pueden transformarse en humanos al salir del agua. A medida que viven un verano lleno de aventuras, ambos aprenden el verdadero significado de la amistad y la aceptación. 'Luca' es una historia cálida y colorida sobre crecer, encontrar tu lugar en el mundo y celebrar lo que te hace diferente.",
  recomendacion: "Una película cálida y encantadora sobre el valor de ser diferente.",
  detalles: "Ambientada en la Riviera Italiana. Un enfoque visual único y colorido.",
  duracion: "1h 35min",
},
{
  id: 45,
  titulo: "Up",
  pais: "Estados Unidos",
  anio: 2009,
  genero: "Animación / Aventura",
  categoria: "Kids",
  imagen: "https://www.funeralnatural.net/sites/default/files/pelicula/imagen/upcartel.jpg",
  rangoEdad: "Apta para todos",
  autor: "Pete Docter (Director)",
  reseña: "Una montaña rusa emocional. Su inicio es uno de los segmentos más aclamados en la historia de la animación.",
  descripcion:
    "Carl Fredricksen, un viudo de espíritu aventurero, decide cumplir su sueño de viajar a Sudamérica amarrando miles de globos a su casa. Pero su viaje da un giro inesperado cuando un niño explorador llamado Russell se cuela a bordo. 'Up' es una historia sobre la pérdida, la esperanza y la amistad, contada con una ternura y profundidad que trascienden edades.",
  recomendacion: "No te dejes engañar por los globos, es una película profundamente adulta y conmovedora.",
  detalles: "Ganadora de 2 Oscars. Nombrada a Mejor Película, un honor raro para la animación.",
  duracion: "1h 36min",
},
{
  id: 46,
  titulo: "La Sirenita",
  anio: 2023,
  genero: "Musical / Fantasía",
  categoria: "Kids",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyrAAhriSRmnPNElfM4_OLBos6XwgYucYcHQ&s",
  rangoEdad: "+7",
  autor: "Rob Marshall (Director)",
  reseña: "La versión *live-action* del clásico de Disney, con nuevas canciones y efectos visuales impresionantes.",
  descripcion:
    "Ariel, una joven sirena fascinada por el mundo humano, sueña con conocer la tierra. Cuando se enamora de un príncipe humano, hace un trato arriesgado con la bruja del mar Úrsula para cambiar su destino. Esta nueva versión del clásico combina nostalgia, actuaciones cautivadoras y una espectacular puesta en escena que revive la magia del cuento original con un toque moderno.",
  recomendacion: "Para revivir el clásico con una perspectiva moderna y una gran actuación vocal.",
  detalles: "Adaptación *live-action* del clásico animado de 1989.",
  duracion: "2h 15min",
},
{
  id: 47,
  titulo: "Mi villano favorito",
  anio: 2010,
  genero: "Animación / Comedia",
  categoria: "Kids",
  imagen: "https://play-lh.googleusercontent.com/HihhmPVUKMThE7Ik3NwRG33NDfhvSGTsljZUYHNMJOJ0dYcHwrhde6H0EhcWDokCBc30rQ",
  rangoEdad: "Apta para todos",
  autor: "Pierre Coffin y Chris Renaud (Directores)",
  reseña: "Presentó al mundo a los adorables Minions en una divertida historia sobre el descubrimiento de la paternidad.",
  descripcion:
    "Gru, un supervillano con planes para robar la Luna, ve su vida patas arriba cuando adopta a tres niñas huérfanas como parte de su plan. Lo que comienza como una estrategia malvada se transforma en una lección de amor, ternura y redención. 'Mi villano favorito' combina humor, acción y ternura en una historia que demuestra que incluso los corazones más fríos pueden cambiar.",
  recomendacion: "Comedia animada ligera y muy divertida, especialmente por los Minions.",
  detalles: "La película que inició la exitosa franquicia de los Minions.",
  duracion: "1h 35min",
},
{
  id: 48,
  titulo: "Sing",
  anio: 2016,
  genero: "Animación / Musical",
  categoria: "Kids",
  imagen: "https://play-lh.googleusercontent.com/m5r43n1UznZC5TJCJNGX7-rg-6R9uv4cC7zbe3CAD62DryoIqnb6ci6qjitd0-6Qvvo",
  rangoEdad: "Apta para todos",
  autor: "Garth Jennings (Director)",
  reseña: "Una celebración de la música con personajes animales y una banda sonora llena de éxitos.",
  descripcion:
    "Cuando Buster Moon, un entusiasta koala dueño de un teatro en decadencia, organiza un concurso de canto para salvarlo, una variada colección de animales talentosos encuentra una oportunidad para brillar. 'Sing' es una historia llena de ritmo, humor y emoción que celebra los sueños, el esfuerzo y el poder de la música para unir a todos.",
  recomendacion: "Mucha música y diversión. Ideal para una tarde familiar y animada.",
  detalles: "Producida por Illumination Entertainment.",
  duracion: "1h 48min",
},
{
  id: 49,
  titulo: "Pinocho",
  anio: 2022,
  genero: "Animación / Fantasía",
  categoria: "Kids",
  imagen: "https://i.pinimg.com/564x/5e/b4/e4/5eb4e4e89a1f7d0a556a5e266d868621.jpg",
  rangoEdad: "+13",
  autor: "Guillermo del Toro (Director)",
  reseña: "Una reinterpretación oscura, visualmente deslumbrante y profundamente emotiva del cuento clásico.",
  descripcion:
    "En esta versión en *stop-motion* del clásico cuento, Guillermo del Toro reinventa la historia del muñeco de madera que cobra vida. Ambientada en la Italia fascista, la película explora temas de pérdida, amor, identidad y humanidad con una profundidad poética única. Con una animación artesanal impresionante y una atmósfera melancólica, 'Pinocho' es una obra maestra visual y emocional que redefine el concepto del cine animado.",
  recomendacion: "Si buscas una animación artística, adulta y con un mensaje político y emocional profundo.",
  detalles: "Ganadora del Oscar a Mejor Película de Animación. Obra maestra de *stop-motion*.",
  duracion: "1h 56min",
},

  // ===============================
  // 🎥 DOCUMENTALES
  // ===============================
  {
  id: 50,
  titulo: "Nuestro Planeta",
  anio: 2019,
  genero: "Naturaleza / Ciencia",
  categoria: "Documentales",
  imagen: "https://www.lavanguardia.com/peliculas-series/images/serie/poster/2019/4/w1280/aV05lTbDLzeA1qkZxd4AJKUJ6mN.jpg",
  rangoEdad: "Apta para todos",
  autor: "Alastair Fothergill (Director)",
  reseña: "Una obra maestra visual que combina la belleza majestuosa del mundo natural con un mensaje urgente sobre la conservación. Cada episodio es una invitación a reflexionar sobre la interconexión entre las especies y el impacto humano en la Tierra.",
  descripcion: "Esta serie documental nos transporta a los hábitats más asombrosos del planeta: desde las selvas tropicales llenas de vida hasta los desiertos más áridos, pasando por los océanos y las tundras heladas. Con imágenes de una calidad cinematográfica impresionante y narración del legendario David Attenborough, 'Nuestro Planeta' no solo celebra la diversidad del mundo natural, sino que también denuncia la pérdida acelerada de ecosistemas provocada por la actividad humana. A lo largo de sus episodios, combina asombro visual con un mensaje profundo sobre la urgencia de proteger la vida que nos rodea.",
  recomendacion: "Imprescindible por su cinematografía, su emotiva narrativa y su poderoso mensaje ecológico.",
  detalles: "Narrado por David Attenborough y producido por Netflix en colaboración con WWF. Filmado en más de 50 países a lo largo de cuatro años, con tecnología 4K. Ganador de múltiples premios Emmy.",
  duracion: "Serie, 8 episodios"
},
{
  id: 51,
  titulo: "Blackfish",
  anio: 2013,
  genero: "Animales / Denuncia",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BNzkzYmRmYTMtMTE5OS00NWYyLTg5MzgtOGM3ZjE1N2MwMTJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "Gabriela Cowperthwaite (Directora)",
  reseña: "Impactante, valiente y profundamente emocional. ‘Blackfish’ cambió para siempre la forma en que el público percibe el entretenimiento con animales marinos, revelando una verdad dolorosa detrás de los espectáculos de orcas.",
  descripcion: "El documental sigue la historia de Tilikum, una orca en cautiverio involucrada en la muerte de varias personas, y expone las prácticas de la industria del entretenimiento marino. A través de entrevistas con exentrenadores, científicos y expertos en comportamiento animal, ‘Blackfish’ revela el sufrimiento físico y psicológico de las orcas encerradas en parques acuáticos. Más allá del caso de Tilikum, la película es una crítica feroz a la explotación animal y un llamado global a la empatía y la conciencia ambiental. Su lanzamiento generó un movimiento internacional que transformó la industria de los parques temáticos.",
  recomendacion: "Un documental de denuncia que te hará replantearte los parques acuáticos y la relación del ser humano con los animales.",
  detalles: "Tuvo un enorme impacto social y mediático, reduciendo significativamente la popularidad de SeaWorld. Nominado a múltiples premios internacionales y considerado uno de los documentales más influyentes de la década.",
  duracion: "1h 23min"
},
{
  id: 52,
  titulo: "The Social Dilemma",
  anio: 2020,
  genero: "Tecnología / Sociedad",
  categoria: "Documentales",
  imagen: "https://upload.wikimedia.org/wikipedia/en/2/27/Social_dilemma_xlg.jpg",
  rangoEdad: "+16",
  autor: "Jeff Orlowski (Director)",
  reseña: "Una mirada inquietante a la era digital. Combina testimonios reales y dramatizaciones para mostrar cómo las redes sociales moldean nuestros pensamientos, emociones y comportamientos.",
  descripcion: "A través de entrevistas con exejecutivos y diseñadores de grandes empresas tecnológicas como Google, Facebook y Twitter, ‘The Social Dilemma’ explora cómo los algoritmos están diseñados para manipular la atención humana. El documental analiza los efectos psicológicos, sociales y políticos de vivir en un mundo dominado por las redes, desde la polarización social hasta la adicción a los dispositivos. Con una narrativa ágil e impactante, plantea una pregunta esencial: ¿quién controla realmente la información que consumimos y cómo afecta nuestra libertad individual?",
  recomendacion: "Si usas redes sociales, este documental es una experiencia reveladora que te hará ver el mundo digital desde otra perspectiva.",
  detalles: "Producido por Netflix. Incluye dramatizaciones protagonizadas por Skyler Gisondo. Ganador del premio Emmy al Mejor Documental de Impacto Social.",
  duracion: "1h 34min"
},
{
  id: 53,
  titulo: "Seaspiracy",
  anio: 2021,
  genero: "Océanos / Ecología",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BOWUzZDNjZTEtZDM1Mi00ODVkLWI4Y2UtYjAwZGVlM2YwNTg4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+16",
  autor: "Ali Tabrizi (Director)",
  reseña: "Provocador, revelador y sumamente polémico. ‘Seaspiracy’ desafía todo lo que creías saber sobre la pesca y el consumo de productos marinos.",
  descripcion: "El joven cineasta Ali Tabrizi se embarca en una investigación personal que lo lleva a descubrir la devastadora realidad oculta detrás de la industria pesquera global. Desde la contaminación plástica hasta la sobrepesca masiva, el documental desenmascara cómo las grandes corporaciones y los gobiernos contribuyen a la destrucción de los ecosistemas marinos. Con imágenes crudas, entrevistas reveladoras y un tono de denuncia, ‘Seaspiracy’ pone en evidencia las contradicciones del activismo ambiental moderno y plantea una pregunta incómoda: ¿es posible consumir pescado de manera sostenible?",
  recomendacion: "Un llamado urgente a repensar nuestros hábitos alimenticios y la salud de los océanos. Perfecto para quienes buscan documentales de impacto.",
  detalles: "Producción de Netflix respaldada por Kip Andersen, creador de ‘Cowspiracy’. Generó gran debate en redes sociales y medios ambientales por sus contundentes afirmaciones.",
  duracion: "1h 29min"
},
{
  id: 54,
  titulo: "The Tinder Swindler",
  anio: 2022,
  genero: "Crimen / Real",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BNTQ5YzM2YzQtNGY0ZS00ZjUyLThmN2YtYzlmNTEzMmQ0YzgyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+16",
  autor: "Felicity Morris (Directora)",
  reseña: "Una historia real tan increíble que parece salida de una película de suspenso. ‘The Tinder Swindler’ combina el ritmo del *true crime* con la emoción del drama humano.",
  descripcion: "A través de testimonios de mujeres de diferentes países, este documental reconstruye la historia de un hombre que utilizó la aplicación de citas Tinder para seducir, manipular y estafar a sus víctimas, haciéndose pasar por un empresario millonario. Con un montaje ágil y giros sorprendentes, la película revela el poder de la manipulación emocional y las trampas del mundo digital. Más allá del engaño, muestra la valentía de las víctimas al unirse para desenmascarar la verdad y exponer una red de mentiras que se extendió por toda Europa.",
  recomendacion: "Si te gustan las historias de crímenes reales y el suspenso psicológico, este documental te mantendrá atrapado de principio a fin.",
  detalles: "Dirigido por Felicity Morris y producido por los creadores de ‘Don’t F**k With Cats’. Se convirtió en uno de los documentales más vistos de Netflix en su estreno, inspirando incluso memes y debates globales sobre seguridad en citas online.",
  duracion: "1h 54min"
},
{
  id: 55,
  titulo: "13th",
  anio: 2016,
  genero: "Sociedad / Política",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMjAwMjU5NTAzOF5BMl5BanBnXkFtZTgwMjQwODQxMDI@._V1_.jpg",
  rangoEdad: "+16",
  autor: "Ava DuVernay (Directora)",
  reseña: "Poderoso, esclarecedor y profundamente necesario. '13th' expone con rigor histórico y emocional la continuidad entre la esclavitud y el encarcelamiento masivo en Estados Unidos.",
  descripcion: "El documental toma su título de la Decimotercera Enmienda de la Constitución de los EE. UU., que abolió la esclavitud salvo como castigo por un crimen. A partir de ese punto, Ava DuVernay construye un relato estremecedor sobre cómo el sistema judicial y carcelario estadounidense perpetúa la discriminación racial bajo nuevas formas. Mediante imágenes de archivo, entrevistas con activistas, académicos y políticos, '13th' ofrece una visión integral del racismo estructural y el poder de las corporaciones privadas detrás del negocio penitenciario. Es una clase magistral de historia, política y humanidad.",
  recomendacion: "Una película vital para entender las raíces del racismo y la desigualdad en la sociedad moderna.",
  detalles: "Nominada al Oscar a Mejor Documental y ganadora del BAFTA. Dirigida por Ava DuVernay (‘Selma’). Distribuida por Netflix y reconocida por la ONU por su impacto social.",
  duracion: "1h 40min"
},
{
  id: 56,
  titulo: "David Attenborough: A Life on Our Planet",
  anio: 2020,
  genero: "Naturaleza / Reflexión",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BNzc0NzdhZWUtOTRjMi00ZjllLTgzOTItOTc4ZGI0NWU1NmJiXkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "Apta para todos",
  autor: "Alastair Fothergill, Jonnie Hughes (Directores)",
  reseña: "Una obra profundamente conmovedora. El legendario naturalista David Attenborough comparte su testamento personal sobre el estado del planeta y su visión de esperanza para el futuro.",
  descripcion: "En este documental íntimo y visualmente impresionante, Attenborough repasa más de 90 años de vida dedicados a explorar la naturaleza. Desde los primeros años de su carrera hasta el presente, observa con tristeza y sabiduría cómo la biodiversidad del planeta ha disminuido drásticamente. Pero no todo es desesperanza: Attenborough ofrece soluciones reales y un llamado urgente a revertir el daño. Su voz, serena pero contundente, guía un viaje emocional a través del tiempo y la conciencia ecológica.",
  recomendacion: "Esencial para cualquier amante de la naturaleza y defensor del medio ambiente.",
  detalles: "Producido por Silverback Films y Netflix. Considerado el 'testimonio' ambiental de Attenborough. Ganador del Emmy al Mejor Documental de Naturaleza.",
  duracion: "1h 23min"
},
{
  id: 57,
  titulo: "My Octopus Teacher",
  anio: 2020,
  genero: "Naturaleza / Vida Marina",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BYWU5OGMxYjktMWY5Ny00NDJhLTgwMDktNjVmMTExZGIyODljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "Apta para todos",
  autor: "Pippa Ehrlich y James Reed (Directores)",
  reseña: "Tierno, poético y visualmente asombroso. Este documental muestra cómo una conexión inesperada entre un humano y un pulpo puede transformar la manera en que vemos la naturaleza.",
  descripcion: "El cineasta sudafricano Craig Foster, tras pasar por una etapa de agotamiento emocional, comienza a bucear diariamente en un bosque submarino frente a Ciudad del Cabo. Allí conoce a una hembra de pulpo común, con la que desarrolla una sorprendente relación de confianza y aprendizaje mutuo. A través de sus encuentros, Foster reflexiona sobre la inteligencia, la empatía y la interdependencia entre las especies. Filmado con una belleza hipnótica, ‘My Octopus Teacher’ es tanto una carta de amor al océano como una meditación sobre la conexión humana con la naturaleza.",
  recomendacion: "Ganador del Oscar a Mejor Documental. Ideal para quienes buscan inspiración, calma y belleza.",
  detalles: "Producido por Netflix y Sea Change Project. Rodado durante más de 300 días de buceo consecutivo.",
  duracion: "1h 25min"
},
{
  id: 58,
  titulo: "American Factory",
  anio: 2019,
  genero: "Trabajo / Sociedad",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BY2I1ZWJmNDUtMzc5OC00YzVmLTliZWItNTczZDQ0YTNiOTZjXkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "+13",
  autor: "Steven Bognar y Julia Reichert (Directores)",
  reseña: "Una mirada fascinante a la globalización moderna. Muestra el choque cultural entre trabajadores estadounidenses y empresarios chinos en una misma fábrica.",
  descripcion: "Tras el cierre de una planta de General Motors en Ohio, una empresa china de vidrios automotrices compra las instalaciones y reabre la fábrica. El documental sigue a los trabajadores mientras intentan adaptarse a un nuevo modelo laboral, marcado por la disciplina asiática y la pérdida de las garantías americanas. ‘American Factory’ expone con humanidad los retos de la economía global: el trabajo, la identidad y la dignidad frente al avance tecnológico y la producción masiva.",
  recomendacion: "Un retrato honesto y necesario sobre los efectos de la globalización en la clase trabajadora.",
  detalles: "Primer documental producido por Higher Ground, la compañía de Barack y Michelle Obama. Ganador del Oscar a Mejor Documental en 2020.",
  duracion: "1h 50min"
},
{
  id: 59,
  titulo: "Crip Camp",
  anio: 2020,
  genero: "Derechos Humanos / Historia",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BYmI4ODAyMDctODU4My00MWFmLThiN2MtYTAwNWFiMzlhY2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "Nicole Newnham y James LeBrecht (Directores)",
  reseña: "Una historia poderosa y llena de esperanza. ‘Crip Camp’ celebra el espíritu revolucionario de un grupo de jóvenes con discapacidad que cambió la historia de los derechos civiles en EE. UU.",
  descripcion: "A principios de los años 70, un grupo de adolescentes asiste a un campamento de verano llamado Camp Jened, un espacio libre de prejuicios donde las personas con discapacidad podían sentirse plenamente aceptadas. Años más tarde, muchos de ellos se convierten en líderes del movimiento por los derechos de las personas con discapacidad. Combinando material de archivo vibrante con entrevistas actuales, ‘Crip Camp’ demuestra cómo un simple verano puede encender una revolución social.",
  recomendacion: "Inspirador y profundamente humano. Un recordatorio de que la inclusión es una lucha colectiva.",
  detalles: "Producido por Higher Ground Productions (Barack y Michelle Obama). Nominado al Oscar y ganador del premio del público en Sundance.",
  duracion: "1h 47min"
},
{
  id: 60,
  titulo: "The Deepest Breath",
  anio: 2023,
  genero: "Aventura / Océano",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMmY2YmUwZDMtNjRmNi00ODJhLTllZjYtYzk4ZDg3MTE4ZjA4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "Laura McGann (Directora)",
  reseña: "Una experiencia intensa y emocional. Combina la belleza del océano con el riesgo mortal del buceo libre, en una historia de pasión, sacrificio y amor por el mar.",
  descripcion: "‘The Deepest Breath’ narra la historia paralela de Alessia Zecchini, una buceadora italiana de apnea, y Stephen Keenan, un buzo de seguridad irlandés. Unidos por su amor al océano, sus caminos se cruzan en la búsqueda de récords bajo el agua. Con imágenes impresionantes y una tensión constante, el documental explora los límites físicos y mentales del cuerpo humano, así como la conexión espiritual con el mar. Una oda visual a la libertad y al peligro.",
  recomendacion: "Ideal para amantes del océano, la adrenalina y las historias de superación extrema.",
  detalles: "Producción original de Netflix, con filmaciones en el Mar Rojo y entrevistas exclusivas. Aclamado en el Festival de Sundance 2023.",
  duracion: "1h 48min"
},
{
  id: 61,
  titulo: "Beckham",
  anio: 2023,
  genero: "Deporte / Biografía",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BZmNmZTU5ZTUtZTc0NS00ZWJlLWFlMzUtMDRmZDgzMDhjNmM0XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg",
  rangoEdad: "+13",
  autor: "Fisher Stevens (Director)",
  reseña: "Un retrato íntimo y sincero del ícono mundial del fútbol. Muestra al David Beckham más humano: el deportista, el padre, el esposo y el símbolo cultural.",
  descripcion: "A lo largo de cuatro episodios, esta serie documental sigue la vida de David Beckham, desde sus humildes inicios en Londres hasta convertirse en una superestrella global. Con material de archivo inédito y entrevistas exclusivas, ‘Beckham’ ofrece una mirada equilibrada a su carrera deportiva, su relación con Victoria Beckham y los desafíos de vivir bajo el escrutinio público. Una historia de éxito, sacrificio y perseverancia.",
  recomendacion: "Perfecto para fans del fútbol y quienes disfrutan las biografías inspiradoras.",
  detalles: "Miniserie de 4 episodios producida por Netflix. Dirigida por Fisher Stevens (‘Before the Flood’). Filmada con la colaboración directa de la familia Beckham.",
  duracion: "4 episodios (aprox. 4 horas)"
},
{
  id: 62,
  titulo: "Arnold",
  anio: 2023,
  genero: "Biografía / Superación",
  categoria: "Documentales",
  imagen: "https://images.plex.tv/photo?size=medium-360&scale=1&url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2Fo9KmWrG9rbFhB7jWW4vFHTmqv28.jpg",
  rangoEdad: "+16",
  autor: "Lesley Chilcott (Directora)",
  reseña: "La historia definitiva de Arnold Schwarzenegger. Desde su juventud en Austria hasta su reinado en Hollywood y la política estadounidense.",
  descripcion: "‘Arnold’ es una miniserie documental que explora las tres etapas principales de la vida de Schwarzenegger: el atleta, el actor y el político. Con entrevistas sinceras, imágenes inéditas y reflexiones personales, el documental revela al hombre detrás del mito, mostrando sus ambiciones, fracasos y aprendizajes. Más que una biografía, es un retrato de la determinación y la reinvención constante.",
  recomendacion: "Inspiradora, llena de energía y carisma. Un homenaje a la perseverancia y la disciplina.",
  detalles: "Miniserie de 3 episodios dirigida por Lesley Chilcott. Estrenada en Netflix en 2023 con gran éxito global.",
  duracion: "3 episodios (aprox. 3 horas)"
},
{
  id: 63,
  titulo: "Billie Eilish: The World's a Little Blurry",
  anio: 2021,
  genero: "Música / Juventud",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMDk5NmI4NGMtYzk4MS00NDlhLTlkZGMtNzEzZTJiZjFkYjgyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "R.J. Cutler (Director)",
  reseña: "Íntimo, crudo y emocionalmente honesto. Una mirada sin filtros a la vida y el ascenso meteórico de Billie Eilish.",
  descripcion: "El documental sigue el proceso creativo de Billie Eilish mientras graba su álbum debut ‘When We All Fall Asleep, Where Do We Go?’. Entre giras, premios y desafíos personales, la película muestra a una artista joven enfrentando el peso de la fama y la salud mental en la era digital. Con escenas familiares y momentos musicales poderosos, ‘The World’s a Little Blurry’ es tanto un retrato generacional como una carta abierta a la autenticidad.",
  recomendacion: "Ideal para fans de la música contemporánea y para quienes buscan entender el precio del éxito a temprana edad.",
  detalles: "Documental original de Apple TV+, dirigido por R.J. Cutler. Nominado al Grammy y al Critics Choice Documentary Award.",
  duracion: "2h 20min"
},
{
  id: 64,
  titulo: "Taylor Swift: Miss Americana",
  anio: 2020,
  genero: "Música / Inspiración",
  categoria: "Documentales",
  imagen: "https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABWPzJQNgdL4goIDJ5BmEOBaFIF0uNEvuw_Tsv0s2Ro22uXIZ6K0OWjnzOa0HROsVXT7hyQbJwB9uBLhOGvfq7ZLlJER7ukzoVLOqS9nNNk69rurLUqcL_RHHDwQh1r0OWWUyGg.jpg?r=837",
  rangoEdad: "+13",
  autor: "Lana Wilson (Directora)",
  reseña: "Sincero y revelador. ‘Miss Americana’ muestra a Taylor Swift en su faceta más humana: vulnerable, decidida y en constante evolución.",
  descripcion: "Taylor Swift abre las puertas de su vida privada y profesional en este documental íntimo que recorre su carrera desde los inicios hasta su transformación en una voz política y feminista. A través de momentos personales, grabaciones de estudio y reflexiones honestas, la cantante revela las presiones de la industria musical y su lucha por el control artístico. Es un retrato del crecimiento personal y del poder de usar la fama para generar cambio.",
  recomendacion: "Una mirada inspiradora al camino de una de las artistas más influyentes del siglo XXI.",
  detalles: "Producción original de Netflix. Estrenada en el Festival de Sundance. Dirigida por Lana Wilson (‘After Tiller’).",
  duracion: "1h 25min"
},
{
  id: 65,
  titulo: "Planet Earth II",
  anio: 2016,
  genero: "Naturaleza / Mundo",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMzY4NDBkMWYtYzdkYy00YzBjLWJmODctMWM4YjYzZTdjNWE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "Apta para todos",
  autor: "David Attenborough (Narrador)",
  reseña: "Una experiencia visual sin precedentes. Cada episodio es una oda a la vida en la Tierra, con imágenes que redefinen la televisión documental.",
  descripcion: "‘Planet Earth II’ nos transporta a los ecosistemas más extremos del planeta: montañas, junglas, islas, desiertos, praderas y ciudades. A través de secuencias 4K filmadas con tecnología de vanguardia, el documental capta momentos únicos de comportamiento animal y supervivencia. Narrado con la inconfundible voz de David Attenborough, esta serie celebra la belleza salvaje del planeta y plantea la urgencia de protegerlo frente a la expansión humana.",
  recomendacion: "La cúspide del documental de naturaleza. Imprescindible para cualquier amante de la Tierra.",
  detalles: "Secuela del icónico ‘Planet Earth’ (2006). Producido por BBC Earth. Ganador de múltiples premios Emmy y BAFTA.",
  duracion: "Serie, 6 episodios"
},
{
  id: 66,
  titulo: "Inside Job",
  anio: 2010,
  genero: "Economía / Política",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMTQ3MjkyODA2Nl5BMl5BanBnXkFtZTcwNzQxMTU4Mw@@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+16",
  autor: "Charles Ferguson (Director)",
  reseña: "Riguroso y demoledor. ‘Inside Job’ expone con claridad y evidencia cómo la avaricia y la corrupción causaron la crisis financiera de 2008.",
  descripcion: "Narrado por Matt Damon, este documental explica las causas y consecuencias del colapso económico global de 2008. A través de entrevistas con economistas, políticos y banqueros, revela cómo el sistema financiero fue manipulado por intereses privados y desregulaciones. Con un ritmo ágil y una investigación impecable, ‘Inside Job’ deja en evidencia la fragilidad del sistema capitalista moderno.",
  recomendacion: "Una lección imprescindible de economía, poder y ética.",
  detalles: "Ganador del Oscar a Mejor Documental en 2011. Aclamado por críticos y universidades como recurso educativo sobre finanzas globales.",
  duracion: "1h 48min"
},
{
  id: 67,
  titulo: "The Great Hack",
  anio: 2019,
  genero: "Tecnología / Privacidad",
  categoria: "Documentales",
  imagen: "https://i.pinimg.com/736x/a1/b1/16/a1b11662800226e2a0a66c14e881938a.jpg",
  rangoEdad: "+13",
  autor: "Jehane Noujaim y Karim Amer (Directores)",
  reseña: "Un thriller digital tan real como aterrador. Revela cómo los datos personales se convirtieron en el recurso más valioso —y peligroso— del siglo XXI.",
  descripcion: "‘The Great Hack’ investiga el escándalo de Cambridge Analytica, la empresa que utilizó millones de datos de usuarios de Facebook para manipular elecciones en Estados Unidos y Reino Unido. Con entrevistas a periodistas, analistas y denunciantes, el documental muestra cómo la información personal se transformó en un arma política. Es una advertencia sobre la vulnerabilidad digital en un mundo hiperconectado.",
  recomendacion: "Obligatorio para comprender el poder de los datos y su influencia en la democracia moderna.",
  detalles: "Producido por Netflix. Nominado al BAFTA y al Emmy. Dirigido por los creadores de ‘The Square’.",
  duracion: "1h 54min"
},
{
  id: 68,
  titulo: "Wild Wild Country",
  anio: 2018,
  genero: "Religión / Misterio",
  categoria: "Documentales",
  imagen: "https://resizing.flixster.com/o5mRFFcnl03Y9JYTxo-Tlqza71Q=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p15076916_b_v10_ac.jpg",
  rangoEdad: "+16",
  autor: "Chapman Way y Maclain Way (Directores)",
  reseña: "Un relato fascinante sobre poder, fe y manipulación. La historia real de una secta que desafió al gobierno estadounidense en los años 80.",
  descripcion: "La serie cuenta el ascenso y caída de la comunidad Rajneeshpuram, liderada por el gurú Bhagwan Shree Rajneesh (Osho), en Oregón. Lo que comenzó como un experimento espiritual se transformó en un conflicto político y criminal. Con testimonios de seguidores, exmiembros y habitantes del pueblo, ‘Wild Wild Country’ mezcla drama, intriga y reflexión sobre los límites de la libertad religiosa.",
  recomendacion: "Una historia tan increíble que parece ficción. Perfecta para quienes disfrutan de misterios reales y dilemas éticos.",
  detalles: "Miniserie documental de 6 episodios producida por Netflix. Ganadora del Emmy al Mejor Montaje Documental.",
  duracion: "6 episodios"
},
{
  id: 69,
  titulo: "Fire in Paradise",
  anio: 2019,
  genero: "Desastre / Testimonio",
  categoria: "Documentales",
  imagen: "https://lumiere-a.akamaihd.net/v1/images/rebuildingparadise-vertical_a2021408.jpeg",
  rangoEdad: "+13",
  autor: "Zachary Canepari y Drea Cooper (Directores)",
  reseña: "Impactante y desgarrador. Narra minuto a minuto el incendio más mortal en la historia de California.",
  descripcion: "El 8 de noviembre de 2018, un fuego devastador arrasó la ciudad de Paradise, dejando más de 80 víctimas fatales y miles de desaparecidos. Este documental combina grabaciones reales, llamadas de emergencia y testimonios de sobrevivientes para reconstruir el horror de aquel día. Más allá del desastre natural, la película plantea preguntas sobre el cambio climático y la preparación humana ante la tragedia.",
  recomendacion: "Un recordatorio estremecedor del poder de la naturaleza y la resiliencia humana.",
  detalles: "Producido por Netflix. Ganador del Emmy al Mejor Cortometraje Documental en 2020.",
  duracion: "40min"
},
{
  id: 70,
  titulo: "The Farthest: Voyager in Space",
  anio: 2017,
  genero: "Ciencia / Espacio",
  categoria: "Documentales",
  imagen: "https://upload.wikimedia.org/wikipedia/en/7/71/The_farthest_-_poster.jpg",
  rangoEdad: "Apta para todos",
  autor: "Emer Reynolds (Directora)",
  reseña: "Inspirador y profundamente humano. ‘The Farthest’ celebra una de las mayores hazañas de la humanidad: el viaje de las sondas Voyager hacia lo desconocido.",
  descripcion: "Este documental narra la increíble historia de las sondas Voyager 1 y 2, lanzadas en 1977 para explorar los confines del sistema solar. Con entrevistas a los científicos y técnicos originales de la NASA, ‘The Farthest’ combina emoción, nostalgia y asombro científico. Más que una historia de exploración espacial, es un homenaje a la curiosidad humana, a la cooperación internacional y al deseo de comprender nuestro lugar en el cosmos.",
  recomendacion: "Ideal para quienes aman la ciencia, el espacio y los documentales que inspiran a soñar más allá de las estrellas.",
  detalles: "Producción de la PBS y la NASA. Ganadora del Premio Emmy al Mejor Documental Científico. Incluye imágenes restauradas de las misiones Voyager y el icónico 'Golden Record'.",
  duracion: "2h 1min"
},
  // ===============================
  // 🎎 ASIÁTICAS (COREANAS / ANIMES)
  // ===============================
  {
    id: 71,
    titulo: "Parasite",
    anio: 2019,
    genero: "Thriller / Drama",
    categoria: "Asiáticas",
    imagen: "https://img.rtve.es/imagenes/caratula-parasito-saga-completa/1466077733963.jpg",
    rangoEdad: "+16",
    autor: "Bong Joon-ho (Director)",
    reseña: "Una obra maestra de la sátira social, con giros inesperados y una ejecución brillante.",
    descripcion: "Una familia pobre se infiltra, uno por uno, en el hogar de una familia rica con consecuencias catastróficas.",
    recomendacion: "Cine moderno esencial. Una crítica social inteligente con humor negro.",
    detalles: "Ganadora de la Palma de Oro y 4 Premios de la Academia, incluyendo Mejor Película.",
    duracion: "2h 12min",
  },
  {
    id: 72,
    titulo: "Train to Busan",
    anio: 2016,
    genero: "Terror / Acción",
    categoria: "Asiáticas",
    imagen: "https://images.justwatch.com/poster/9373937/s718/train-to-busan.jpg",
    rangoEdad: "+18",
    autor: "Yeon Sang-ho (Director)",
    reseña: "Una de las mejores películas de zombis de la década, intensa, emocionante y con un ritmo implacable.",
    descripcion: "Un padre y su hija quedan atrapados en un tren de alta velocidad mientras un apocalipsis zombi estalla en Corea.",
    recomendacion: "Acción trepidante. Ideal para fans del terror y el suspenso coreano.",
    detalles: "Un gran éxito internacional del cine surcoreano.",
    duracion: "1h 58min",
  },
  {
    id: 73,
    titulo: "My Name",
    anio: 2021,
    genero: "Acción / Drama",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BN2ZiZWU3MzMtNGM5OC00ZWVkLTkxNjUtMTYwZGU4MzgxYzk0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Kim Jin-min (Director)",
    reseña: "Un drama de venganza oscuro con escenas de acción brutales y una gran actuación de su protagonista.",
    descripcion: "Una joven se une a un cartel de drogas para descubrir la verdad detrás del asesinato de su padre.",
    recomendacion: "Si disfrutas de *K-dramas* de acción y venganza con personajes femeninos fuertes.",
    detalles: "Serie de 8 episodios. Un éxito de Netflix.",
    duracion: "Serie, 8 episodios",
  },
  {
    id: 74,
    titulo: "The Glory",
    anio: 2023,
    genero: "Drama / Venganza",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHJdOzvTpI48s0esFNBVeVw849nLqtQavaZA&s",
    rangoEdad: "+16",
    autor: "An Gil-ho (Director)",
    reseña: "Un drama de venganza meticuloso y bien escrito que aborda el acoso escolar y la justicia.",
    descripcion: "Años después de ser víctima de *bullying*, una mujer ejecuta un elaborado plan de venganza contra sus acosadores.",
    recomendacion: "Uno de los *K-dramas* más aclamados y populares sobre justicia personal.",
    detalles: "Serie de 16 episodios dividida en dos partes. Protagonizada por Song Hye-kyo.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 75,
    titulo: "Extraordinary You",
    anio: 2019,
    genero: "Romance / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ2jC7TEk0s7u4RJKInfbfI_LlXTblbEdchNlmpTKBEsYHZtApNLSO-KSbzPwRpu0W7iw&usqp=CAU",
    rangoEdad: "+13",
    autor: "Kim Sang-hyeop (Director)",
    reseña: "Un *K-drama* único que juega con el concepto de la realidad dentro de un cómic.",
    descripcion: "Una estudiante descubre que es un personaje secundario en un *manhwa* y decide cambiar su destino.",
    recomendacion: "Fantasía juvenil con una premisa original y mucho romance *meta-ficcional*.",
    detalles: "Basada en un *webtoon*. Mezcla comedia, romance y fantasía.",
    duracion: "Serie, 32 episodios cortos",
  },
  {
    id: 76,
    titulo: "Start-Up",
    anio: 2020,
    genero: "Drama / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BYTJiYmE0ZGItMmU1NS00NThhLWIzODEtZmJlYjBmMzcwNmY3XkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Oh Choong-hwan (Director)",
    reseña: "Una serie inspiradora sobre jóvenes ambiciosos que buscan triunfar en el competitivo mundo de las *start-ups* tecnológicas.",
    descripcion: "Un grupo de jóvenes compite por el éxito en un distrito de Corea, enfrentando dilemas de negocios y amor.",
    recomendacion: "Ideal si te gustan las historias de emprendimiento con un triángulo amoroso central.",
    detalles: "Con Suzy y Nam Joo-hyuk. Se centra en la tecnología y la innovación.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 77,
    titulo: "Alchemy of Souls",
    anio: 2022,
    genero: "Fantasía / Aventura",
    categoria: "Asiáticas",
    imagen: "https://www.monash.edu/__data/assets/image/0006/3069096/Alchemy-of-Souls-official-poster.jpg",
    rangoEdad: "+16",
    autor: "Park Joon-hwa (Director)",
    reseña: "Una fantasía épica y compleja con hermosos escenarios, magia, acción y romance.",
    descripcion: "Una hechicera se encuentra atrapada en el cuerpo de una guerrera ciega y se convierte en sirvienta de un noble.",
    recomendacion: "Si amas la fantasía coreana con gran desarrollo de personajes y mitología.",
    detalles: "Dividida en dos partes, con un total de 30 episodios. Gran éxito de TVN.",
    duracion: "Serie, 30 episodios",
  },
  {
    id: 78,
    titulo: "Twenty-Five Twenty-One",
    anio: 2022,
    genero: "Drama / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BNDU3ODZjMzAtYTIyZi00MGExLWFhYjEtOGQ5YjVlMjU3MjNlXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Jung Ji-hyun (Director)",
    reseña: "Un drama *slice of life* conmovedor y nostálgico sobre el primer amor, los sueños y la madurez.",
    descripcion: "La historia de dos jóvenes cuyas vidas se entrelazan en 1998, durante la crisis financiera asiática.",
    recomendacion: "Un drama romántico y profundo, con una estética visual muy cuidada.",
    detalles: "Protagonizada por Kim Tae-ri y Nam Joo-hyuk.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 79,
    titulo: "Squid Game",
    anio: 2021,
    genero: "Acción / Suspenso",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BMDcxYjg1OTctYmUxZi00ZjhjLWIwNTMtNmI2M2Y4OTU1YWU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Hwang Dong-hyuk (Director)",
    reseña: "El fenómeno mundial de Netflix. Tensión extrema, crítica social y un concepto brutal.",
    descripcion: "Cientos de personas con problemas de dinero aceptan participar en juegos infantiles mortales por una gran suma de dinero.",
    recomendacion: "Un *thriller* de supervivencia imprescindible. Intenso y con mucha crítica al capitalismo.",
    detalles: "Se convirtió en la serie más vista de la historia de Netflix en su lanzamiento.",
    duracion: "Serie, 9 episodios",
  },
  {
    id: 80,
    titulo: "All of Us Are Dead",
    anio: 2022,
    genero: "Terror / Escolar",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZxay4or86F0zxdpPsmrbpXXutgSKklnYtrb9E15oPc0tzOcro4u7PDYG0idNv80StwCI&usqp=CAU",
    rangoEdad: "+18",
    autor: "Lee Jae-gyoo (Director)",
    reseña: "Un *K-drama* de zombis ultra violento y con mucha adrenalina, centrado en el drama adolescente.",
    descripcion: "Un grupo de estudiantes queda atrapado en su instituto durante el inicio de un apocalipsis zombi.",
    recomendacion: "Para fans del género zombi con mucha acción y tensión de supervivencia.",
    detalles: "Basada en el *webtoon* 'Now at Our School'.",
    duracion: "Serie, 12 episodios",
  },
  {
    id: 81,
    titulo: "Your Name",
    anio: 2016,
    genero: "Anime / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BMTIyNzFjNzItZmQ1MC00NzhjLThmMzYtZjRhN2Y3MmM2OGQyXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Makoto Shinkai (Director)",
    reseña: "Una obra maestra visual que combina romance, fantasía y un giro narrativo sorprendente.",
    descripcion: "Un chico de Tokio y una chica de un pueblo rural comienzan a intercambiar cuerpos misteriosamente.",
    recomendacion: "Imprescindible para los fans del anime. Una película visualmente deslumbrante.",
    detalles: "Uno de los animes más taquilleros de la historia.",
    duracion: "1h 47min",
  },
  {
    id: 82,
    titulo: "A Silent Voice (Koe no Katachi)",
    anio: 2016,
    genero: "Anime / Drama",
    categoria: "Asiáticas",
    imagen: "https://upload.wikimedia.org/wikipedia/en/3/32/A_Silent_Voice_Film_Poster.jpg",
    rangoEdad: "+13",
    autor: "Naoko Yamada (Directora)",
    reseña: "Una historia conmovedora sobre el perdón, la redención y la empatía. Un retrato sensible del acoso escolar y la búsqueda de segundas oportunidades.",
    descripcion: "Shoya Ishida, un joven que en su infancia acosó a una compañera sorda llamada Shoko Nishimiya, vive atormentado por la culpa de sus acciones. Años después, decide buscarla para disculparse y reparar el daño que causó. Lo que sigue es un viaje emocional sobre la amistad, el arrepentimiento y la posibilidad de sanar. Con una animación delicada y una banda sonora emotiva, *A Silent Voice* explora la soledad y la comunicación humana desde una perspectiva profundamente humana.",
    recomendacion: "Recomendada para quienes buscan un anime con un mensaje poderoso y emocional. Ideal para reflexionar sobre la empatía y el valor del perdón.",
    detalles: "Basada en el manga de Yoshitoki Ōima. Producida por Kyoto Animation. Nominada a Mejor Película de Animación en los Japan Academy Prize.",
    duracion: "2h 10min"
  },
  {
    id: 83,
    titulo: "Spirited Away",
    anio: 2001,
    genero: "Anime / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BM2E2YzcwMTQtNWRlMC00ZGZlLWJhZTEtMDU4ZGIzMWI0NzJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+7",
    autor: "Hayao Miyazaki (Director)",
    reseña: "Una joya de Studio Ghibli. Pura fantasía onírica con una animación magistral y una rica mitología.",
    descripcion: "Una niña se adentra en un mundo espiritual para rescatar a sus padres convertidos en cerdos.",
    recomendacion: "Un clásico del anime y una de las películas de fantasía más importantes de la historia.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación (única película de anime en lograrlo).",
    duracion: "2h 5min",
  },
  {
    id: 84,
    titulo: "Demon Slayer: Mugen Train",
    anio: 2020,
    genero: "Anime / Acción",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BNzEzYjhkYTctMWNmZS00MTc5LWI4OWUtZjFkNzNkYTNkMTJlXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+16",
    autor: "Haruo Sotozaki (Director)",
    reseña: "Una continuación directa del anime, con batallas impresionantes y un gran impacto emocional.",
    descripcion: "Tanjiro y sus compañeros se unen a un poderoso cazador de demonios para investigar misterios en un tren.",
    recomendacion: "Acción visualmente espectacular. Si te gusta el anime, es imperdible.",
    detalles: "Rompió récords de taquilla en Japón y a nivel mundial para una película de anime.",
    duracion: "1h 57min",
  },
  {
    id: 85,
    titulo: "Attack on Titan",
    anio: 2013,
    genero: "Anime / Épico",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BZjliODY5MzQtMmViZC00MTZmLWFhMWMtMjMwM2I3OGY1MTRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Tetsurō Araki (Director)",
    reseña: "Una serie anime brutalmente intensa, con un mundo post-apocalíptico fascinante y mucha acción.",
    descripcion: "La humanidad lucha por sobrevivir dentro de murallas contra gigantes devoradores de personas.",
    recomendacion: "Si buscas una serie con acción, misterio y un gran desarrollo de personajes.",
    detalles: "Basada en el manga de Hajime Isayama. Famosa por sus giros argumentales.",
    duracion: "Serie, 4 temporadas",
  },
  {
  id: 86,
  titulo: "El niño y la garza (The Boy and the Heron)",
  anio: 2023,
  genero: "Anime / Fantasía / Drama",
  categoria: "Asiáticas",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwMhofHqKGhDKdfyTmV1HSx380uLbpTiGMlQ&s",
  rangoEdad: "Apta para todo público",
  autor: "Hayao Miyazaki (Director)",
  reseña: "Una obra maestra visual y poética del Studio Ghibli. Un viaje introspectivo sobre la pérdida, la esperanza y el renacer, envuelto en una atmósfera de ensueño.",
  descripcion: "Tras la muerte de su madre, Mahito, un niño solitario, se muda al campo con su padre y su nueva madrastra. Allí conoce a una garza parlante que lo guía hacia un mundo misterioso, lleno de criaturas fantásticas, donde los límites entre la vida y la muerte se desdibujan. A través de esta aventura simbólica, Mahito enfrenta su dolor y busca entender el ciclo de la existencia. ‘El niño y la garza’ es una carta de despedida y esperanza de Miyazaki, repleta de belleza visual y profundidad emocional.",
  recomendacion: "Perfecta para los fans de Studio Ghibli o del anime contemplativo y filosófico. Una película para ver más de una vez y descubrir nuevos significados.",
  detalles: "Ganadora del Oscar 2024 a Mejor Película de Animación. Producida por Studio Ghibli y musicalizada por Joe Hisaishi. Considerada el regreso triunfal de Hayao Miyazaki tras una década de ausencia.",
  duracion: "2h 4min"
},
  {
  id: 87,
  titulo: "Suzume",
  anio: 2023,
  genero: "Anime / Fantasía / Aventura / Drama",
  categoria: "Asiáticas",
  imagen: "https://es.web.img3.acsta.net/pictures/23/03/31/12/29/1925541.jpg",
  rangoEdad: "+13",
  autor: "Makoto Shinkai (Director)",
  reseña: "Una aventura mágica y emotiva sobre una joven que debe cerrar puertas misteriosas que desatan desastres naturales. Bellísima animación, paisajes impresionantes y una historia sobre el duelo y la esperanza.",
  descripcion: "Suzume, una adolescente japonesa, conoce a un joven que busca extrañas puertas en ruinas. Al abrir una de ellas, desata una fuerza sobrenatural que amenaza con destruir el país. Juntos emprenden un viaje por todo Japón para sellar esas puertas y restaurar el equilibrio entre el mundo de los vivos y el de los espíritus. En el camino, Suzume también enfrentará su propio pasado y aprenderá a sanar sus heridas. Con una mezcla de fantasía, aventura y emoción, ‘Suzume’ es una obra visualmente impactante y profundamente humana.",
  recomendacion: "Si te gustaron *Your Name* o *Weathering With You*, esta película te encantará. Es un viaje espiritual y visual con un mensaje de esperanza.",
  detalles: "Dirigida por Makoto Shinkai, creador de *Your Name*. Nominada al Oscar 2024 a Mejor Película de Animación. La banda sonora corre a cargo de Radwimps y Kazuma Jinnouchi.",
  duracion: "2h 1min"
},
  {
    id: 88,
    titulo: "Jujutsu Kaisen 0",
    anio: 2021,
    genero: "Anime / Sobrenatural",
    categoria: "Asiáticas",
    imagen: "https://es.web.img3.acsta.net/pictures/22/05/18/16/23/5993750.jpg",
    rangoEdad: "+16",
    autor: "Sunghoo Park (Director)",
    reseña: "Una precuela intensa y oscura que expande el universo de Jujutsu Kaisen con acción increíble.",
    descripcion: "Un joven atormentado por el espíritu de su amiga de la infancia se une a la Escuela de Hechicería Jujutsu.",
    recomendacion: "Acción oscura y sobrenatural. Excelente animación y desarrollo de personajes.",
    detalles: "Basada en el manga precuela del éxito de Gege Akutami.",
    duracion: "1h 45min",
  },
  {
    id: 89,
    titulo: "Belle",
    anio: 2021,
    genero: "Anime / Musical",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdl4BP4Nyl9D9QUlzcg6sKotOpwy93-KXApg&s",
    rangoEdad: "+13",
    autor: "Mamoru Hosoda (Director)",
    reseña: "Una reinterpretación de 'La Bella y la Bestia' en la era digital, con un diseño de personaje espectacular.",
    descripcion: "Una adolescente tímida se convierte en una superestrella musical en un mundo virtual masivo.",
    recomendacion: "Visualmente impresionante y con una banda sonora moderna y emotiva.",
    detalles: "Dirigida por el aclamado Mamoru Hosoda ('Mirai', 'Summer Wars').",
    duracion: "2h 1min",
  },
  {
    id: 91,
    titulo: "Demon Slayer – The Movie: Infinity Castle",
    anio: 2025,
    genero: "Anime / Acción / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuXqw5AJVusysElA39ukMOixTihN1nO-h6Uod9NMMTxj6LZvSOIlN-PMN_KV1Vgy-UM7A&usqp=CAU",
    rangoEdad: "+16",
    autor: "Koyoharu Gotōge (Manga)",
    reseña: "La esperada conclusión de la saga de Demon Slayer en formato cinematográfico. Será un evento épico.",
    descripcion: "Los Cazadores de Demonios se enfrentan a Muzan Kibutsuji y sus Lunas Superiores en el Castillo Infinito.",
    recomendacion: "La batalla final de la serie. Máxima expectación para los fans.",
    detalles: "Adaptación del arco final del manga. Dividida en varias partes.",
    duracion: "Tiempo estimado: 2h 20min (Parte 1)",
  },
];

export default peliculas;