const peliculas = [
  // ===============================
  // 📚 BASADAS EN LIBROS
  // ===============================
  {
    id: 1,
    titulo: "Harry Potter y la Piedra Filosofal",
    anio: 2001,
    genero: "Fantasía / Aventura",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BYTkyYjVkNDItODc1Ny00NzA1LTkwY2YtZDUwNTlhMDk3MTZiXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+7",
    autor: "J.K. Rowling (Libro)",
    reseña: "Una adaptación mágica que captura la esencia de la amistad y la lucha contra el mal, perfecta para iniciar una saga épica.",
    descripcion: "Harry Potter descubre que es un mago y comienza su aventura en la Escuela de Magia y Hechicería de Hogwarts.",
    recomendacion: "Imprescindible para los fans de la magia y la fantasía. Gran inicio de saga.",
    detalles: "Basada en el libro 'Harry Potter y la Piedra Filosofal'. Dirigida por Chris Columbus.",
    duracion: "2h 32min",
  },
  {
    id: 2,
    titulo: "Orgullo y Prejuicio",
    anio: 2005,
    genero: "Romance / Drama",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BZjBlODgwZWEtODcxMi00OTY5LWEyOTItODE2MDBjZjU0ZDU3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+12",
    autor: "Jane Austen (Libro)",
    reseña: "Una hermosa adaptación visualmente impactante que honra el clásico literario de Jane Austen.",
    descripcion: "La historia de cinco hermanas en la Inglaterra rural del siglo XIX y las presiones sociales para casarse.",
    recomendacion: "Ideal para amantes del drama de época y el romance con diálogos brillantes.",
    detalles: "Protagonizada por Keira Knightley. Captura la atmósfera y el ingenio de la novela.",
    duracion: "2h 9min",
  },
  {
    id: 3,
    titulo: "El señor de los anillos",
    anio: 2001,
    genero: "Fantasía / Épico",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/71y-2u8rV9L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "J.R.R. Tolkien (Libro)",
    reseña: "Una obra maestra del cine de fantasía, con un mundo inmersivo y personajes inolvidables.",
    descripcion: "Un hobbit debe emprender una épica búsqueda para destruir un anillo mágico y salvar la Tierra Media.",
    recomendacion: "La mejor adaptación de fantasía jamás hecha. Ver la versión extendida es un ritual.",
    detalles: "Parte 1: La Comunidad del Anillo. Dirigida por Peter Jackson.",
    duracion: "2h 58min",
  },
  {
    id: 4,
    titulo: "Crepúsculo",
    anio: 2008,
    genero: "Romance / Fantasía",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/61aW0M0nQ-L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+14",
    autor: "Stephenie Meyer (Libro)",
    reseña: "Un fenómeno cultural que definió el romance sobrenatural adolescente de su generación.",
    descripcion: "Una adolescente se enamora de un misterioso compañero de clase que resulta ser un vampiro.",
    recomendacion: "Para fans de las historias de amor prohibido y la fantasía juvenil.",
    detalles: "Basada en la novela homónima, la película lanzó a la fama a sus protagonistas.",
    duracion: "2h 2min",
  },
  {
    id: 5,
    titulo: "Yo antes de ti",
    anio: 2016,
    genero: "Romance / Drama",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/71bEomzP5JL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Jojo Moyes (Libro)",
    reseña: "Una película emotiva que explora el amor, la vida y las decisiones difíciles. Prepárate para llorar.",
    descripcion: "Una joven es contratada para cuidar a un joven y rico banquero que quedó paralizado tras un accidente.",
    recomendacion: "Un drama romántico con un mensaje profundo sobre la calidad de vida.",
    detalles: "Protagonizada por Emilia Clarke y Sam Claflin. Un éxito de taquilla y crítica.",
    duracion: "1h 50min",
  },
  {
    id: 6,
    titulo: "El padrino",
    anio: 1972,
    genero: "Crimen / Drama",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/91B3xDfzJLL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+18",
    autor: "Mario Puzo (Libro)",
    reseña: "Considerada una de las mejores películas de la historia. Un estudio magistral sobre la familia, el poder y la corrupción.",
    descripcion: "Crónica de la vida de la familia mafiosa Corleone en Nueva York tras la Segunda Guerra Mundial.",
    recomendacion: "Cine clásico obligatorio. Una lección de dirección y actuación.",
    detalles: "Dirigida por Francis Ford Coppola. Ganadora de 3 Oscars. Clave del género de gángsters.",
    duracion: "2h 55min",
  },
  {
    id: 7,
    titulo: "El resplandor",
    anio: 1980,
    genero: "Terror / Psicológico",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/71bttjKzbkL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+18",
    autor: "Stephen King (Libro)",
    reseña: "Una obra cumbre del terror psicológico, con una atmósfera opresiva y una actuación icónica de Jack Nicholson.",
    descripcion: "Un escritor acepta un trabajo como cuidador de invierno en un hotel aislado, donde comienza a enloquecer.",
    recomendacion: "Si buscas un terror lento, atmosférico y que te haga pensar, esta es tu película.",
    detalles: "Dirigida por Stanley Kubrick. Un clásico de culto que difiere del libro en varios aspectos.",
    duracion: "1h 59min",
  },
  {
    id: 8,
    titulo: "Mujercitas",
    anio: 2019,
    genero: "Drama / Histórico",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/71zsu7A5JpL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+7",
    autor: "Louisa May Alcott (Libro)",
    reseña: "Una vibrante y moderna reimaginación de una historia atemporal sobre las aspiraciones de cuatro hermanas.",
    descripcion: "Retrato de las vidas de las hermanas March mientras exploran el paso a la edad adulta y sus sueños individuales.",
    recomendacion: "Una película visualmente hermosa y con actuaciones sobresalientes.",
    detalles: "Dirigida por Greta Gerwig. Nominada a múltiples Oscars.",
    duracion: "2h 15min",
  },
  {
    id: 9,
    titulo: "It",
    anio: 2017,
    genero: "Terror",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/71ZbDqu5qVL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Stephen King (Libro)",
    reseña: "Una de las mejores adaptaciones recientes de King, centrada en la amistad y el terror puro.",
    descripcion: "Siete niños se enfrentan a un payaso maligno que acecha la pequeña ciudad de Derry.",
    recomendacion: "Excelente mezcla de terror y una conmovedora historia de 'coming of age'.",
    detalles: "Basada en la novela de 1986. Primera parte de dos.",
    duracion: "2h 15min",
  },
  {
    id: 10,
    titulo: "Psicosis",
    anio: 1960,
    genero: "Suspenso / Terror",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81I-6fw9b5L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Robert Bloch (Libro)",
    reseña: "El thriller por excelencia que sentó las bases para el género de terror moderno. Inolvidable e innovadora.",
    descripcion: "Una secretaria fugitiva se aloja en un motel regentado por un joven tímido con una madre dominante.",
    recomendacion: "Un clásico de Alfred Hitchcock. Su giro final es historia del cine.",
    detalles: "Dirigida por Alfred Hitchcock. La famosa escena de la ducha es legendaria.",
    duracion: "1h 49min",
  },
  {
    id: 11,
    titulo: "Los juegos del hambre",
    anio: 2012,
    genero: "Ciencia Ficción / Acción",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81H4cWfUtxL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Suzanne Collins (Libro)",
    reseña: "Una sólida adaptación que ofrece acción, crítica social y un fuerte personaje femenino principal.",
    descripcion: "En un futuro distópico, dos jóvenes de cada distrito son elegidos para luchar a muerte en un evento televisado.",
    recomendacion: "Buena para introducirse en el género distópico y de acción juvenil.",
    detalles: "Protagonizada por Jennifer Lawrence. Basada en el primer libro de la trilogía.",
    duracion: "2h 22min",
  },
  {
    id: 12,
    titulo: "El código Da Vinci",
    anio: 2006,
    genero: "Misterio / Suspenso",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81pT8J9mQBL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Dan Brown (Libro)",
    reseña: "Un thriller trepidante lleno de enigmas históricos, perfecto para los amantes de las conspiraciones.",
    descripcion: "Un simbologista debe descifrar un misterio que se esconde tras la obra de Leonardo da Vinci.",
    recomendacion: "Ideal si disfrutas de películas que combinan historia, arte y suspenso.",
    detalles: "Dirigida por Ron Howard y protagonizada por Tom Hanks.",
    duracion: "2h 29min",
  },
  {
    id: 13,
    titulo: "Las ventajas de ser invisible",
    anio: 2012,
    genero: "Drama / Adolescente",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81xvC2Aeo1L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+14",
    autor: "Stephen Chbosky (Libro y Director)",
    reseña: "Una película honesta y emotiva sobre la salud mental, la amistad y encontrar tu lugar en el mundo.",
    descripcion: "Un adolescente socialmente incómodo entra a la escuela secundaria y es acogido por dos estudiantes carismáticos.",
    recomendacion: "Un drama conmovedor y muy bien valorado por su retrato de la adolescencia.",
    detalles: "El autor del libro también dirigió la película. Protagonizada por Logan Lerman, Emma Watson.",
    duracion: "1h 43min",
  },
  {
    id: 14,
    titulo: "El niño con el pijama de rayas",
    anio: 2008,
    genero: "Drama / Guerra",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81I9wFv19JL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "John Boyne (Libro)",
    reseña: "Un relato desgarrador y necesario sobre el Holocausto, visto a través de la inocencia de dos niños.",
    descripcion: "Un niño alemán se muda con su familia y se hace amigo de un niño judío al otro lado de la cerca de un campo de concentración.",
    recomendacion: "Un drama intenso que te dejará reflexionando. Preparar pañuelos.",
    detalles: "Basada en la novela de 2006. Ambientada durante la Segunda Guerra Mundial.",
    duracion: "1h 34min",
  },
  {
    id: 15,
    titulo: "La milla verde",
    anio: 1999,
    genero: "Drama / Fantasía",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81VjvF7J3QL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Stephen King (Libro)",
    reseña: "Un drama profundamente emotivo que toca temas de justicia, milagros y la naturaleza humana.",
    descripcion: "Un guardia de prisión en el corredor de la muerte narra su experiencia con un recluso de gran tamaño y poderes sobrenaturales.",
    recomendacion: "Una película que todo amante del drama debe ver. Tan conmovedora como 'Cadena Perpetua'.",
    detalles: "Protagonizada por Tom Hanks. Dirigida por Frank Darabont.",
    duracion: "3h 9min",
  },
  {
    id: 16,
    titulo: "Forrest Gump",
    anio: 1994,
    genero: "Drama / Comedia",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81xTxW7YQdL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Winston Groom (Libro)",
    reseña: "Una joya del cine que mezcla comedia, drama y la historia moderna de EE. UU. a través de un personaje único.",
    descripcion: "Un hombre bondadoso con un coeficiente intelectual bajo relata su vida extraordinaria y sus encuentros con figuras históricas.",
    recomendacion: "Una de las películas más queridas de la historia. Ineludible.",
    detalles: "Ganadora de 6 Premios de la Academia, incluyendo Mejor Película y Mejor Actor (Tom Hanks).",
    duracion: "2h 22min",
  },
  {
    id: 17,
    titulo: "Narnia",
    anio: 2005,
    genero: "Fantasía / Aventura",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81M-HjM3woL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+7",
    autor: "C.S. Lewis (Libro)",
    reseña: "Una aventura clásica de fantasía con efectos especiales impresionantes y una historia atemporal.",
    descripcion: "Cuatro hermanos son evacuados a una casa de campo y descubren un mundo mágico a través de un armario.",
    recomendacion: "Perfecta para ver en familia. Si te gustó Harry Potter, te gustará Narnia.",
    detalles: "Basada en el libro 'El León, la Bruja y el Armario'.",
    duracion: "2h 23min",
  },
  {
    id: 18,
    titulo: "Dune",
    anio: 2021,
    genero: "Ciencia Ficción / Épico",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81kz8jG0GSL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Frank Herbert (Libro)",
    reseña: "Una adaptación majestuosa y visualmente impresionante que logra capturar la escala y la complejidad de la novela.",
    descripcion: "Un joven debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y su pueblo.",
    recomendacion: "Cine de ciencia ficción de gran presupuesto que debe verse en la pantalla más grande posible.",
    detalles: "Dirigida por Denis Villeneuve. Ganadora de 6 Oscars técnicos.",
    duracion: "2h 35min",
  },
  {
    id: 19,
    titulo: "La chica del tren",
    anio: 2016,
    genero: "Thriller / Drama",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81NoaEoTk2L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Paula Hawkins (Libro)",
    reseña: "Un thriller psicológico tenso con una protagonista compleja y una narrativa poco fiable.",
    descripcion: "Una mujer alcohólica se involucra en un caso de personas desaparecidas tras ver algo perturbador desde el tren.",
    recomendacion: "Si disfrutas de thrillers con misterios y giros inesperados.",
    detalles: "Protagonizada por Emily Blunt. Adaptación del best-seller de 2015.",
    duracion: "1h 52min",
  },
  {
    id: 20,
    titulo: "El gran Gatsby",
    anio: 2013,
    genero: "Drama / Romance",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/I/81XMFwOGbJL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "F. Scott Fitzgerald (Libro)",
    reseña: "Una visión extravagante y moderna de la 'Era del Jazz', con un diseño de producción deslumbrante.",
    descripcion: "Un aspirante a escritor es atraído al mundo del misterioso millonario Jay Gatsby en Long Island.",
    recomendacion: "Visualmente espectacular. Combina drama, romance y una crítica a la riqueza.",
    detalles: "Dirigida por Baz Luhrmann. Protagonizada por Leonardo DiCaprio.",
    duracion: "2h 23min",
  },

  // ===============================
  // 🔥 TOP 10 DE 2025 (PREVISIONES)
  // ===============================
  {
    id: 21,
    titulo: "Cómo entrenar a tu dragón",
    anio: 2025,
    genero: "Animación / Aventura",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/71Z8aMtM-AL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Dean DeBlois (Director Original)",
    reseña: "La versión *live-action* de una de las sagas animadas más queridas, con potencial para ser un éxito de fantasía.",
    descripcion: "La historia de Hipo y su dragón Chimuelo, en su paso a la edad adulta y la defensa de su comunidad. (Live-Action)",
    recomendacion: "Para los que crecieron con la trilogía original. Gran potencial épico.",
    detalles: "Adaptación *live-action* del éxito de Dreamworks. Dirigida por Dean DeBlois.",
    duracion: "Tiempo estimado: 2h 10min",
  },
  {
    id: 22,
    titulo: "Superman",
    anio: 2025,
    genero: "Acción / Superhéroes",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/81j8iY+gl-L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "DC Comics",
    reseña: "El inicio de una nueva era para el Hombre de Acero, prometiendo un enfoque más esperanzador y clásico.",
    descripcion: "Clark Kent equilibra su vida como periodista en Metrópolis con su papel de protector del mundo, Superman.",
    recomendacion: "La película que definirá el futuro del Universo DC. Alta expectación.",
    detalles: "Dirigida por James Gunn. Parte del nuevo DC Universe (DCU).",
    duracion: "Tiempo estimado: 2h 30min",
  },
  {
    id: 23,
    titulo: "La Hora De La Desaparición",
    anio: 2025,
    genero: "Suspenso / Misterio",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/91XFdctdKEL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Guion Original",
    reseña: "Un thriller con una premisa intrigante que promete mantener al espectador al borde del asiento.",
    descripcion: "Un detective debe resolver la misteriosa desaparición masiva de personas en un pueblo aislado.",
    recomendacion: "Para fans de las películas de misterio con giros oscuros.",
    detalles: "Película original con un elenco de alto perfil.",
    duracion: "Tiempo estimado: 1h 55min",
  },
  {
    id: 24,
    titulo: "Caught Stealing",
    anio: 2025,
    genero: "Acción / Crimen",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/81kN+Vr4nXL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+18",
    autor: "Charlie Huston (Libro)",
    reseña: "Una adaptación de novela *noir* con un estilo visual crudo y mucha adrenalina.",
    descripcion: "Un exjugador de béisbol de mala suerte se ve envuelto en un violento conflicto en la ciudad de Nueva York.",
    recomendacion: "Un thriller de crimen para adultos, con tintes de humor negro.",
    detalles: "Dirigida por Darren Aronofsky. Adaptación de la novela de Charlie Huston.",
    duracion: "Tiempo estimado: 2h 05min",
  },
  {
    id: 25,
    titulo: "Thunderbolts",
    anio: 2025,
    genero: "Acción / Marvel",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/91OEGaWqBbL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Marvel Comics",
    reseña: "El equipo de antihéroes de Marvel. Promete acción intensa y dilemas morales complejos.",
    descripcion: "Un grupo de villanos y antihéroes es reunido por el gobierno para misiones secretas de alto riesgo.",
    recomendacion: "Imperdible para los seguidores del Universo Cinematográfico de Marvel.",
    detalles: "Protagonizada por personajes ya conocidos del UCM, como Yelena Belova y Bucky Barnes.",
    duracion: "Tiempo estimado: 2h 15min",
  },
  {
    id: 26,
    titulo: "Los 4 fantásticos: primeros pasos",
    anio: 2025,
    genero: "Superhéroes / Ciencia Ficción",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/81BuVQ5c8zL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Marvel Comics",
    reseña: "El tan esperado debut de la 'Primera Familia' de Marvel en el UCM, con un enfoque fresco y aventurero.",
    descripcion: "Cuatro astronautas obtienen superpoderes después de una misión espacial y deben aprender a usarlos para proteger al mundo.",
    recomendacion: "Gran potencial para ser la película de superhéroes del año.",
    detalles: "Se espera que tenga un tono más enfocado en la ciencia y la aventura espacial.",
    duracion: "Tiempo estimado: 2h 18min",
  },
  {
    id: 27,
    titulo: "Misión: Imposible - Sentencia final",
    anio: 2025,
    genero: "Acción / Espionaje",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/81W4sAxWk4L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Guion Original",
    reseña: "Ethan Hunt vuelve con acrobacias más locas y un espionaje de alto calibre. Puro entretenimiento de acción.",
    descripcion: "El agente Ethan Hunt y su equipo se enfrentan a una amenaza global que pone en peligro a toda la humanidad.",
    recomendacion: "Acción trepidante. Ideal para amantes de los *blockbusters* con efectos prácticos.",
    detalles: "La continuación directa de la primera parte de 'Sentencia Final'. Protagonizada por Tom Cruise.",
    duracion: "Tiempo estimado: 2h 40min",
  },
  {
    id: 28,
    titulo: "Blade",
    anio: 2025,
    genero: "Acción / Terror",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/81bVq-umIzL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Marvel Comics",
    reseña: "El cazavampiros de Marvel regresa con una promesa de terror y acción más adulta en el UCM.",
    descripcion: "Un 'caminante diurno' mitad humano, mitad vampiro, lucha para proteger a la humanidad de las criaturas de la noche.",
    recomendacion: "Si buscas una película de superhéroes con un toque de terror gótico.",
    detalles: "Protagonizada por Mahershala Ali. Se espera que explore el lado oscuro de Marvel.",
    duracion: "Tiempo estimado: 1h 58min",
  },
  {
    id: 29,
    titulo: "Guardianes de la noche",
    anio: 2025,
    genero: "Animación / Fantasía",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/91r2h2eY9DL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Koyoharu Gotōge (Manga)",
    reseña: "El fenómeno del anime continúa con una nueva entrega cinematográfica con una animación espectacular.",
    descripcion: "Tanjiro y sus compañeros cazadores de demonios se enfrentan a un nuevo y poderoso enemigo.",
    recomendacion: "Imprescindible para los fans del anime de acción. Una experiencia visual.",
    detalles: "Basada en el manga 'Kimetsu no Yaiba'. Se espera una adaptación fiel al arco del manga.",
    duracion: "Tiempo estimado: 1h 40min",
  },
  {
    id: 30,
    titulo: "F1",
    anio: 2025,
    genero: "Acción / Deporte",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/I/71j7T+0xXWL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Guion Original",
    reseña: "Una película que promete capturar la velocidad, el drama y la intensidad de la Fórmula 1.",
    descripcion: "Un expiloto de F1 regresa de su retiro para competir junto a un novato contra los mejores del mundo.",
    recomendacion: "Perfecta para los amantes del automovilismo y las películas de superación deportiva.",
    detalles: "Protagonizada por Brad Pitt y dirigida por Joseph Kosinski ('Top Gun: Maverick').",
    duracion: "Tiempo estimado: 2h 12min",
  },

  // ===============================
  // 🎬 KIDS
  // ===============================
  {
    id: 31,
    titulo: "Toy Story",
    anio: 1995,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/71aFt4+OTOL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "John Lasseter (Director)",
    reseña: "Un clásico atemporal de Pixar que celebra la amistad, la lealtad y el poder de la imaginación.",
    descripcion: "Los juguetes de un niño cobran vida y deben enfrentar la llegada de un nuevo juguete que amenaza su orden.",
    recomendacion: "Una película obligatoria para todas las edades. Divertida, emotiva e innovadora.",
    detalles: "La primera película de Pixar realizada completamente por ordenador. Un hito en la animación.",
    duracion: "1h 21min",
  },
  {
    id: 32,
    titulo: "Buscando a Nemo",
    anio: 2003,
    genero: "Animación / Familiar",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81r0ZV4hWmL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Andrew Stanton (Director)",
    reseña: "Una aventura acuática inolvidable que habla sobre la sobreprotección y el valor de soltar.",
    descripcion: "Un pez payaso sobreprotector viaja por el océano para encontrar a su hijo, que ha sido capturado.",
    recomendacion: "Un clásico moderno de Pixar. Visualmente hermoso y con mucho humor.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación.",
    duracion: "1h 40min",
  },
  {
    id: 33,
    titulo: "Shrek",
    anio: 2001,
    genero: "Animación / Comedia",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/71Xl5ZC3l0L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Andrew Adamson y Vicky Jenson (Directores)",
    reseña: "Una parodia inteligente de los cuentos de hadas que se convirtió en un éxito instantáneo.",
    descripcion: "Un ogro cascarrabias es enviado a rescatar a una princesa para recuperar su pantano.",
    recomendacion: "Humor para adultos y niños. Muy recomendable.",
    detalles: "Primera película en ganar el Oscar a Mejor Película de Animación (categoría recién creada).",
    duracion: "1h 30min",
  },
  {
    id: 34,
    titulo: "Frozen",
    anio: 2013,
    genero: "Animación / Musical",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81rbHqVtZPL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Chris Buck y Jennifer Lee (Directores)",
    reseña: "El fenómeno de Disney que redefinió la narrativa de princesas, centrándose en el amor fraternal.",
    descripcion: "Una princesa debe encontrar a su hermana con poderes de hielo para salvar su reino de un invierno eterno.",
    recomendacion: "Sus canciones son un éxito mundial. Imprescindible en Disney.",
    detalles: "Basada vagamente en el cuento de 'La Reina de las Nieves'. Ganó 2 Oscars.",
    duracion: "1h 42min",
  },
  {
    id: 35,
    titulo: "Kung Fu Panda",
    anio: 2008,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81P7rC5R8kL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Mark Osborne y John Stevenson (Directores)",
    reseña: "Divertida y con un gran mensaje de superación, mezclando acción de artes marciales con comedia.",
    descripcion: "Un torpe panda que trabaja en el restaurante de fideos de su padre es elegido inesperadamente como el Guerrero Dragón.",
    recomendacion: "Excelente animación y peleas de artes marciales aptas para niños.",
    detalles: "Producida por Dreamworks Animation.",
    duracion: "1h 30min",
  },
  {
    id: 36,
    titulo: "Los Increíbles",
    anio: 2004,
    genero: "Animación / Superhéroes",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81Xx6D5W6sL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+7",
    autor: "Brad Bird (Director)",
    reseña: "Una película de superhéroes que funciona como una gran historia familiar y un thriller de acción.",
    descripcion: "Una familia de superhéroes intenta llevar una vida normal hasta que se ven obligados a salvar el mundo.",
    recomendacion: "Considerada una de las mejores películas de superhéroes de la historia, animada o no.",
    detalles: "Dirigida por Brad Bird, conocido por su trabajo en 'El gigante de hierro'.",
    duracion: "1h 55min",
  },
  {
    id: 37,
    titulo: "Coco",
    anio: 2017,
    genero: "Animación / Musical",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81C3WhiXQZL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Lee Unkrich (Director)",
    reseña: "Una celebración visual y emocional de la cultura mexicana, la familia y el Día de Muertos.",
    descripcion: "Un joven con sueños de ser músico viaja accidentalmente a la Tierra de los Muertos.",
    recomendacion: "Una de las películas más emotivas de Pixar. Hermosa y culturalmente rica.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación y Mejor Canción Original.",
    duracion: "1h 45min",
  },
  {
    id: 38,
    titulo: "Encanto",
    anio: 2021,
    genero: "Animación / Musical",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81zMDxF1R5L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Byron Howard y Jared Bush (Directores)",
    reseña: "Una explosión de color y música inspirada en la cultura colombiana, con un fuerte mensaje sobre el legado familiar.",
    descripcion: "Una joven es la única de su familia que no tiene un don mágico, pero debe salvar la magia de su casa.",
    recomendacion: "Un éxito de Disney con canciones pegadizas y un enfoque moderno en la dinámica familiar.",
    detalles: "La banda sonora incluye canciones de Lin-Manuel Miranda.",
    duracion: "1h 42min",
  },
  {
    id: 39,
    titulo: "Ratatouille",
    anio: 2007,
    genero: "Animación / Comedia",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81M0nGblcLL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Brad Bird (Director)",
    reseña: "Una comedia encantadora que demuestra que cualquiera puede lograr sus sueños, incluso una rata chef.",
    descripcion: "Una rata con un gusto refinado por la comida se asocia con un joven ayudante de cocina en París.",
    recomendacion: "Visualmente exquisita y un deleite para los amantes de la gastronomía.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación.",
    duracion: "1h 51min",
  },
  {
    id: 40,
    titulo: "Monsters Inc",
    anio: 2001,
    genero: "Animación / Fantasía",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81r+0D0EJzL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Pete Docter (Director)",
    reseña: "Una idea original y divertida que convierte a los monstruos del armario en personajes adorables.",
    descripcion: "Dos monstruos que trabajan asustando niños descubren que la risa es una fuente de energía más poderosa que el miedo.",
    recomendacion: "Una de las películas más tiernas y divertidas de Pixar.",
    detalles: "Nominada a 4 Oscars, ganando el de Mejor Canción Original.",
    duracion: "1h 32min",
  },
  {
    id: 41,
    titulo: "Zootopia",
    anio: 2016,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81xLzZka3RL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Byron Howard y Rich Moore (Directores)",
    reseña: "Una aventura de detectives con un mensaje social sutil y relevante para todas las edades.",
    descripcion: "Una conejita policía se une a un zorro estafador para resolver un caso de desapariciones en la gran ciudad.",
    recomendacion: "Inteligente, divertida y con una gran animación. Ganadora del Oscar.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación.",
    duracion: "1h 48min",
  },
  {
    id: 42,
    titulo: "Moana",
    anio: 2016,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81m+6cG8gEL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Ron Clements y John Musker (Directores)",
    reseña: "Una aventura marítima llena de mitología polinesia, personajes fuertes y canciones inolvidables.",
    descripcion: "Una valiente joven se aventura en el océano para salvar a su pueblo con la ayuda del semidiós Maui.",
    recomendacion: "Perfecta para los fans de las historias de heroínas y la aventura en el mar.",
    detalles: "Canciones de Lin-Manuel Miranda. Un éxito de crítica y público.",
    duracion: "1h 47min",
  },
  {
    id: 43,
    titulo: "Intensamente",
    anio: 2015,
    genero: "Animación / Emocional",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81LRwVbQMYL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Pete Docter (Director)",
    reseña: "Una obra maestra conceptual que explica la complejidad de las emociones humanas de forma sencilla y profunda.",
    descripcion: "Las emociones de una niña pequeña (Alegría, Tristeza, Miedo, etc.) luchan por guiarla a través de un cambio de vida.",
    recomendacion: "Una película esencial para niños y adultos. Educativa y muy conmovedora.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación.",
    duracion: "1h 35min",
  },
  {
    id: 44,
    titulo: "Luca",
    anio: 2021,
    genero: "Animación / Amistad",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81D2f5WdfJL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Enrico Casarosa (Director)",
    reseña: "Una carta de amor a la amistad, la aceptación y la cultura italiana, con un toque de fantasía veraniega.",
    descripcion: "Dos monstruos marinos adolescentes exploran el mundo humano en un pueblo costero de Italia.",
    recomendacion: "Una película cálida y encantadora sobre el valor de ser diferente.",
    detalles: "Ambientada en la Riviera Italiana. Un enfoque visual único y colorido.",
    duracion: "1h 35min",
  },
  {
    id: 45,
    titulo: "Up",
    anio: 2009,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81u3ZBzMleL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Pete Docter (Director)",
    reseña: "Una montaña rusa emocional. Su inicio es uno de los segmentos más aclamados en la historia de la animación.",
    descripcion: "Un anciano viudo cumple su sueño de atar miles de globos a su casa y volar a Sudamérica, con un joven polizón.",
    recomendacion: "No te dejes engañar por los globos, es una película profundamente adulta y conmovedora.",
    detalles: "Ganadora de 2 Oscars. Nombrada a Mejor Película, un honor raro para la animación.",
    duracion: "1h 36min",
  },
  {
    id: 46,
    titulo: "La Sirenita",
    anio: 2023,
    genero: "Musical / Fantasía",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81xDnL4McnL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+7",
    autor: "Rob Marshall (Director)",
    reseña: "La versión *live-action* del clásico de Disney, con nuevas canciones y efectos visuales impresionantes.",
    descripcion: "Una joven sirena sueña con experimentar el mundo humano y hace un trato peligroso con una bruja marina.",
    recomendacion: "Para revivir el clásico con una perspectiva moderna y una gran actuación vocal.",
    detalles: "Adaptación *live-action* del clásico animado de 1989.",
    duracion: "2h 15min",
  },
  {
    id: 47,
    titulo: "Mi villano favorito",
    anio: 2010,
    genero: "Animación / Comedia",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81rCeUFW9aL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Pierre Coffin y Chris Renaud (Directores)",
    reseña: "Presentó al mundo a los adorables Minions en una divertida historia sobre el descubrimiento de la paternidad.",
    descripcion: "Un supervillano planea robar la Luna, pero su plan se ve interrumpido por tres niñas huérfanas.",
    recomendacion: "Comedia animada ligera y muy divertida, especialmente por los Minions.",
    detalles: "La película que inició la exitosa franquicia de los Minions.",
    duracion: "1h 35min",
  },
  {
    id: 48,
    titulo: "Sing",
    anio: 2016,
    genero: "Animación / Musical",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/81CjEoaymFL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Garth Jennings (Director)",
    reseña: "Una celebración de la música con personajes animales y una banda sonora llena de éxitos.",
    descripcion: "Un koala organiza un concurso de canto para salvar su teatro de la ruina financiera.",
    recomendacion: "Mucha música y diversión. Ideal para una tarde familiar y animada.",
    detalles: "Producida por Illumination Entertainment.",
    duracion: "1h 48min",
  },
  {
    id: 49,
    titulo: "Pinocho",
    anio: 2022,
    genero: "Animación / Fantasía",
    categoria: "Kids",
    imagen: "https://m.media-amazon.com/images/I/91k9mP3vA6L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Guillermo del Toro (Director)",
    reseña: "Una reinterpretación oscura, visualmente deslumbrante y profundamente emotiva del cuento clásico.",
    descripcion: "Una versión en *stop-motion* del clásico de la marioneta que cobra vida, ambientada en la Italia fascista.",
    recomendacion: "Si buscas una animación artística, adulta y con un mensaje político y emocional profundo.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación. Obra maestra de *stop-motion*.",
    duracion: "1h 56min",
  },

  // ===============================
  // 🎥 DOCUMENTALES
  // ===============================
  {
    id: 50,
    titulo: "Nuestro Planeta",
    anio: 2019,
    genero: "Naturaleza / Ciencia",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81k1uvhZbZL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Alastair Fothergill (Director)",
    reseña: "Imágenes de naturaleza espectaculares con una narrativa centrada en la importancia de la conservación.",
    descripcion: "Una serie documental que explora los hábitats naturales del mundo y la urgencia de proteger la vida salvaje.",
    recomendacion: "Imprescindible por su cinematografía y su mensaje ecológico.",
    detalles: "Narrado por David Attenborough. Producido por Netflix y WWF.",
    duracion: "Serie, 8 episodios",
  },
  {
    id: 51,
    titulo: "Blackfish",
    anio: 2013,
    genero: "Animales / Denuncia",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81h4tS3ANbL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Gabriela Cowperthwaite (Directora)",
    reseña: "Un documental impactante y controvertido que generó un cambio en la industria de los parques marinos.",
    descripcion: "Examina la vida en cautiverio de la orca Tilikum y los peligros de mantener a estos animales en espectáculos.",
    recomendacion: "Un documental de denuncia que te hará replantearte los parques acuáticos.",
    detalles: "Tuvo un impacto significativo en la popularidad de SeaWorld.",
    duracion: "1h 23min",
  },
  {
    id: 52,
    titulo: "The Social Dilemma",
    anio: 2020,
    genero: "Tecnología / Sociedad",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81Zz3uEJKuL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Jeff Orlowski (Director)",
    reseña: "Revelador y preocupante. Expone cómo las redes sociales están diseñadas para manipular el comportamiento humano.",
    descripcion: "Entrevistas con exejecutivos de empresas tecnológicas que revelan el lado oscuro de las redes sociales.",
    recomendacion: "Si usas redes sociales, debes ver esta película para entender su impacto.",
    detalles: "Producido por Netflix. Mezcla entrevistas y segmentos dramatizados.",
    duracion: "1h 34min",
  },
  {
    id: 53,
    titulo: "Seaspiracy",
    anio: 2021,
    genero: "Océanos / Ecología",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81tB9hFTKoL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Ali Tabrizi (Director)",
    reseña: "Un documental polémico que explora el impacto de la pesca industrial en los ecosistemas marinos.",
    descripcion: "Un cineasta investiga la destrucción del ecosistema marino y la corrupción en la industria pesquera.",
    recomendacion: "Un *wake-up call* sobre el consumo de pescado y la salud de los océanos.",
    detalles: "Generó un gran debate en redes sociales por sus fuertes afirmaciones.",
    duracion: "1h 29min",
  },
  {
    id: 54,
    titulo: "The Tinder Swindler",
    anio: 2022,
    genero: "Crimen / Real",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81gmpz52stL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Felicity Morris (Directora)",
    reseña: "Un *true crime* adictivo sobre un estafador que utilizaba la aplicación de citas Tinder.",
    descripcion: "Varias mujeres narran cómo fueron engañadas y estafadas por un mismo hombre en la aplicación de citas.",
    recomendacion: "Si te gustan las historias de crímenes reales y el suspenso.",
    detalles: "Se convirtió en uno de los documentales más vistos de Netflix en su lanzamiento.",
    duracion: "1h 54min",
  },
  {
    id: 55,
    titulo: "13th",
    anio: 2016,
    genero: "Sociedad / Política",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81Bwo1Dwc6L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Ava DuVernay (Directora)",
    reseña: "Un documental poderoso y vital que expone la conexión entre la esclavitud y el sistema carcelario en EE. UU.",
    descripcion: "Analiza el artículo 13 de la Constitución de EE. UU. que prohibió la esclavitud, salvo como castigo por un delito.",
    recomendacion: "Una película muy importante para entender la historia racial y la justicia penal.",
    detalles: "Nominada al Oscar a Mejor Documental. Dirigida por la aclamada Ava DuVernay.",
    duracion: "1h 40min",
  },
  {
    id: 56,
    titulo: "David Attenborough: A Life on Our Planet",
    anio: 2020,
    genero: "Naturaleza / Reflexión",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81x5D2+dCGL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Alastair Fothergill, Jonnie Hughes (Directores)",
    reseña: "La reflexión personal de David Attenborough sobre su vida y la crisis ambiental que enfrenta el planeta.",
    descripcion: "El legendario naturalista comparte su testimonio y una visión de cómo podemos salvar el planeta.",
    recomendacion: "Esencial. Una combinación de biografía, naturaleza y llamado a la acción.",
    detalles: "Presentado como el 'testimonio' de Attenborough para el futuro.",
    duracion: "1h 23min",
  },
  {
    id: 57,
    titulo: "My Octopus Teacher",
    anio: 2020,
    genero: "Naturaleza / Vida Marina",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81j0L-FC8zL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "Pippa Ehrlich y James Reed (Directores)",
    reseña: "Un documental conmovedor sobre la extraña amistad entre un cineasta y un pulpo.",
    descripcion: "Un cineasta de vida salvaje establece una relación inusual con un pulpo que vive en un bosque de algas marinas.",
    recomendacion: "Un documental tierno, poético y visualmente espectacular. Ganador del Oscar.",
    detalles: "Ganador del Oscar a Mejor Documental.",
    duracion: "1h 25min",
  },
  {
    id: 58,
    titulo: "American Factory",
    anio: 2019,
    genero: "Trabajo / Sociedad",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81x8rE47HqL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Steven Bognar y Julia Reichert (Directores)",
    reseña: "Una mirada fascinante y tensa al choque de culturas cuando una empresa china abre una fábrica en EE. UU.",
    descripcion: "Documenta el intento de una corporación china de revitalizar una fábrica abandonada en Ohio.",
    recomendacion: "Interesante para ver las diferencias culturales en el entorno laboral y la globalización.",
    detalles: "El primer documental producido por la compañía de Barack y Michelle Obama, Higher Ground.",
    duracion: "1h 50min",
  },
  {
    id: 59,
    titulo: "Crip Camp",
    anio: 2020,
    genero: "Derechos Humanos / Historia",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81pySMu+JQL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Nicole Newnham y James LeBrecht (Directores)",
    reseña: "Una historia inspiradora y crucial sobre el movimiento de derechos de las personas con discapacidad.",
    descripcion: "Documenta un campamento de verano para adolescentes con discapacidad que se convirtió en un catalizador para la lucha por la igualdad.",
    recomendacion: "Una joya histórica que muestra la importancia de la comunidad y la acción social.",
    detalles: "Producido por la compañía de Barack y Michelle Obama, Higher Ground.",
    duracion: "1h 47min",
  },
  {
    id: 60,
    titulo: "The Deepest Breath",
    anio: 2023,
    genero: "Aventura / Océano",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81j2CjSfAoL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Laura McGann (Directora)",
    reseña: "Un documental fascinante sobre la adrenalina y el peligro del buceo en apnea.",
    descripcion: "Sigue la vida de una buceadora en apnea y un buzo de seguridad, y la conexión entre ellos.",
    recomendacion: "Un *thriller* bajo el agua. Visualmente impactante y muy tenso.",
    detalles: "Documental original de Netflix.",
    duracion: "1h 48min",
  },
  {
    id: 61,
    titulo: "Beckham",
    anio: 2023,
    genero: "Deporte / Biografía",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81M0W4UMCEL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Fisher Stevens (Director)",
    reseña: "Una mirada íntima y sincera a la vida del ícono del fútbol David Beckham, más allá de la fama.",
    descripcion: "Serie documental que explora la carrera, la vida personal y el ascenso a la fama de David Beckham.",
    recomendacion: "Interesante tanto para fans del fútbol como para los interesados en la cultura pop y los medios.",
    detalles: "Miniserie de 4 episodios. Muestra su relación con Victoria Beckham.",
    duracion: "4 episodios (aprox. 4 horas)",
  },
  {
    id: 62,
    titulo: "Arnold",
    anio: 2023,
    genero: "Biografía / Superación",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81qqUoy6AsL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Lesley Chilcott (Directora)",
    reseña: "La historia épica de Arnold Schwarzenegger: del culturismo al cine y la política.",
    descripcion: "Miniserie que relata las múltiples vidas de Arnold, con entrevistas y material de archivo inédito.",
    recomendacion: "Una biografía inspiradora sobre la ambición y la perseverancia.",
    detalles: "Miniserie de 3 episodios en Netflix.",
    duracion: "3 episodios (aprox. 3 horas)",
  },
  {
    id: 63,
    titulo: "Billie Eilish: The World's a Little Blurry",
    anio: 2021,
    genero: "Música / Juventud",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81Ojx7LBnsL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "R.J. Cutler (Director)",
    reseña: "Una visión sin filtro de la vida de Billie Eilish, desde la creación musical hasta la fama global.",
    descripcion: "Sigue la vida de la joven artista mientras graba su álbum debut y experimenta el salto a la fama.",
    recomendacion: "Interesante para entender los desafíos de la fama y el proceso creativo.",
    detalles: "Documental original de Apple TV+.",
    duracion: "2h 20min",
  },
  {
    id: 64,
    titulo: "Taylor Swift: Miss Americana",
    anio: 2020,
    genero: "Música / Inspiración",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81AqNQ9mVFL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Lana Wilson (Directora)",
    reseña: "Un documental íntimo que muestra el lado vulnerable de Taylor Swift y su despertar político.",
    descripcion: "Taylor Swift se sincera sobre su vida, su música, la presión pública y su lucha por el control artístico.",
    recomendacion: "Para entender la evolución de una de las artistas más influyentes del pop.",
    detalles: "Documental original de Netflix.",
    duracion: "1h 25min",
  },
  {
    id: 65,
    titulo: "Planet Earth II",
    anio: 2016,
    genero: "Naturaleza / Mundo",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81yBt6uwOqL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "Apta para todos",
    autor: "David Attenborough (Narrador)",
    reseña: "Una serie documental que es un triunfo técnico y visual, con escenas de vida salvaje épicas.",
    descripcion: "Explora los diferentes biomas del planeta con una calidad de imagen 4K impresionante.",
    recomendacion: "La cúspide de los documentales de naturaleza. Absolutamente obligatorio.",
    detalles: "Secuela de la aclamada 'Planet Earth' (2006).",
    duracion: "Serie, 6 episodios",
  },
  {
    id: 66,
    titulo: "Inside Job",
    anio: 2010,
    genero: "Economía / Política",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81nERkgw3nL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Charles Ferguson (Director)",
    reseña: "Un análisis meticuloso y demoledor de la crisis financiera de 2008, explicando su origen y consecuencias.",
    descripcion: "Investiga las causas de la crisis económica mundial, con entrevistas a políticos y expertos.",
    recomendacion: "Esencial para entender la complejidad de la economía moderna y las fallas del sistema.",
    detalles: "Ganador del Oscar a Mejor Documental. Narrado por Matt Damon.",
    duracion: "1h 48min",
  },
  {
    id: 67,
    titulo: "The Great Hack",
    anio: 2019,
    genero: "Tecnología / Privacidad",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81YNNdPUnaL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Jehane Noujaim y Karim Amer (Directores)",
    reseña: "Un *thriller* sobre datos que revela cómo la información se convirtió en la mercancía más valiosa del mundo.",
    descripcion: "Investiga el escándalo de Cambridge Analytica y su impacto en las elecciones y la privacidad.",
    recomendacion: "Impactante, muestra el peligro de la minería de datos en la democracia.",
    detalles: "Documental original de Netflix.",
    duracion: "1h 54min",
  },
  {
    id: 68,
    titulo: "Wild Wild Country",
    anio: 2018,
    genero: "Religión / Misterio",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81g+X7CUpZL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+18",
    autor: "Maclain Way y Chapman Way (Directores)",
    reseña: "Una historia de culto real tan extraña que parece ficción. Mantiene la tensión en cada episodio.",
    descripcion: "Relata la controversial comunidad establecida por el gurú Bhagwan Shree Rajneesh en Oregón, EE. UU.",
    recomendacion: "Perfecto para el *binge-watching*. Una visión única de la ambición religiosa y política.",
    detalles: "Miniserie de 6 episodios en Netflix.",
    duracion: "Miniserie, 6 episodios",
  },
  {
    id: 69,
    titulo: "The Last Dance",
    anio: 2020,
    genero: "Deporte / Inspiración",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81OHgU0U+LL._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+13",
    autor: "Jason Hehir (Director)",
    reseña: "Un viaje nostálgico e intenso a la era dorada de los Chicago Bulls y Michael Jordan.",
    descripcion: "Crónica de la última temporada de Michael Jordan con los Bulls, con entrevistas exclusivas y material inédito.",
    recomendacion: "Si te gusta el deporte o las historias de superación, es un *must-watch*.",
    detalles: "Miniserie de 10 episodios. Un éxito global durante la pandemia.",
    duracion: "Miniserie, 10 episodios",
  },
  {
    id: 70,
    titulo: "Navalny",
    anio: 2022,
    genero: "Política / Corrupción",
    categoria: "Documentales",
    imagen: "https://m.media-amazon.com/images/I/81O4L4f9o6L._AC_UF894,1000_QL80_.jpg",
    rangoEdad: "+16",
    autor: "Daniel Roher (Director)",
    reseña: "Un *thriller* político de la vida real sobre el líder de la oposición rusa y su envenenamiento.",
    descripcion: "Sigue la investigación sobre el intento de asesinato de Alexéi Navalny y su confrontación con el Kremlin.",
    recomendacion: "Un documental de alto riesgo, tenso y con momentos increíbles de periodismo de investigación.",
    detalles: "Ganador del Oscar a Mejor Documental. Rodado en secreto.",
    duracion: "1h 38min",
  },

  // ===============================
  // 🎎 ASIÁTICAS (COREANAS / ANIMES)
  // ===============================
  {
    id: 71,
    titulo: "Parasite",
    anio: 2019,
    genero: "Thriller / Drama",
    categoria: "Asiáticas",
    imagen: "https://img.rtve.es/imagenes/caratula-parasito-saga-completa/1466077733963.jpg",
    rangoEdad: "+16",
    autor: "Bong Joon-ho (Director)",
    reseña: "Una obra maestra de la sátira social, con giros inesperados y una ejecución brillante.",
    descripcion: "Una familia pobre se infiltra, uno por uno, en el hogar de una familia rica con consecuencias catastróficas.",
    recomendacion: "Cine moderno esencial. Una crítica social inteligente con humor negro.",
    detalles: "Ganadora de la Palma de Oro y 4 Premios de la Academia, incluyendo Mejor Película.",
    duracion: "2h 12min",
  },
  {
    id: 72,
    titulo: "Train to Busan",
    anio: 2016,
    genero: "Terror / Acción",
    categoria: "Asiáticas",
    imagen: "https://images.justwatch.com/poster/9373937/s718/train-to-busan.jpg",
    rangoEdad: "+18",
    autor: "Yeon Sang-ho (Director)",
    reseña: "Una de las mejores películas de zombis de la década, intensa, emocionante y con un ritmo implacable.",
    descripcion: "Un padre y su hija quedan atrapados en un tren de alta velocidad mientras un apocalipsis zombi estalla en Corea.",
    recomendacion: "Acción trepidante. Ideal para fans del terror y el suspenso coreano.",
    detalles: "Un gran éxito internacional del cine surcoreano.",
    duracion: "1h 58min",
  },
  {
    id: 73,
    titulo: "My Name",
    anio: 2021,
    genero: "Acción / Drama",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BN2ZiZWU3MzMtNGM5OC00ZWVkLTkxNjUtMTYwZGU4MzgxYzk0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Kim Jin-min (Director)",
    reseña: "Un drama de venganza oscuro con escenas de acción brutales y una gran actuación de su protagonista.",
    descripcion: "Una joven se une a un cartel de drogas para descubrir la verdad detrás del asesinato de su padre.",
    recomendacion: "Si disfrutas de *K-dramas* de acción y venganza con personajes femeninos fuertes.",
    detalles: "Serie de 8 episodios. Un éxito de Netflix.",
    duracion: "Serie, 8 episodios",
  },
  {
    id: 74,
    titulo: "The Glory",
    anio: 2023,
    genero: "Drama / Venganza",
    categoria: "Asiáticas",
    imagen: "https://pics.filmaffinity.com/La_gloria_Serie_de_TV-431017765-large.jpg",
    rangoEdad: "+16",
    autor: "An Gil-ho (Director)",
    reseña: "Un drama de venganza meticuloso y bien escrito que aborda el acoso escolar y la justicia.",
    descripcion: "Años después de ser víctima de *bullying*, una mujer ejecuta un elaborado plan de venganza contra sus acosadores.",
    recomendacion: "Uno de los *K-dramas* más aclamados y populares sobre justicia personal.",
    detalles: "Serie de 16 episodios dividida en dos partes. Protagonizada por Song Hye-kyo.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 75,
    titulo: "Extraordinary You",
    anio: 2019,
    genero: "Romance / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ2jC7TEk0s7u4RJKInfbfI_LlXTblbEdchNlmpTKBEsYHZtApNLSO-KSbzPwRpu0W7iw&usqp=CAU",
    rangoEdad: "+13",
    autor: "Kim Sang-hyeop (Director)",
    reseña: "Un *K-drama* único que juega con el concepto de la realidad dentro de un cómic.",
    descripcion: "Una estudiante descubre que es un personaje secundario en un *manhwa* y decide cambiar su destino.",
    recomendacion: "Fantasía juvenil con una premisa original y mucho romance *meta-ficcional*.",
    detalles: "Basada en un *webtoon*. Mezcla comedia, romance y fantasía.",
    duracion: "Serie, 32 episodios cortos",
  },
  {
    id: 76,
    titulo: "Start-Up",
    anio: 2020,
    genero: "Drama / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BYTJiYmE0ZGItMmU1NS00NThhLWIzODEtZmJlYjBmMzcwNmY3XkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Oh Choong-hwan (Director)",
    reseña: "Una serie inspiradora sobre jóvenes ambiciosos que buscan triunfar en el competitivo mundo de las *start-ups* tecnológicas.",
    descripcion: "Un grupo de jóvenes compite por el éxito en un distrito de Corea, enfrentando dilemas de negocios y amor.",
    recomendacion: "Ideal si te gustan las historias de emprendimiento con un triángulo amoroso central.",
    detalles: "Con Suzy y Nam Joo-hyuk. Se centra en la tecnología y la innovación.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 77,
    titulo: "Alchemy of Souls",
    anio: 2022,
    genero: "Fantasía / Aventura",
    categoria: "Asiáticas",
    imagen: "https://www.monash.edu/__data/assets/image/0006/3069096/Alchemy-of-Souls-official-poster.jpg",
    rangoEdad: "+16",
    autor: "Park Joon-hwa (Director)",
    reseña: "Una fantasía épica y compleja con hermosos escenarios, magia, acción y romance.",
    descripcion: "Una hechicera se encuentra atrapada en el cuerpo de una guerrera ciega y se convierte en sirvienta de un noble.",
    recomendacion: "Si amas la fantasía coreana con gran desarrollo de personajes y mitología.",
    detalles: "Dividida en dos partes, con un total de 30 episodios. Gran éxito de TVN.",
    duracion: "Serie, 30 episodios",
  },
  {
    id: 78,
    titulo: "Twenty-Five Twenty-One",
    anio: 2022,
    genero: "Drama / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BNDU3ODZjMzAtYTIyZi00MGExLWFhYjEtOGQ5YjVlMjU3MjNlXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Jung Ji-hyun (Director)",
    reseña: "Un drama *slice of life* conmovedor y nostálgico sobre el primer amor, los sueños y la madurez.",
    descripcion: "La historia de dos jóvenes cuyas vidas se entrelazan en 1998, durante la crisis financiera asiática.",
    recomendacion: "Un drama romántico y profundo, con una estética visual muy cuidada.",
    detalles: "Protagonizada por Kim Tae-ri y Nam Joo-hyuk.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 79,
    titulo: "Squid Game",
    anio: 2021,
    genero: "Acción / Suspenso",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BMDcxYjg1OTctYmUxZi00ZjhjLWIwNTMtNmI2M2Y4OTU1YWU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Hwang Dong-hyuk (Director)",
    reseña: "El fenómeno mundial de Netflix. Tensión extrema, crítica social y un concepto brutal.",
    descripcion: "Cientos de personas con problemas de dinero aceptan participar en juegos infantiles mortales por una gran suma de dinero.",
    recomendacion: "Un *thriller* de supervivencia imprescindible. Intenso y con mucha crítica al capitalismo.",
    detalles: "Se convirtió en la serie más vista de la historia de Netflix en su lanzamiento.",
    duracion: "Serie, 9 episodios",
  },
  {
    id: 80,
    titulo: "All of Us Are Dead",
    anio: 2022,
    genero: "Terror / Escolar",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZxay4or86F0zxdpPsmrbpXXutgSKklnYtrb9E15oPc0tzOcro4u7PDYG0idNv80StwCI&usqp=CAU",
    rangoEdad: "+18",
    autor: "Lee Jae-gyoo (Director)",
    reseña: "Un *K-drama* de zombis ultra violento y con mucha adrenalina, centrado en el drama adolescente.",
    descripcion: "Un grupo de estudiantes queda atrapado en su instituto durante el inicio de un apocalipsis zombi.",
    recomendacion: "Para fans del género zombi con mucha acción y tensión de supervivencia.",
    detalles: "Basada en el *webtoon* 'Now at Our School'.",
    duracion: "Serie, 12 episodios",
  },
  {
    id: 81,
    titulo: "Your Name",
    anio: 2016,
    genero: "Anime / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BMTIyNzFjNzItZmQ1MC00NzhjLThmMzYtZjRhN2Y3MmM2OGQyXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Makoto Shinkai (Director)",
    reseña: "Una obra maestra visual que combina romance, fantasía y un giro narrativo sorprendente.",
    descripcion: "Un chico de Tokio y una chica de un pueblo rural comienzan a intercambiar cuerpos misteriosamente.",
    recomendacion: "Imprescindible para los fans del anime. Una película visualmente deslumbrante.",
    detalles: "Uno de los animes más taquilleros de la historia.",
    duracion: "1h 47min",
  },
  {
    id: 82,
    titulo: "A Silent Voice",
    anio: 2016,
    genero: "Anime / Drama",
    categoria: "Asiáticas",
    imagen: "https://upload.wikimedia.org/wikipedia/en/3/32/A_Silent_Voice_Film_Poster.jpg",
    rangoEdad: "+13",
    autor: "Naoko Yamada (Directora)",
    reseña: "Un drama adolescente maduro y sensible sobre el *bullying*, la culpa y la búsqueda de la redención.",
    descripcion: "Un joven busca hacer las paces con una chica sorda a la que acosó en la infancia.",
    recomendacion: "Un anime profundo y muy emotivo que aborda temas difíciles con gran sensibilidad.",
    detalles: "Basada en el manga homónimo de Yoshitoki Ōima.",
    duracion: "2h 10min",
  },
  {
    id: 83,
    titulo: "Spirited Away",
    anio: 2001,
    genero: "Anime / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BM2E2YzcwMTQtNWRlMC00ZGZlLWJhZTEtMDU4ZGIzMWI0NzJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+7",
    autor: "Hayao Miyazaki (Director)",
    reseña: "Una joya de Studio Ghibli. Pura fantasía onírica con una animación magistral y una rica mitología.",
    descripcion: "Una niña se adentra en un mundo espiritual para rescatar a sus padres convertidos en cerdos.",
    recomendacion: "Un clásico del anime y una de las películas de fantasía más importantes de la historia.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación (única película de anime en lograrlo).",
    duracion: "2h 5min",
  },
  {
    id: 84,
    titulo: "Demon Slayer: Mugen Train",
    anio: 2020,
    genero: "Anime / Acción",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BNzEzYjhkYTctMWNmZS00MTc5LWI4OWUtZjFkNzNkYTNkMTJlXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+16",
    autor: "Haruo Sotozaki (Director)",
    reseña: "Una continuación directa del anime, con batallas impresionantes y un gran impacto emocional.",
    descripcion: "Tanjiro y sus compañeros se unen a un poderoso cazador de demonios para investigar misterios en un tren.",
    recomendacion: "Acción visualmente espectacular. Si te gusta el anime, es imperdible.",
    detalles: "Rompió récords de taquilla en Japón y a nivel mundial para una película de anime.",
    duracion: "1h 57min",
  },
  {
    id: 85,
    titulo: "Attack on Titan",
    anio: 2013,
    genero: "Anime / Épico",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BZjliODY5MzQtMmViZC00MTZmLWFhMWMtMjMwM2I3OGY1MTRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Tetsurō Araki (Director)",
    reseña: "Una serie anime brutalmente intensa, con un mundo post-apocalíptico fascinante y mucha acción.",
    descripcion: "La humanidad lucha por sobrevivir dentro de murallas contra gigantes devoradores de personas.",
    recomendacion: "Si buscas una serie con acción, misterio y un gran desarrollo de personajes.",
    detalles: "Basada en el manga de Hajime Isayama. Famosa por sus giros argumentales.",
    duracion: "Serie, 4 temporadas",
  },
  {
    id: 86,
    titulo: "Naruto",
    anio: 2002,
    genero: "Anime / Aventura",
    categoria: "Asiáticas",
    imagen: "https://pics.filmaffinity.com/naruto_movie_1_daikatsugeki_yukihime_ninpocho_dattebayo_naruto_the_movie_ninja_clash_in_the_land_of_snow-813795021-msmall.jpg",
    rangoEdad: "+13",
    autor: "Masashi Kishimoto (Manga)",
    reseña: "Un anime *shonen* de culto que inspira con su historia de un joven ninja que busca el reconocimiento.",
    descripcion: "Un joven ninja marginado sueña con convertirse en el líder de su aldea (Hokage).",
    recomendacion: "Un clásico para iniciarse en el mundo del anime de aventuras y superación.",
    detalles: "La imagen corresponde a la primera película: 'Ninja Clash in the Land of Snow'.",
    duracion: "Serie, 220 episodios",
  },
  {
    id: 87,
    titulo: "One Piece Film: Red",
    anio: 2022,
    genero: "Anime / Acción",
    categoria: "Asiáticas",
    imagen: "https://pics.filmaffinity.com/One_Piece_Film_Red-407711303-large.jpg",
    rangoEdad: "+13",
    autor: "Gorō Taniguchi (Director)",
    reseña: "Una aventura cinematográfica emocionante con mucha acción, y que introduce a un personaje clave.",
    descripcion: "La tripulación de Luffy se encuentra con Uta, la cantante más querida del mundo, que esconde un secreto.",
    recomendacion: "Para los fans de One Piece es un *must*. Mucha música y batallas épicas.",
    detalles: "La decimoquinta película de la franquicia One Piece.",
    duracion: "1h 55min",
  },
  {
    id: 88,
    titulo: "Jujutsu Kaisen 0",
    anio: 2021,
    genero: "Anime / Sobrenatural",
    categoria: "Asiáticas",
    imagen: "https://es.web.img3.acsta.net/pictures/22/05/18/16/23/5993750.jpg",
    rangoEdad: "+16",
    autor: "Sunghoo Park (Director)",
    reseña: "Una precuela intensa y oscura que expande el universo de Jujutsu Kaisen con acción increíble.",
    descripcion: "Un joven atormentado por el espíritu de su amiga de la infancia se une a la Escuela de Hechicería Jujutsu.",
    recomendacion: "Acción oscura y sobrenatural. Excelente animación y desarrollo de personajes.",
    detalles: "Basada en el manga precuela del éxito de Gege Akutami.",
    duracion: "1h 45min",
  },
  {
    id: 89,
    titulo: "Belle",
    anio: 2021,
    genero: "Anime / Musical",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdl4BP4Nyl9D9QUlzcg6sKotOpwy93-KXApg&s",
    rangoEdad: "+13",
    autor: "Mamoru Hosoda (Director)",
    reseña: "Una reinterpretación de 'La Bella y la Bestia' en la era digital, con un diseño de personaje espectacular.",
    descripcion: "Una adolescente tímida se convierte en una superestrella musical en un mundo virtual masivo.",
    recomendacion: "Visualmente impresionante y con una banda sonora moderna y emotiva.",
    detalles: "Dirigida por el aclamado Mamoru Hosoda ('Mirai', 'Summer Wars').",
    duracion: "2h 1min",
  },
  {
    id: 91,
    titulo: "Demon Slayer – The Movie: Infinity Castle",
    anio: 2025,
    genero: "Anime / Acción / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://pics.filmaffinity.com/Demon_Slayer_Kimetsu_no_Yaiba_AO_Castillo_infinito-319955045-large.jpg",
    rangoEdad: "+16",
    autor: "Koyoharu Gotōge (Manga)",
    reseña: "La esperada conclusión de la saga de Demon Slayer en formato cinematográfico. Será un evento épico.",
    descripcion: "Los Cazadores de Demonios se enfrentan a Muzan Kibutsuji y sus Lunas Superiores en el Castillo Infinito.",
    recomendacion: "La batalla final de la serie. Máxima expectación para los fans.",
    detalles: "Adaptación del arco final del manga. Dividida en varias partes.",
    duracion: "Tiempo estimado: 2h 20min (Parte 1)",
  },
];

export default peliculas;