const peliculas = [
  // ===============================
  // 📚 BASADAS EN LIBROS
  // ===============================
  {
    id: 1,
    titulo: "Harry Potter y la Piedra Filosofal",
    anio: 2001,
    genero: "Fantasía / Aventura",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BYTkyYjVkNDItODc1Ny00NzA1LTkwY2YtZDUwNTlhMDk3MTZiXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+7",
    autor: "J.K. Rowling (Libro)",
    reseña: "Una adaptación mágica que captura la esencia de la amistad y la lucha contra el mal, perfecta para iniciar una saga épica.",
    descripcion: "Harry Potter descubre que es un mago y comienza su aventura en la Escuela de Magia y Hechicería de Hogwarts.",
    recomendacion: "Imprescindible para los fans de la magia y la fantasía. Gran inicio de saga.",
    detalles: "Basada en el libro 'Harry Potter y la Piedra Filosofal'. Dirigida por Chris Columbus.",
    duracion: "2h 32min",
  },
  {
    id: 2,
    titulo: "Orgullo y Prejuicio",
    anio: 2005,
    genero: "Romance / Drama",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BZjBlODgwZWEtODcxMi00OTY5LWEyOTItODE2MDBjZjU0ZDU3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+12",
    autor: "Jane Austen (Libro)",
    reseña: "Una hermosa adaptación visualmente impactante que honra el clásico literario de Jane Austen.",
    descripcion: "La historia de cinco hermanas en la Inglaterra rural del siglo XIX y las presiones sociales para casarse.",
    recomendacion: "Ideal para amantes del drama de época y el romance con diálogos brillantes.",
    detalles: "Protagonizada por Keira Knightley. Captura la atmósfera y el ingenio de la novela.",
    duracion: "2h 9min",
  },
  {
    id: 3,
    titulo: "El señor de los anillos",
    anio: 2001,
    genero: "Fantasía / Épico",
    categoria: "Basadas en Libros",
    imagen: "https://es.web.img2.acsta.net/c_310_420/medias/nmedia/18/89/67/45/20061512.jpg",
    rangoEdad: "+13",
    autor: "J.R.R. Tolkien (Libro)",
    reseña: "Una obra maestra del cine de fantasía, con un mundo inmersivo y personajes inolvidables.",
    descripcion: "Un hobbit debe emprender una épica búsqueda para destruir un anillo mágico y salvar la Tierra Media.",
    recomendacion: "La mejor adaptación de fantasía jamás hecha. Ver la versión extendida es un ritual.",
    detalles: "Parte 1: La Comunidad del Anillo. Dirigida por Peter Jackson.",
    duracion: "2h 58min",
  },
  {
    id: 4,
    titulo: "Crepúsculo",
    anio: 2008,
    genero: "Romance / Fantasía",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BOGEwYWIzOGEtMzY2Ny00NzE0LTkwZmQtYjk5NTE2ZmZiM2QxXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+14",
    autor: "Stephenie Meyer (Libro)",
    reseña: "Un fenómeno cultural que definió el romance sobrenatural adolescente de su generación.",
    descripcion: "Una adolescente se enamora de un misterioso compañero de clase que resulta ser un vampiro.",
    recomendacion: "Para fans de las historias de amor prohibido y la fantasía juvenil.",
    detalles: "Basada en la novela homónima, la película lanzó a la fama a sus protagonistas.",
    duracion: "2h 2min",
  },
  {
    id: 5,
    titulo: "Yo antes de ti",
    anio: 2016,
    genero: "Romance / Drama",
    categoria: "Basadas en Libros",
    imagen: "https://www.libreriasur.com.pe/imagenes/9789870/978987043466.webp",
    rangoEdad: "+16",
    autor: "Jojo Moyes (Libro)",
    reseña: "Una película emotiva que explora el amor, la vida y las decisiones difíciles. Prepárate para llorar.",
    descripcion: "Una joven es contratada para cuidar a un joven y rico banquero que quedó paralizado tras un accidente.",
    recomendacion: "Un drama romántico con un mensaje profundo sobre la calidad de vida.",
    detalles: "Protagonizada por Emilia Clarke y Sam Claflin. Un éxito de taquilla y crítica.",
    duracion: "1h 50min",
  },
  {
    id: 6,
    titulo: "El padrino",
    anio: 1972,
    genero: "Crimen / Drama",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BZmNiNzM4MTctODI5YS00MzczLWE2MzktNzY4YmNjYjA5YmY1XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Mario Puzo (Libro)",
    reseña: "Considerada una de las mejores películas de la historia. Un estudio magistral sobre la familia, el poder y la corrupción.",
    descripcion: "Crónica de la vida de la familia mafiosa Corleone en Nueva York tras la Segunda Guerra Mundial.",
    recomendacion: "Cine clásico obligatorio. Una lección de dirección y actuación.",
    detalles: "Dirigida por Francis Ford Coppola. Ganadora de 3 Oscars. Clave del género de gángsters.",
    duracion: "2h 55min",
  },
  {
    id: 7,
    titulo: "El resplandor",
    anio: 1980,
    genero: "Terror / Psicológico",
    categoria: "Basadas en Libros",
    imagen: "https://es.web.img3.acsta.net/pictures/14/04/15/10/46/568345.jpg",
    rangoEdad: "+18",
    autor: "Stephen King (Libro)",
    reseña: "Una obra cumbre del terror psicológico, con una atmósfera opresiva y una actuación icónica de Jack Nicholson.",
    descripcion: "Un escritor acepta un trabajo como cuidador de invierno en un hotel aislado, donde comienza a enloquecer.",
    recomendacion: "Si buscas un terror lento, atmosférico y que te haga pensar, esta es tu película.",
    detalles: "Dirigida por Stanley Kubrick. Un clásico de culto que difiere del libro en varios aspectos.",
    duracion: "1h 59min",
  },
  {
    id: 8,
    titulo: "Mujercitas",
    anio: 2019,
    genero: "Drama / Histórico",
    categoria: "Basadas en Libros",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUtfbFFKCv0lZl6gCJuQKHV8aILZdLoqlL3g&s",
    rangoEdad: "+7",
    autor: "Louisa May Alcott (Libro)",
    reseña: "Una vibrante y moderna reimaginación de una historia atemporal sobre las aspiraciones de cuatro hermanas.",
    descripcion: "Retrato de las vidas de las hermanas March mientras exploran el paso a la edad adulta y sus sueños individuales.",
    recomendacion: "Una película visualmente hermosa y con actuaciones sobresalientes.",
    detalles: "Dirigida por Greta Gerwig. Nominada a múltiples Oscars.",
    duracion: "2h 15min",
  },
  {
    id: 9,
    titulo: "It",
    anio: 2017,
    genero: "Terror",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BZDFhODExOTctNTFkZS00NjE1LWE2MWMtY2Q1ZThhMGY5NjJkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+16",
    autor: "Stephen King (Libro)",
    reseña: "Una de las mejores adaptaciones recientes de King, centrada en la amistad y el terror puro.",
    descripcion: "Siete niños se enfrentan a un payaso maligno que acecha la pequeña ciudad de Derry.",
    recomendacion: "Excelente mezcla de terror y una conmovedora historia de 'coming of age'.",
    detalles: "Basada en la novela de 1986. Primera parte de dos.",
    duracion: "2h 15min",
  },
  {
    id: 10,
    titulo: "Psicosis",
    anio: 1960,
    genero: "Suspenso / Terror",
    categoria: "Basadas en Libros",
    imagen: "https://storage.googleapis.com/cclm-prod/2025/03/afiche-psicosis.jpg",
    rangoEdad: "+16",
    autor: "Robert Bloch (Libro)",
    reseña: "El thriller por excelencia que sentó las bases para el género de terror moderno. Inolvidable e innovadora.",
    descripcion: "Una secretaria fugitiva se aloja en un motel regentado por un joven tímido con una madre dominante.",
    recomendacion: "Un clásico de Alfred Hitchcock. Su giro final es historia del cine.",
    detalles: "Dirigida por Alfred Hitchcock. La famosa escena de la ducha es legendaria.",
    duracion: "1h 49min",
  },
  {
    id: 11,
    titulo: "Los juegos del hambre",
    anio: 2012,
    genero: "Ciencia Ficción / Acción",
    categoria: "Basadas en Libros",
    imagen: "https://es.web.img2.acsta.net/medias/nmedia/18/86/46/05/19945375.jpg",
    rangoEdad: "+13",
    autor: "Suzanne Collins (Libro)",
    reseña: "Una sólida adaptación que ofrece acción, crítica social y un fuerte personaje femenino principal.",
    descripcion: "En un futuro distópico, dos jóvenes de cada distrito son elegidos para luchar a muerte en un evento televisado.",
    recomendacion: "Buena para introducirse en el género distópico y de acción juvenil.",
    detalles: "Protagonizada por Jennifer Lawrence. Basada en el primer libro de la trilogía.",
    duracion: "2h 22min",
  },
  {
    id: 12,
    titulo: "El código Da Vinci",
    anio: 2006,
    genero: "Misterio / Suspenso",
    categoria: "Basadas en Libros",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRL-7WJiojB0FSIoXNNsaY_HR5INiAVV2ZB7A&s",
    rangoEdad: "+13",
    autor: "Dan Brown (Libro)",
    reseña: "Un thriller trepidante lleno de enigmas históricos, perfecto para los amantes de las conspiraciones.",
    descripcion: "Un simbologista debe descifrar un misterio que se esconde tras la obra de Leonardo da Vinci.",
    recomendacion: "Ideal si disfrutas de películas que combinan historia, arte y suspenso.",
    detalles: "Dirigida por Ron Howard y protagonizada por Tom Hanks.",
    duracion: "2h 29min",
  },
  {
    id: 13,
    titulo: "Las ventajas de ser invisible",
    anio: 2012,
    genero: "Drama / Adolescente",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BYzM0MDI3MjQtZTc0MC00YzNlLWExYjUtNjFlOTg3NmI5ZWUyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+14",
    autor: "Stephen Chbosky (Libro y Director)",
    reseña: "Una película honesta y emotiva sobre la salud mental, la amistad y encontrar tu lugar en el mundo.",
    descripcion: "Un adolescente socialmente incómodo entra a la escuela secundaria y es acogido por dos estudiantes carismáticos.",
    recomendacion: "Un drama conmovedor y muy bien valorado por su retrato de la adolescencia.",
    detalles: "El autor del libro también dirigió la película. Protagonizada por Logan Lerman, Emma Watson.",
    duracion: "1h 43min",
  },
  {
    id: 14,
    titulo: "El niño con el pijama de rayas",
    anio: 2008,
    genero: "Drama / Guerra",
    categoria: "Basadas en Libros",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTtm_yyxrb-ju2TTyS0GimoGsYFTtLpnv_dQ&s",
    rangoEdad: "+16",
    autor: "John Boyne (Libro)",
    reseña: "Un relato desgarrador y necesario sobre el Holocausto, visto a través de la inocencia de dos niños.",
    descripcion: "Un niño alemán se muda con su familia y se hace amigo de un niño judío al otro lado de la cerca de un campo de concentración.",
    recomendacion: "Un drama intenso que te dejará reflexionando. Preparar pañuelos.",
    detalles: "Basada en la novela de 2006. Ambientada durante la Segunda Guerra Mundial.",
    duracion: "1h 34min",
  },
  {
    id: 15,
    titulo: "La milla verde",
    anio: 1999,
    genero: "Drama / Fantasía",
    categoria: "Basadas en Libros",
    imagen: "https://covers.mymovies.dk/0be90224-283e-40a6-8023-cc5bf208628d.jpg",
    rangoEdad: "+16",
    autor: "Stephen King (Libro)",
    reseña: "Un drama profundamente emotivo que toca temas de justicia, milagros y la naturaleza humana.",
    descripcion: "Un guardia de prisión en el corredor de la muerte narra su experiencia con un recluso de gran tamaño y poderes sobrenaturales.",
    recomendacion: "Una película que todo amante del drama debe ver. Tan conmovedora como 'Cadena Perpetua'.",
    detalles: "Protagonizada por Tom Hanks. Dirigida por Frank Darabont.",
    duracion: "3h 9min",
  },
  {
    id: 16,
    titulo: "Forrest Gump",
    anio: 1994,
    genero: "Drama / Comedia",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+13",
    autor: "Winston Groom (Libro)",
    reseña: "Una joya del cine que mezcla comedia, drama y la historia moderna de EE. UU. a través de un personaje único.",
    descripcion: "Un hombre bondadoso con un coeficiente intelectual bajo relata su vida extraordinaria y sus encuentros con figuras históricas.",
    recomendacion: "Una de las películas más queridas de la historia. Ineludible.",
    detalles: "Ganadora de 6 Premios de la Academia, incluyendo Mejor Película y Mejor Actor (Tom Hanks).",
    duracion: "2h 22min",
  },
  {
    id: 17,
    titulo: "Narnia",
    anio: 2005,
    genero: "Fantasía / Aventura",
    categoria: "Basadas en Libros",
    imagen: "https://m.media-amazon.com/images/M/MV5BMTc0NTUwMTU5OV5BMl5BanBnXkFtZTcwNjAwNzQzMw@@._V1_.jpg",
    rangoEdad: "+7",
    autor: "C.S. Lewis (Libro)",
    reseña: "Una aventura clásica de fantasía con efectos especiales impresionantes y una historia atemporal.",
    descripcion: "Cuatro hermanos son evacuados a una casa de campo y descubren un mundo mágico a través de un armario.",
    recomendacion: "Perfecta para ver en familia. Si te gustó Harry Potter, te gustará Narnia.",
    detalles: "Basada en el libro 'El León, la Bruja y el Armario'.",
    duracion: "2h 23min",
  },
  {
    id: 18,
    titulo: "Dune",
    anio: 2021,
    genero: "Ciencia Ficción / Épico",
    categoria: "Basadas en Libros",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoXWHE3oXlJSM7f3vj1I_EQN7N9zCqf_P78L2ZWHgevIH3EW52jXNst0W5iCweH0zPRCM&usqp=CAU",
    rangoEdad: "+13",
    autor: "Frank Herbert (Libro)",
    reseña: "Una adaptación majestuosa y visualmente impresionante que logra capturar la escala y la complejidad de la novela.",
    descripcion: "Un joven debe viajar al planeta más peligroso del universo para asegurar el futuro de su familia y su pueblo.",
    recomendacion: "Cine de ciencia ficción de gran presupuesto que debe verse en la pantalla más grande posible.",
    detalles: "Dirigida por Denis Villeneuve. Ganadora de 6 Oscars técnicos.",
    duracion: "2h 35min",
  },
  {
    id: 19,
    titulo: "La chica del tren",
    anio: 2016,
    genero: "Thriller / Drama",
    categoria: "Basadas en Libros",
    imagen: "https://es.web.img3.acsta.net/pictures/16/08/02/09/49/298907.jpg",
    rangoEdad: "+16",
    autor: "Paula Hawkins (Libro)",
    reseña: "Un thriller psicológico tenso con una protagonista compleja y una narrativa poco fiable.",
    descripcion: "Una mujer alcohólica se involucra en un caso de personas desaparecidas tras ver algo perturbador desde el tren.",
    recomendacion: "Si disfrutas de thrillers con misterios y giros inesperados.",
    detalles: "Protagonizada por Emily Blunt. Adaptación del best-seller de 2015.",
    duracion: "1h 52min",
  },
  {
    id: 20,
    titulo: "El gran Gatsby",
    anio: 2013,
    genero: "Drama / Romance",
    categoria: "Basadas en Libros",
    imagen: "https://es.web.img3.acsta.net/pictures/14/06/04/13/09/206777.jpg",
    rangoEdad: "+13",
    autor: "F. Scott Fitzgerald (Libro)",
    reseña: "Una visión extravagante y moderna de la 'Era del Jazz', con un diseño de producción deslumbrante.",
    descripcion: "Un aspirante a escritor es atraído al mundo del misterioso millonario Jay Gatsby en Long Island.",
    recomendacion: "Visualmente espectacular. Combina drama, romance y una crítica a la riqueza.",
    detalles: "Dirigida por Baz Luhrmann. Protagonizada por Leonardo DiCaprio.",
    duracion: "2h 23min",
  },

  // ===============================
  // 🔥 TOP 10 DE 2025 (PREVISIONES)
  // ===============================
  {
    id: 21,
    titulo: "Cómo entrenar a tu dragón",
    anio: 2025,
    genero: "Animación / Aventura",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/S/pv-target-images/d6c3d19442144f7678ae5a96a91b6b8759dbb2404b889e2470cafceacbc11438.jpg",
    rangoEdad: "Apta para todos",
    autor: "Dean DeBlois (Director Original)",
    reseña: "La versión *live-action* de una de las sagas animadas más queridas, con potencial para ser un éxito de fantasía.",
    descripcion: "La historia de Hipo y su dragón Chimuelo, en su paso a la edad adulta y la defensa de su comunidad. (Live-Action)",
    recomendacion: "Para los que crecieron con la trilogía original. Gran potencial épico.",
    detalles: "Adaptación *live-action* del éxito de Dreamworks. Dirigida por Dean DeBlois.",
    duracion: "Tiempo estimado: 2h 10min",
  },
  {
    id: 22,
    titulo: "Superman",
    anio: 2025,
    genero: "Acción / Superhéroes",
    categoria: "Top 10",
    imagen: "https://i.ebayimg.com/00/s/MTYwMFgxMDY2/z/GU0AAOSw-6RoXMdt/$_57.JPG?set_id=880000500F",
    rangoEdad: "+13",
    autor: "DC Comics",
    reseña: "El inicio de una nueva era para el Hombre de Acero, prometiendo un enfoque más esperanzador y clásico.",
    descripcion: "Clark Kent equilibra su vida como periodista en Metrópolis con su papel de protector del mundo, Superman.",
    recomendacion: "La película que definirá el futuro del Universo DC. Alta expectación.",
    detalles: "Dirigida por James Gunn. Parte del nuevo DC Universe (DCU).",
    duracion: "Tiempo estimado: 2h 30min",
  },
  {
    id: 23,
    titulo: "La Hora De La Desaparición",
    anio: 2025,
    genero: "Suspenso / Misterio",
    categoria: "Top 10",
    imagen: "https://www.cinestar.com.pe/bucket/images/cine/e4b5c078-a175-4875-aaab-57dafe7c9dae.png/w=250",
    rangoEdad: "+16",
    autor: "Guion Original",
    reseña: "Un thriller con una premisa intrigante que promete mantener al espectador al borde del asiento.",
    descripcion: "Un detective debe resolver la misteriosa desaparición masiva de personas en un pueblo aislado.",
    recomendacion: "Para fans de las películas de misterio con giros oscuros.",
    detalles: "Película original con un elenco de alto perfil.",
    duracion: "Tiempo estimado: 1h 55min",
  },
  {
    id: 24,
    titulo: "Caught Stealing",
    anio: 2025,
    genero: "Acción / Crimen",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/M/MV5BZjc3Y2I0M2YtZDY5NS00MGU5LWI5ZTEtOGNhMTZiZWFkMTljXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+18",
    autor: "Charlie Huston (Libro)",
    reseña: "Una adaptación de novela *noir* con un estilo visual crudo y mucha adrenalina.",
    descripcion: "Un exjugador de béisbol de mala suerte se ve envuelto en un violento conflicto en la ciudad de Nueva York.",
    recomendacion: "Un thriller de crimen para adultos, con tintes de humor negro.",
    detalles: "Dirigida por Darren Aronofsky. Adaptación de la novela de Charlie Huston.",
    duracion: "Tiempo estimado: 2h 05min",
  },
  {
    id: 25,
    titulo: "Thunderbolts",
    anio: 2025,
    genero: "Acción / Marvel",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/M/MV5BYWE2NmNmYTItZGY0ZC00MmY2LTk1NDAtMGUyMGEzMjcxNWM0XkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Marvel Comics",
    reseña: "El equipo de antihéroes de Marvel. Promete acción intensa y dilemas morales complejos.",
    descripcion: "Un grupo de villanos y antihéroes es reunido por el gobierno para misiones secretas de alto riesgo.",
    recomendacion: "Imperdible para los seguidores del Universo Cinematográfico de Marvel.",
    detalles: "Protagonizada por personajes ya conocidos del UCM, como Yelena Belova y Bucky Barnes.",
    duracion: "Tiempo estimado: 2h 15min",
  },
  {
    id: 26,
    titulo: "Los 4 fantásticos: primeros pasos",
    anio: 2025,
    genero: "Superhéroes / Ciencia Ficción",
    categoria: "Top 10",
    imagen: "https://pics.filmaffinity.com/Los_4_Fantaasticos_Primeros_pasos-284761648-large.jpg",
    rangoEdad: "+13",
    autor: "Marvel Comics",
    reseña: "El tan esperado debut de la 'Primera Familia' de Marvel en el UCM, con un enfoque fresco y aventurero.",
    descripcion: "Cuatro astronautas obtienen superpoderes después de una misión espacial y deben aprender a usarlos para proteger al mundo.",
    recomendacion: "Gran potencial para ser la película de superhéroes del año.",
    detalles: "Se espera que tenga un tono más enfocado en la ciencia y la aventura espacial.",
    duracion: "Tiempo estimado: 2h 18min",
  },
  {
    id: 27,
    titulo: "Misión: Imposible - Sentencia final",
    anio: 2025,
    genero: "Acción / Espionaje",
    categoria: "Top 10",
    imagen: "https://m.media-amazon.com/images/M/MV5BZTg0YzRkNDMtZTJjZS00Mjk0LTgwNGQtZWIzMTM3ZDRmZTQwXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Guion Original",
    reseña: "Ethan Hunt vuelve con acrobacias más locas y un espionaje de alto calibre. Puro entretenimiento de acción.",
    descripcion: "El agente Ethan Hunt y su equipo se enfrentan a una amenaza global que pone en peligro a toda la humanidad.",
    recomendacion: "Acción trepidante. Ideal para amantes de los *blockbusters* con efectos prácticos.",
    detalles: "La continuación directa de la primera parte de 'Sentencia Final'. Protagonizada por Tom Cruise.",
    duracion: "Tiempo estimado: 2h 40min",
  },
  {
    id: 28,
    titulo: "Blade",
    anio: 2025,
    genero: "Acción / Terror",
    categoria: "Top 10",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTe54HuJNspuNkUmcp-SyuK7UbUlOJ4hEFJQ&s",
    rangoEdad: "+16",
    autor: "Marvel Comics",
    reseña: "El cazavampiros de Marvel regresa con una promesa de terror y acción más adulta en el UCM.",
    descripcion: "Un 'caminante diurno' mitad humano, mitad vampiro, lucha para proteger a la humanidad de las criaturas de la noche.",
    recomendacion: "Si buscas una película de superhéroes con un toque de terror gótico.",
    detalles: "Protagonizada por Mahershala Ali. Se espera que explore el lado oscuro de Marvel.",
    duracion: "Tiempo estimado: 1h 58min",
  },
  {
  id: 34,
  titulo: "Ballerina",
  anio: 2025,
  genero: "Acción / Thriller",
  categoria: "Top 10",
  imagen: "https://m.media-amazon.com/images/M/MV5BNzdhZmY2OTQtYWI4OC00ZThkLTlhZjAtNzE2YzRjM2Q5YjJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",  // reemplaza por la portada oficial
  rangoEdad: "+16",
  autor: "Dir. Len Wiseman",
  reseña: "Un spin-off explosivo de la saga del asesino solitario que redefine los límites del cine de acción moderno.",
  descripcion: "En ‘Ballerina’, ambientada entre los eventos de la saga principal de John Wick, sigue a Eve Macarro, una joven bailarina que se ve arrastrada al mundo letal del crimen organizado cuando su padre es brutalmente asesinado por una red internacional de asesinos a sueldo. Prometida a una vida de disciplina artística, descubre que su verdadero entrenamiento comenzará cuando la venganza se convierta en su única forma de expresarse. Con la ayuda de un misterioso mentor, Eve cultiva habilidades mortales entre pasos de ballet y combates clandestinos, penetrando en los bajos fondos de Praga y Budapest donde la codicia, la traición y el poder convergen en un ballet mortal. A medida que se adentra más en esa oscura coreografía de muerte, se enfrenta a dilemas morales: ¿hasta dónde puede llegar alguien en nombre del amor filial? ¿Puede la belleza coexistir con la brutalidad del combate? Con secuencias de acción coreografiadas como piezas de danza, cámaras que giran en 360° y un clímax que fusiona la serenidad del escenario con el caos del enfrentamiento, la película ofrece tanto intensidad como reflexión. La aparición del icónico personaje de Keanu Reeves le imprime un sello emocional, conectando el nuevo relato con la mitología original de John Wick.}",
  recomendacion: "Perfecta para los fanáticos del cine de acción estilizado que no temen ver belleza y brutalidad en la misma escena.",
  detalles: "Estrenada el 6 de junio de 2025 en EE.UU., con reparto liderado por Ana de Armas, Norman Reedus y Lance Reddick (en su última aparición). Basada en el universo de la saga John Wick. :contentReference[oaicite:6]{index=6}",
  duracion: "Tiempo estimado: 2h 5min",
},
  {
    id: 30,
    titulo: "F1",
    anio: 2025,
    genero: "Acción / Deporte",
    categoria: "Top 10",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSMR_rBMZBVN6jJ4swPvcSlRqVYjl19riN9Ew&s",
    rangoEdad: "+13",
    autor: "Guion Original",
    reseña: "Una película que promete capturar la velocidad, el drama y la intensidad de la Fórmula 1.",
    descripcion: "Un expiloto de F1 regresa de su retiro para competir junto a un novato contra los mejores del mundo.",
    recomendacion: "Perfecta para los amantes del automovilismo y las películas de superación deportiva.",
    detalles: "Protagonizada por Brad Pitt y dirigida por Joseph Kosinski ('Top Gun: Maverick').",
    duracion: "Tiempo estimado: 2h 12min",
  },

  // ===============================
  // 🎬 KIDS
  // ===============================
  {
    id: 31,
    titulo: "Toy Story",
    anio: 1995,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://xl.movieposterdb.com/15_10/1995/114709/xl_114709_70786505.jpg",
    rangoEdad: "Apta para todos",
    autor: "John Lasseter (Director)",
    reseña: "Un clásico atemporal de Pixar que celebra la amistad, la lealtad y el poder de la imaginación.",
    descripcion: "Los juguetes de un niño cobran vida y deben enfrentar la llegada de un nuevo juguete que amenaza su orden.",
    recomendacion: "Una película obligatoria para todas las edades. Divertida, emotiva e innovadora.",
    detalles: "La primera película de Pixar realizada completamente por ordenador. Un hito en la animación.",
    duracion: "1h 21min",
  },
  {
    id: 32,
    titulo: "Buscando a Nemo",
    anio: 2003,
    genero: "Animación / Familiar",
    categoria: "Kids",
    imagen: "https://images.cdn3.buscalibre.com/fit-in/360x360/9e/7d/9e7d0d7d4254b88e2ffad7245672b32a.jpg",
    rangoEdad: "Apta para todos",
    autor: "Andrew Stanton (Director)",
    reseña: "Una aventura acuática inolvidable que habla sobre la sobreprotección y el valor de soltar.",
    descripcion: "Un pez payaso sobreprotector viaja por el océano para encontrar a su hijo, que ha sido capturado.",
    recomendacion: "Un clásico moderno de Pixar. Visualmente hermoso y con mucho humor.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación.",
    duracion: "1h 40min",
  },
  {
    id: 33,
    titulo: "Shrek",
    anio: 2001,
    genero: "Animación / Comedia",
    categoria: "Kids",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJYba3ne5xgEyCp1b-Jno526rKBljRLgg0jFx4Fj-CInGGaxrUCI0gEGOkNt7qmt2ESm0&usqp=CAU",
    rangoEdad: "Apta para todos",
    autor: "Andrew Adamson y Vicky Jenson (Directores)",
    reseña: "Una parodia inteligente de los cuentos de hadas que se convirtió en un éxito instantáneo.",
    descripcion: "Un ogro cascarrabias es enviado a rescatar a una princesa para recuperar su pantano.",
    recomendacion: "Humor para adultos y niños. Muy recomendable.",
    detalles: "Primera película en ganar el Oscar a Mejor Película de Animación (categoría recién creada).",
    duracion: "1h 30min",
  },
  {
    id: 34,
    titulo: "Frozen",
    anio: 2013,
    genero: "Animación / Musical",
    categoria: "Kids",
    imagen: "https://cdn.shopify.com/s/files/1/0398/4202/1535/files/oRmfdrPmK85jCMDRCp9U2Q96sfq2HhhFl_LnqsraFlA_30b2a58c-bb9d-4c54-aff5-f6d7ca5c33e5_300x.png?v=1755166298",
    rangoEdad: "Apta para todos",
    autor: "Chris Buck y Jennifer Lee (Directores)",
    reseña: "El fenómeno de Disney que redefinió la narrativa de princesas, centrándose en el amor fraternal.",
    descripcion: "Una princesa debe encontrar a su hermana con poderes de hielo para salvar su reino de un invierno eterno.",
    recomendacion: "Sus canciones son un éxito mundial. Imprescindible en Disney.",
    detalles: "Basada vagamente en el cuento de 'La Reina de las Nieves'. Ganó 2 Oscars.",
    duracion: "1h 42min",
  },
  {
    id: 35,
    titulo: "Kung Fu Panda",
    anio: 2008,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://images.justwatch.com/poster/312538889/s718/kung-fu-panda.jpg",
    rangoEdad: "Apta para todos",
    autor: "Mark Osborne y John Stevenson (Directores)",
    reseña: "Divertida y con un gran mensaje de superación, mezclando acción de artes marciales con comedia.",
    descripcion: "Un torpe panda que trabaja en el restaurante de fideos de su padre es elegido inesperadamente como el Guerrero Dragón.",
    recomendacion: "Excelente animación y peleas de artes marciales aptas para niños.",
    detalles: "Producida por Dreamworks Animation.",
    duracion: "1h 30min",
  },
  {
    id: 36,
    titulo: "Los Increíbles",
    anio: 2004,
    genero: "Animación / Superhéroes",
    categoria: "Kids",
    imagen: "https://es.web.img2.acsta.net/medias/nmedia/18/89/87/86/20070947.jpg",
    rangoEdad: "+7",
    autor: "Brad Bird (Director)",
    reseña: "Una película de superhéroes que funciona como una gran historia familiar y un thriller de acción.",
    descripcion: "Una familia de superhéroes intenta llevar una vida normal hasta que se ven obligados a salvar el mundo.",
    recomendacion: "Considerada una de las mejores películas de superhéroes de la historia, animada o no.",
    detalles: "Dirigida por Brad Bird, conocido por su trabajo en 'El gigante de hierro'.",
    duracion: "1h 55min",
  },
  {
    id: 37,
    titulo: "Coco",
    anio: 2017,
    genero: "Animación / Musical",
    categoria: "Kids",
    imagen: "https://lumiere-a.akamaihd.net/v1/images/p_coco_19736_fd5fa537.jpeg?region=0,0,540,810",
    rangoEdad: "Apta para todos",
    autor: "Lee Unkrich (Director)",
    reseña: "Una celebración visual y emocional de la cultura mexicana, la familia y el Día de Muertos.",
    descripcion: "Un joven con sueños de ser músico viaja accidentalmente a la Tierra de los Muertos.",
    recomendacion: "Una de las películas más emotivas de Pixar. Hermosa y culturalmente rica.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación y Mejor Canción Original.",
    duracion: "1h 45min",
  },
  {
    id: 38,
    titulo: "Encanto",
    anio: 2021,
    genero: "Animación / Musical",
    categoria: "Kids",
    imagen: "https://lumiere-a.akamaihd.net/v1/images/encanto_ka_las_pay1_92ad7410.jpeg?region=0%2C0%2C1080%2C1350",
    rangoEdad: "Apta para todos",
    autor: "Byron Howard y Jared Bush (Directores)",
    reseña: "Una explosión de color y música inspirada en la cultura colombiana, con un fuerte mensaje sobre el legado familiar.",
    descripcion: "Una joven es la única de su familia que no tiene un don mágico, pero debe salvar la magia de su casa.",
    recomendacion: "Un éxito de Disney con canciones pegadizas y un enfoque moderno en la dinámica familiar.",
    detalles: "La banda sonora incluye canciones de Lin-Manuel Miranda.",
    duracion: "1h 42min",
  },
  {
    id: 39,
    titulo: "Ratatouille",
    anio: 2007,
    genero: "Animación / Comedia",
    categoria: "Kids",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLdN29MakwxGl8AQ0HuwkLIxaFASaSB72H9w&s",
    rangoEdad: "Apta para todos",
    autor: "Brad Bird (Director)",
    reseña: "Una comedia encantadora que demuestra que cualquiera puede lograr sus sueños, incluso una rata chef.",
    descripcion: "Una rata con un gusto refinado por la comida se asocia con un joven ayudante de cocina en París.",
    recomendacion: "Visualmente exquisita y un deleite para los amantes de la gastronomía.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación.",
    duracion: "1h 51min",
  },
  {
    id: 40,
    titulo: "Monsters Inc",
    anio: 2001,
    genero: "Animación / Fantasía",
    categoria: "Kids",
    imagen: "https://upload.wikimedia.org/wikipedia/en/6/63/Monsters_Inc.JPG",
    rangoEdad: "Apta para todos",
    autor: "Pete Docter (Director)",
    reseña: "Una idea original y divertida que convierte a los monstruos del armario en personajes adorables.",
    descripcion: "Dos monstruos que trabajan asustando niños descubren que la risa es una fuente de energía más poderosa que el miedo.",
    recomendacion: "Una de las películas más tiernas y divertidas de Pixar.",
    detalles: "Nominada a 4 Oscars, ganando el de Mejor Canción Original.",
    duracion: "1h 32min",
  },
  {
    id: 41,
    titulo: "Zootopia",
    anio: 2016,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://lumiere-a.akamaihd.net/v1/images/movie_poster_zootopia_866a1bf2.jpeg?region=0%2C0%2C300%2C450",
    rangoEdad: "Apta para todos",
    autor: "Byron Howard y Rich Moore (Directores)",
    reseña: "Una aventura de detectives con un mensaje social sutil y relevante para todas las edades.",
    descripcion: "Una conejita policía se une a un zorro estafador para resolver un caso de desapariciones en la gran ciudad.",
    recomendacion: "Inteligente, divertida y con una gran animación. Ganadora del Oscar.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación.",
    duracion: "1h 48min",
  },
  {
    id: 42,
    titulo: "Moana",
    anio: 2016,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://i.pinimg.com/474x/e0/ae/48/e0ae489f31577f6c185ee9b13f39582c.jpg",
    rangoEdad: "Apta para todos",
    autor: "Ron Clements y John Musker (Directores)",
    reseña: "Una aventura marítima llena de mitología polinesia, personajes fuertes y canciones inolvidables.",
    descripcion: "Una valiente joven se aventura en el océano para salvar a su pueblo con la ayuda del semidiós Maui.",
    recomendacion: "Perfecta para los fans de las historias de heroínas y la aventura en el mar.",
    detalles: "Canciones de Lin-Manuel Miranda. Un éxito de crítica y público.",
    duracion: "1h 47min",
  },
  {
    id: 43,
    titulo: "Intensamente",
    anio: 2015,
    genero: "Animación / Emocional",
    categoria: "Kids",
    imagen: "https://mx.web.img3.acsta.net/pictures/17/08/07/21/43/466493.jpg",
    rangoEdad: "Apta para todos",
    autor: "Pete Docter (Director)",
    reseña: "Una obra maestra conceptual que explica la complejidad de las emociones humanas de forma sencilla y profunda.",
    descripcion: "Las emociones de una niña pequeña (Alegría, Tristeza, Miedo, etc.) luchan por guiarla a través de un cambio de vida.",
    recomendacion: "Una película esencial para niños y adultos. Educativa y muy conmovedora.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación.",
    duracion: "1h 35min",
  },
  {
    id: 44,
    titulo: "Luca",
    anio: 2021,
    genero: "Animación / Amistad",
    categoria: "Kids",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQl2B5oqGa40uuvMiA8rNF-PlsjWg2DfR3DRtVXsa6RCjRbBsUIRHmiSi2ua5yq5OxdPB8&usqp=CAU",
    rangoEdad: "Apta para todos",
    autor: "Enrico Casarosa (Director)",
    reseña: "Una carta de amor a la amistad, la aceptación y la cultura italiana, con un toque de fantasía veraniega.",
    descripcion: "Dos monstruos marinos adolescentes exploran el mundo humano en un pueblo costero de Italia.",
    recomendacion: "Una película cálida y encantadora sobre el valor de ser diferente.",
    detalles: "Ambientada en la Riviera Italiana. Un enfoque visual único y colorido.",
    duracion: "1h 35min",
  },
  {
    id: 45,
    titulo: "Up",
    pais: "Estados Unidos",
    anio: 2009,
    genero: "Animación / Aventura",
    categoria: "Kids",
    imagen: "https://www.funeralnatural.net/sites/default/files/pelicula/imagen/upcartel.jpg",
    rangoEdad: "Apta para todos",
    autor: "Pete Docter (Director)",
    reseña: "Una montaña rusa emocional. Su inicio es uno de los segmentos más aclamados en la historia de la animación.",
    descripcion: "Un anciano viudo cumple su sueño de atar miles de globos a su casa y volar a Sudamérica, con un joven polizón.",
    recomendacion: "No te dejes engañar por los globos, es una película profundamente adulta y conmovedora.",
    detalles: "Ganadora de 2 Oscars. Nombrada a Mejor Película, un honor raro para la animación.",
    duracion: "1h 36min",
  },
  {
    id: 46,
    titulo: "La Sirenita",
    anio: 2023,
    genero: "Musical / Fantasía",
    categoria: "Kids",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyrAAhriSRmnPNElfM4_OLBos6XwgYucYcHQ&s",
    rangoEdad: "+7",
    autor: "Rob Marshall (Director)",
    reseña: "La versión *live-action* del clásico de Disney, con nuevas canciones y efectos visuales impresionantes.",
    descripcion: "Una joven sirena sueña con experimentar el mundo humano y hace un trato peligroso con una bruja marina.",
    recomendacion: "Para revivir el clásico con una perspectiva moderna y una gran actuación vocal.",
    detalles: "Adaptación *live-action* del clásico animado de 1989.",
    duracion: "2h 15min",
  },
  {
    id: 47,
    titulo: "Mi villano favorito",
    anio: 2010,
    genero: "Animación / Comedia",
    categoria: "Kids",
    imagen: "https://pics.filmaffinity.com/Gru_mi_villano_favorito-506947321-large.jpg",
    rangoEdad: "Apta para todos",
    autor: "Pierre Coffin y Chris Renaud (Directores)",
    reseña: "Presentó al mundo a los adorables Minions en una divertida historia sobre el descubrimiento de la paternidad.",
    descripcion: "Un supervillano planea robar la Luna, pero su plan se ve interrumpido por tres niñas huérfanas.",
    recomendacion: "Comedia animada ligera y muy divertida, especialmente por los Minions.",
    detalles: "La película que inició la exitosa franquicia de los Minions.",
    duracion: "1h 35min",
  },
  {
    id: 48,
    titulo: "Sing",
    anio: 2016,
    genero: "Animación / Musical",
    categoria: "Kids",
    imagen: "https://play-lh.googleusercontent.com/4bW-B4vqtJtLzn_pvfZeVWYrmoWeMPDBgaW8kLKt3x1qbjEX9mBHR4zfdQelkrvHGZ2H=w240-h480-rw",
    rangoEdad: "Apta para todos",
    autor: "Garth Jennings (Director)",
    reseña: "Una celebración de la música con personajes animales y una banda sonora llena de éxitos.",
    descripcion: "Un koala organiza un concurso de canto para salvar su teatro de la ruina financiera.",
    recomendacion: "Mucha música y diversión. Ideal para una tarde familiar y animada.",
    detalles: "Producida por Illumination Entertainment.",
    duracion: "1h 48min",
  },
  {
    id: 49,
    titulo: "Pinocho",
    anio: 2022,
    genero: "Animación / Fantasía",
    categoria: "Kids",
    imagen: "https://i.pinimg.com/564x/5e/b4/e4/5eb4e4e89a1f7d0a556a5e266d868621.jpg",
    rangoEdad: "+13",
    autor: "Guillermo del Toro (Director)",
    reseña: "Una reinterpretación oscura, visualmente deslumbrante y profundamente emotiva del cuento clásico.",
    descripcion: "Una versión en *stop-motion* del clásico de la marioneta que cobra vida, ambientada en la Italia fascista.",
    recomendacion: "Si buscas una animación artística, adulta y con un mensaje político y emocional profundo.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación. Obra maestra de *stop-motion*.",
    duracion: "1h 56min",
  },

  // ===============================
  // 🎥 DOCUMENTALES
  // ===============================
  {
  id: 50,
  titulo: "Nuestro Planeta",
  anio: 2019,
  genero: "Naturaleza / Ciencia",
  categoria: "Documentales",
  imagen: "https://www.lavanguardia.com/peliculas-series/images/serie/poster/2019/4/w1280/aV05lTbDLzeA1qkZxd4AJKUJ6mN.jpg",
  rangoEdad: "Apta para todos",
  autor: "Alastair Fothergill (Director)",
  reseña: "Una obra maestra visual que combina la belleza majestuosa del mundo natural con un mensaje urgente sobre la conservación. Cada episodio es una invitación a reflexionar sobre la interconexión entre las especies y el impacto humano en la Tierra.",
  descripcion: "Esta serie documental nos transporta a los hábitats más asombrosos del planeta: desde las selvas tropicales llenas de vida hasta los desiertos más áridos, pasando por los océanos y las tundras heladas. Con imágenes de una calidad cinematográfica impresionante y narración del legendario David Attenborough, 'Nuestro Planeta' no solo celebra la diversidad del mundo natural, sino que también denuncia la pérdida acelerada de ecosistemas provocada por la actividad humana. A lo largo de sus episodios, combina asombro visual con un mensaje profundo sobre la urgencia de proteger la vida que nos rodea.",
  recomendacion: "Imprescindible por su cinematografía, su emotiva narrativa y su poderoso mensaje ecológico.",
  detalles: "Narrado por David Attenborough y producido por Netflix en colaboración con WWF. Filmado en más de 50 países a lo largo de cuatro años, con tecnología 4K. Ganador de múltiples premios Emmy.",
  duracion: "Serie, 8 episodios"
},
{
  id: 51,
  titulo: "Blackfish",
  anio: 2013,
  genero: "Animales / Denuncia",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BNzkzYmRmYTMtMTE5OS00NWYyLTg5MzgtOGM3ZjE1N2MwMTJlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "Gabriela Cowperthwaite (Directora)",
  reseña: "Impactante, valiente y profundamente emocional. ‘Blackfish’ cambió para siempre la forma en que el público percibe el entretenimiento con animales marinos, revelando una verdad dolorosa detrás de los espectáculos de orcas.",
  descripcion: "El documental sigue la historia de Tilikum, una orca en cautiverio involucrada en la muerte de varias personas, y expone las prácticas de la industria del entretenimiento marino. A través de entrevistas con exentrenadores, científicos y expertos en comportamiento animal, ‘Blackfish’ revela el sufrimiento físico y psicológico de las orcas encerradas en parques acuáticos. Más allá del caso de Tilikum, la película es una crítica feroz a la explotación animal y un llamado global a la empatía y la conciencia ambiental. Su lanzamiento generó un movimiento internacional que transformó la industria de los parques temáticos.",
  recomendacion: "Un documental de denuncia que te hará replantearte los parques acuáticos y la relación del ser humano con los animales.",
  detalles: "Tuvo un enorme impacto social y mediático, reduciendo significativamente la popularidad de SeaWorld. Nominado a múltiples premios internacionales y considerado uno de los documentales más influyentes de la década.",
  duracion: "1h 23min"
},
{
  id: 52,
  titulo: "The Social Dilemma",
  anio: 2020,
  genero: "Tecnología / Sociedad",
  categoria: "Documentales",
  imagen: "https://pics.filmaffinity.com/the_social_dilemma-384147385-large.jpg",
  rangoEdad: "+16",
  autor: "Jeff Orlowski (Director)",
  reseña: "Una mirada inquietante a la era digital. Combina testimonios reales y dramatizaciones para mostrar cómo las redes sociales moldean nuestros pensamientos, emociones y comportamientos.",
  descripcion: "A través de entrevistas con exejecutivos y diseñadores de grandes empresas tecnológicas como Google, Facebook y Twitter, ‘The Social Dilemma’ explora cómo los algoritmos están diseñados para manipular la atención humana. El documental analiza los efectos psicológicos, sociales y políticos de vivir en un mundo dominado por las redes, desde la polarización social hasta la adicción a los dispositivos. Con una narrativa ágil e impactante, plantea una pregunta esencial: ¿quién controla realmente la información que consumimos y cómo afecta nuestra libertad individual?",
  recomendacion: "Si usas redes sociales, este documental es una experiencia reveladora que te hará ver el mundo digital desde otra perspectiva.",
  detalles: "Producido por Netflix. Incluye dramatizaciones protagonizadas por Skyler Gisondo. Ganador del premio Emmy al Mejor Documental de Impacto Social.",
  duracion: "1h 34min"
},
{
  id: 53,
  titulo: "Seaspiracy",
  anio: 2021,
  genero: "Océanos / Ecología",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BOWUzZDNjZTEtZDM1Mi00ODVkLWI4Y2UtYjAwZGVlM2YwNTg4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+16",
  autor: "Ali Tabrizi (Director)",
  reseña: "Provocador, revelador y sumamente polémico. ‘Seaspiracy’ desafía todo lo que creías saber sobre la pesca y el consumo de productos marinos.",
  descripcion: "El joven cineasta Ali Tabrizi se embarca en una investigación personal que lo lleva a descubrir la devastadora realidad oculta detrás de la industria pesquera global. Desde la contaminación plástica hasta la sobrepesca masiva, el documental desenmascara cómo las grandes corporaciones y los gobiernos contribuyen a la destrucción de los ecosistemas marinos. Con imágenes crudas, entrevistas reveladoras y un tono de denuncia, ‘Seaspiracy’ pone en evidencia las contradicciones del activismo ambiental moderno y plantea una pregunta incómoda: ¿es posible consumir pescado de manera sostenible?",
  recomendacion: "Un llamado urgente a repensar nuestros hábitos alimenticios y la salud de los océanos. Perfecto para quienes buscan documentales de impacto.",
  detalles: "Producción de Netflix respaldada por Kip Andersen, creador de ‘Cowspiracy’. Generó gran debate en redes sociales y medios ambientales por sus contundentes afirmaciones.",
  duracion: "1h 29min"
},
{
  id: 54,
  titulo: "The Tinder Swindler",
  anio: 2022,
  genero: "Crimen / Real",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BNTQ5YzM2YzQtNGY0ZS00ZjUyLThmN2YtYzlmNTEzMmQ0YzgyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+16",
  autor: "Felicity Morris (Directora)",
  reseña: "Una historia real tan increíble que parece salida de una película de suspenso. ‘The Tinder Swindler’ combina el ritmo del *true crime* con la emoción del drama humano.",
  descripcion: "A través de testimonios de mujeres de diferentes países, este documental reconstruye la historia de un hombre que utilizó la aplicación de citas Tinder para seducir, manipular y estafar a sus víctimas, haciéndose pasar por un empresario millonario. Con un montaje ágil y giros sorprendentes, la película revela el poder de la manipulación emocional y las trampas del mundo digital. Más allá del engaño, muestra la valentía de las víctimas al unirse para desenmascarar la verdad y exponer una red de mentiras que se extendió por toda Europa.",
  recomendacion: "Si te gustan las historias de crímenes reales y el suspenso psicológico, este documental te mantendrá atrapado de principio a fin.",
  detalles: "Dirigido por Felicity Morris y producido por los creadores de ‘Don’t F**k With Cats’. Se convirtió en uno de los documentales más vistos de Netflix en su estreno, inspirando incluso memes y debates globales sobre seguridad en citas online.",
  duracion: "1h 54min"
},
{
  id: 55,
  titulo: "13th",
  anio: 2016,
  genero: "Sociedad / Política",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMjAwMjU5NTAzOF5BMl5BanBnXkFtZTgwMjQwODQxMDI@._V1_.jpg",
  rangoEdad: "+16",
  autor: "Ava DuVernay (Directora)",
  reseña: "Poderoso, esclarecedor y profundamente necesario. '13th' expone con rigor histórico y emocional la continuidad entre la esclavitud y el encarcelamiento masivo en Estados Unidos.",
  descripcion: "El documental toma su título de la Decimotercera Enmienda de la Constitución de los EE. UU., que abolió la esclavitud salvo como castigo por un crimen. A partir de ese punto, Ava DuVernay construye un relato estremecedor sobre cómo el sistema judicial y carcelario estadounidense perpetúa la discriminación racial bajo nuevas formas. Mediante imágenes de archivo, entrevistas con activistas, académicos y políticos, '13th' ofrece una visión integral del racismo estructural y el poder de las corporaciones privadas detrás del negocio penitenciario. Es una clase magistral de historia, política y humanidad.",
  recomendacion: "Una película vital para entender las raíces del racismo y la desigualdad en la sociedad moderna.",
  detalles: "Nominada al Oscar a Mejor Documental y ganadora del BAFTA. Dirigida por Ava DuVernay (‘Selma’). Distribuida por Netflix y reconocida por la ONU por su impacto social.",
  duracion: "1h 40min"
},
{
  id: 56,
  titulo: "David Attenborough: A Life on Our Planet",
  anio: 2020,
  genero: "Naturaleza / Reflexión",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BNzc0NzdhZWUtOTRjMi00ZjllLTgzOTItOTc4ZGI0NWU1NmJiXkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "Apta para todos",
  autor: "Alastair Fothergill, Jonnie Hughes (Directores)",
  reseña: "Una obra profundamente conmovedora. El legendario naturalista David Attenborough comparte su testamento personal sobre el estado del planeta y su visión de esperanza para el futuro.",
  descripcion: "En este documental íntimo y visualmente impresionante, Attenborough repasa más de 90 años de vida dedicados a explorar la naturaleza. Desde los primeros años de su carrera hasta el presente, observa con tristeza y sabiduría cómo la biodiversidad del planeta ha disminuido drásticamente. Pero no todo es desesperanza: Attenborough ofrece soluciones reales y un llamado urgente a revertir el daño. Su voz, serena pero contundente, guía un viaje emocional a través del tiempo y la conciencia ecológica.",
  recomendacion: "Esencial para cualquier amante de la naturaleza y defensor del medio ambiente.",
  detalles: "Producido por Silverback Films y Netflix. Considerado el 'testimonio' ambiental de Attenborough. Ganador del Emmy al Mejor Documental de Naturaleza.",
  duracion: "1h 23min"
},
{
  id: 57,
  titulo: "My Octopus Teacher",
  anio: 2020,
  genero: "Naturaleza / Vida Marina",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BYWU5OGMxYjktMWY5Ny00NDJhLTgwMDktNjVmMTExZGIyODljXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "Apta para todos",
  autor: "Pippa Ehrlich y James Reed (Directores)",
  reseña: "Tierno, poético y visualmente asombroso. Este documental muestra cómo una conexión inesperada entre un humano y un pulpo puede transformar la manera en que vemos la naturaleza.",
  descripcion: "El cineasta sudafricano Craig Foster, tras pasar por una etapa de agotamiento emocional, comienza a bucear diariamente en un bosque submarino frente a Ciudad del Cabo. Allí conoce a una hembra de pulpo común, con la que desarrolla una sorprendente relación de confianza y aprendizaje mutuo. A través de sus encuentros, Foster reflexiona sobre la inteligencia, la empatía y la interdependencia entre las especies. Filmado con una belleza hipnótica, ‘My Octopus Teacher’ es tanto una carta de amor al océano como una meditación sobre la conexión humana con la naturaleza.",
  recomendacion: "Ganador del Oscar a Mejor Documental. Ideal para quienes buscan inspiración, calma y belleza.",
  detalles: "Producido por Netflix y Sea Change Project. Rodado durante más de 300 días de buceo consecutivo.",
  duracion: "1h 25min"
},
{
  id: 58,
  titulo: "American Factory",
  anio: 2019,
  genero: "Trabajo / Sociedad",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BY2I1ZWJmNDUtMzc5OC00YzVmLTliZWItNTczZDQ0YTNiOTZjXkEyXkFqcGc@._V1_.jpg",
  rangoEdad: "+13",
  autor: "Steven Bognar y Julia Reichert (Directores)",
  reseña: "Una mirada fascinante a la globalización moderna. Muestra el choque cultural entre trabajadores estadounidenses y empresarios chinos en una misma fábrica.",
  descripcion: "Tras el cierre de una planta de General Motors en Ohio, una empresa china de vidrios automotrices compra las instalaciones y reabre la fábrica. El documental sigue a los trabajadores mientras intentan adaptarse a un nuevo modelo laboral, marcado por la disciplina asiática y la pérdida de las garantías americanas. ‘American Factory’ expone con humanidad los retos de la economía global: el trabajo, la identidad y la dignidad frente al avance tecnológico y la producción masiva.",
  recomendacion: "Un retrato honesto y necesario sobre los efectos de la globalización en la clase trabajadora.",
  detalles: "Primer documental producido por Higher Ground, la compañía de Barack y Michelle Obama. Ganador del Oscar a Mejor Documental en 2020.",
  duracion: "1h 50min"
},
{
  id: 59,
  titulo: "Crip Camp",
  anio: 2020,
  genero: "Derechos Humanos / Historia",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BYmI4ODAyMDctODU4My00MWFmLThiN2MtYTAwNWFiMzlhY2M5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "Nicole Newnham y James LeBrecht (Directores)",
  reseña: "Una historia poderosa y llena de esperanza. ‘Crip Camp’ celebra el espíritu revolucionario de un grupo de jóvenes con discapacidad que cambió la historia de los derechos civiles en EE. UU.",
  descripcion: "A principios de los años 70, un grupo de adolescentes asiste a un campamento de verano llamado Camp Jened, un espacio libre de prejuicios donde las personas con discapacidad podían sentirse plenamente aceptadas. Años más tarde, muchos de ellos se convierten en líderes del movimiento por los derechos de las personas con discapacidad. Combinando material de archivo vibrante con entrevistas actuales, ‘Crip Camp’ demuestra cómo un simple verano puede encender una revolución social.",
  recomendacion: "Inspirador y profundamente humano. Un recordatorio de que la inclusión es una lucha colectiva.",
  detalles: "Producido por Higher Ground Productions (Barack y Michelle Obama). Nominado al Oscar y ganador del premio del público en Sundance.",
  duracion: "1h 47min"
},
{
  id: 60,
  titulo: "The Deepest Breath",
  anio: 2023,
  genero: "Aventura / Océano",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMmY2YmUwZDMtNjRmNi00ODJhLTllZjYtYzk4ZDg3MTE4ZjA4XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "Laura McGann (Directora)",
  reseña: "Una experiencia intensa y emocional. Combina la belleza del océano con el riesgo mortal del buceo libre, en una historia de pasión, sacrificio y amor por el mar.",
  descripcion: "‘The Deepest Breath’ narra la historia paralela de Alessia Zecchini, una buceadora italiana de apnea, y Stephen Keenan, un buzo de seguridad irlandés. Unidos por su amor al océano, sus caminos se cruzan en la búsqueda de récords bajo el agua. Con imágenes impresionantes y una tensión constante, el documental explora los límites físicos y mentales del cuerpo humano, así como la conexión espiritual con el mar. Una oda visual a la libertad y al peligro.",
  recomendacion: "Ideal para amantes del océano, la adrenalina y las historias de superación extrema.",
  detalles: "Producción original de Netflix, con filmaciones en el Mar Rojo y entrevistas exclusivas. Aclamado en el Festival de Sundance 2023.",
  duracion: "1h 48min"
},
{
  id: 61,
  titulo: "Beckham",
  anio: 2023,
  genero: "Deporte / Biografía",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BZmNmZTU5ZTUtZTc0NS00ZWJlLWFlMzUtMDRmZDgzMDhjNmM0XkEyXkFqcGc@._V1_QL75_UX190_CR0,2,190,281_.jpg",
  rangoEdad: "+13",
  autor: "Fisher Stevens (Director)",
  reseña: "Un retrato íntimo y sincero del ícono mundial del fútbol. Muestra al David Beckham más humano: el deportista, el padre, el esposo y el símbolo cultural.",
  descripcion: "A lo largo de cuatro episodios, esta serie documental sigue la vida de David Beckham, desde sus humildes inicios en Londres hasta convertirse en una superestrella global. Con material de archivo inédito y entrevistas exclusivas, ‘Beckham’ ofrece una mirada equilibrada a su carrera deportiva, su relación con Victoria Beckham y los desafíos de vivir bajo el escrutinio público. Una historia de éxito, sacrificio y perseverancia.",
  recomendacion: "Perfecto para fans del fútbol y quienes disfrutan las biografías inspiradoras.",
  detalles: "Miniserie de 4 episodios producida por Netflix. Dirigida por Fisher Stevens (‘Before the Flood’). Filmada con la colaboración directa de la familia Beckham.",
  duracion: "4 episodios (aprox. 4 horas)"
},
{
  id: 62,
  titulo: "Arnold",
  anio: 2023,
  genero: "Biografía / Superación",
  categoria: "Documentales",
  imagen: "https://images.plex.tv/photo?size=medium-360&scale=1&url=https%3A%2F%2Fimage.tmdb.org%2Ft%2Fp%2Foriginal%2Fo9KmWrG9rbFhB7jWW4vFHTmqv28.jpg",
  rangoEdad: "+16",
  autor: "Lesley Chilcott (Directora)",
  reseña: "La historia definitiva de Arnold Schwarzenegger. Desde su juventud en Austria hasta su reinado en Hollywood y la política estadounidense.",
  descripcion: "‘Arnold’ es una miniserie documental que explora las tres etapas principales de la vida de Schwarzenegger: el atleta, el actor y el político. Con entrevistas sinceras, imágenes inéditas y reflexiones personales, el documental revela al hombre detrás del mito, mostrando sus ambiciones, fracasos y aprendizajes. Más que una biografía, es un retrato de la determinación y la reinvención constante.",
  recomendacion: "Inspiradora, llena de energía y carisma. Un homenaje a la perseverancia y la disciplina.",
  detalles: "Miniserie de 3 episodios dirigida por Lesley Chilcott. Estrenada en Netflix en 2023 con gran éxito global.",
  duracion: "3 episodios (aprox. 3 horas)"
},
{
  id: 63,
  titulo: "Billie Eilish: The World's a Little Blurry",
  anio: 2021,
  genero: "Música / Juventud",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMDk5NmI4NGMtYzk4MS00NDlhLTlkZGMtNzEzZTJiZjFkYjgyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+13",
  autor: "R.J. Cutler (Director)",
  reseña: "Íntimo, crudo y emocionalmente honesto. Una mirada sin filtros a la vida y el ascenso meteórico de Billie Eilish.",
  descripcion: "El documental sigue el proceso creativo de Billie Eilish mientras graba su álbum debut ‘When We All Fall Asleep, Where Do We Go?’. Entre giras, premios y desafíos personales, la película muestra a una artista joven enfrentando el peso de la fama y la salud mental en la era digital. Con escenas familiares y momentos musicales poderosos, ‘The World’s a Little Blurry’ es tanto un retrato generacional como una carta abierta a la autenticidad.",
  recomendacion: "Ideal para fans de la música contemporánea y para quienes buscan entender el precio del éxito a temprana edad.",
  detalles: "Documental original de Apple TV+, dirigido por R.J. Cutler. Nominado al Grammy y al Critics Choice Documentary Award.",
  duracion: "2h 20min"
},
{
  id: 64,
  titulo: "Taylor Swift: Miss Americana",
  anio: 2020,
  genero: "Música / Inspiración",
  categoria: "Documentales",
  imagen: "https://dnm.nflximg.net/api/v6/mAcAr9TxZIVbINe88xb3Teg5_OA/AAAABWPzJQNgdL4goIDJ5BmEOBaFIF0uNEvuw_Tsv0s2Ro22uXIZ6K0OWjnzOa0HROsVXT7hyQbJwB9uBLhOGvfq7ZLlJER7ukzoVLOqS9nNNk69rurLUqcL_RHHDwQh1r0OWWUyGg.jpg?r=837",
  rangoEdad: "+13",
  autor: "Lana Wilson (Directora)",
  reseña: "Sincero y revelador. ‘Miss Americana’ muestra a Taylor Swift en su faceta más humana: vulnerable, decidida y en constante evolución.",
  descripcion: "Taylor Swift abre las puertas de su vida privada y profesional en este documental íntimo que recorre su carrera desde los inicios hasta su transformación en una voz política y feminista. A través de momentos personales, grabaciones de estudio y reflexiones honestas, la cantante revela las presiones de la industria musical y su lucha por el control artístico. Es un retrato del crecimiento personal y del poder de usar la fama para generar cambio.",
  recomendacion: "Una mirada inspiradora al camino de una de las artistas más influyentes del siglo XXI.",
  detalles: "Producción original de Netflix. Estrenada en el Festival de Sundance. Dirigida por Lana Wilson (‘After Tiller’).",
  duracion: "1h 25min"
},
{
  id: 65,
  titulo: "Planet Earth II",
  anio: 2016,
  genero: "Naturaleza / Mundo",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMzY4NDBkMWYtYzdkYy00YzBjLWJmODctMWM4YjYzZTdjNWE5XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "Apta para todos",
  autor: "David Attenborough (Narrador)",
  reseña: "Una experiencia visual sin precedentes. Cada episodio es una oda a la vida en la Tierra, con imágenes que redefinen la televisión documental.",
  descripcion: "‘Planet Earth II’ nos transporta a los ecosistemas más extremos del planeta: montañas, junglas, islas, desiertos, praderas y ciudades. A través de secuencias 4K filmadas con tecnología de vanguardia, el documental capta momentos únicos de comportamiento animal y supervivencia. Narrado con la inconfundible voz de David Attenborough, esta serie celebra la belleza salvaje del planeta y plantea la urgencia de protegerlo frente a la expansión humana.",
  recomendacion: "La cúspide del documental de naturaleza. Imprescindible para cualquier amante de la Tierra.",
  detalles: "Secuela del icónico ‘Planet Earth’ (2006). Producido por BBC Earth. Ganador de múltiples premios Emmy y BAFTA.",
  duracion: "Serie, 6 episodios"
},
{
  id: 66,
  titulo: "Inside Job",
  anio: 2010,
  genero: "Economía / Política",
  categoria: "Documentales",
  imagen: "https://m.media-amazon.com/images/M/MV5BMTQ3MjkyODA2Nl5BMl5BanBnXkFtZTcwNzQxMTU4Mw@@._V1_FMjpg_UX1000_.jpg",
  rangoEdad: "+16",
  autor: "Charles Ferguson (Director)",
  reseña: "Riguroso y demoledor. ‘Inside Job’ expone con claridad y evidencia cómo la avaricia y la corrupción causaron la crisis financiera de 2008.",
  descripcion: "Narrado por Matt Damon, este documental explica las causas y consecuencias del colapso económico global de 2008. A través de entrevistas con economistas, políticos y banqueros, revela cómo el sistema financiero fue manipulado por intereses privados y desregulaciones. Con un ritmo ágil y una investigación impecable, ‘Inside Job’ deja en evidencia la fragilidad del sistema capitalista moderno.",
  recomendacion: "Una lección imprescindible de economía, poder y ética.",
  detalles: "Ganador del Oscar a Mejor Documental en 2011. Aclamado por críticos y universidades como recurso educativo sobre finanzas globales.",
  duracion: "1h 48min"
},
{
  id: 67,
  titulo: "The Great Hack",
  anio: 2019,
  genero: "Tecnología / Privacidad",
  categoria: "Documentales",
  imagen: "https://i.pinimg.com/736x/a1/b1/16/a1b11662800226e2a0a66c14e881938a.jpg",
  rangoEdad: "+13",
  autor: "Jehane Noujaim y Karim Amer (Directores)",
  reseña: "Un thriller digital tan real como aterrador. Revela cómo los datos personales se convirtieron en el recurso más valioso —y peligroso— del siglo XXI.",
  descripcion: "‘The Great Hack’ investiga el escándalo de Cambridge Analytica, la empresa que utilizó millones de datos de usuarios de Facebook para manipular elecciones en Estados Unidos y Reino Unido. Con entrevistas a periodistas, analistas y denunciantes, el documental muestra cómo la información personal se transformó en un arma política. Es una advertencia sobre la vulnerabilidad digital en un mundo hiperconectado.",
  recomendacion: "Obligatorio para comprender el poder de los datos y su influencia en la democracia moderna.",
  detalles: "Producido por Netflix. Nominado al BAFTA y al Emmy. Dirigido por los creadores de ‘The Square’.",
  duracion: "1h 54min"
},
{
  id: 68,
  titulo: "Wild Wild Country",
  anio: 2018,
  genero: "Religión / Misterio",
  categoria: "Documentales",
  imagen: "https://resizing.flixster.com/o5mRFFcnl03Y9JYTxo-Tlqza71Q=/fit-in/705x460/v2/https://resizing.flixster.com/-XZAfHZM39UwaGJIFWKAE8fS0ak=/v3/t/assets/p15076916_b_v10_ac.jpg",
  rangoEdad: "+16",
  autor: "Chapman Way y Maclain Way (Directores)",
  reseña: "Un relato fascinante sobre poder, fe y manipulación. La historia real de una secta que desafió al gobierno estadounidense en los años 80.",
  descripcion: "La serie cuenta el ascenso y caída de la comunidad Rajneeshpuram, liderada por el gurú Bhagwan Shree Rajneesh (Osho), en Oregón. Lo que comenzó como un experimento espiritual se transformó en un conflicto político y criminal. Con testimonios de seguidores, exmiembros y habitantes del pueblo, ‘Wild Wild Country’ mezcla drama, intriga y reflexión sobre los límites de la libertad religiosa.",
  recomendacion: "Una historia tan increíble que parece ficción. Perfecta para quienes disfrutan de misterios reales y dilemas éticos.",
  detalles: "Miniserie documental de 6 episodios producida por Netflix. Ganadora del Emmy al Mejor Montaje Documental.",
  duracion: "6 episodios"
},
{
  id: 69,
  titulo: "Fire in Paradise",
  anio: 2019,
  genero: "Desastre / Testimonio",
  categoria: "Documentales",
  imagen: "https://lumiere-a.akamaihd.net/v1/images/rebuildingparadise-vertical_a2021408.jpeg",
  rangoEdad: "+13",
  autor: "Zachary Canepari y Drea Cooper (Directores)",
  reseña: "Impactante y desgarrador. Narra minuto a minuto el incendio más mortal en la historia de California.",
  descripcion: "El 8 de noviembre de 2018, un fuego devastador arrasó la ciudad de Paradise, dejando más de 80 víctimas fatales y miles de desaparecidos. Este documental combina grabaciones reales, llamadas de emergencia y testimonios de sobrevivientes para reconstruir el horror de aquel día. Más allá del desastre natural, la película plantea preguntas sobre el cambio climático y la preparación humana ante la tragedia.",
  recomendacion: "Un recordatorio estremecedor del poder de la naturaleza y la resiliencia humana.",
  detalles: "Producido por Netflix. Ganador del Emmy al Mejor Cortometraje Documental en 2020.",
  duracion: "40min"
},
{
  id: 70,
  titulo: "The Farthest: Voyager in Space",
  anio: 2017,
  genero: "Ciencia / Espacio",
  categoria: "Documentales",
  imagen: "https://upload.wikimedia.org/wikipedia/en/7/71/The_farthest_-_poster.jpg",
  rangoEdad: "Apta para todos",
  autor: "Emer Reynolds (Directora)",
  reseña: "Inspirador y profundamente humano. ‘The Farthest’ celebra una de las mayores hazañas de la humanidad: el viaje de las sondas Voyager hacia lo desconocido.",
  descripcion: "Este documental narra la increíble historia de las sondas Voyager 1 y 2, lanzadas en 1977 para explorar los confines del sistema solar. Con entrevistas a los científicos y técnicos originales de la NASA, ‘The Farthest’ combina emoción, nostalgia y asombro científico. Más que una historia de exploración espacial, es un homenaje a la curiosidad humana, a la cooperación internacional y al deseo de comprender nuestro lugar en el cosmos.",
  recomendacion: "Ideal para quienes aman la ciencia, el espacio y los documentales que inspiran a soñar más allá de las estrellas.",
  detalles: "Producción de la PBS y la NASA. Ganadora del Premio Emmy al Mejor Documental Científico. Incluye imágenes restauradas de las misiones Voyager y el icónico 'Golden Record'.",
  duracion: "2h 1min"
},
  // ===============================
  // 🎎 ASIÁTICAS (COREANAS / ANIMES)
  // ===============================
  {
    id: 71,
    titulo: "Parasite",
    anio: 2019,
    genero: "Thriller / Drama",
    categoria: "Asiáticas",
    imagen: "https://img.rtve.es/imagenes/caratula-parasito-saga-completa/1466077733963.jpg",
    rangoEdad: "+16",
    autor: "Bong Joon-ho (Director)",
    reseña: "Una obra maestra de la sátira social, con giros inesperados y una ejecución brillante.",
    descripcion: "Una familia pobre se infiltra, uno por uno, en el hogar de una familia rica con consecuencias catastróficas.",
    recomendacion: "Cine moderno esencial. Una crítica social inteligente con humor negro.",
    detalles: "Ganadora de la Palma de Oro y 4 Premios de la Academia, incluyendo Mejor Película.",
    duracion: "2h 12min",
  },
  {
    id: 72,
    titulo: "Train to Busan",
    anio: 2016,
    genero: "Terror / Acción",
    categoria: "Asiáticas",
    imagen: "https://images.justwatch.com/poster/9373937/s718/train-to-busan.jpg",
    rangoEdad: "+18",
    autor: "Yeon Sang-ho (Director)",
    reseña: "Una de las mejores películas de zombis de la década, intensa, emocionante y con un ritmo implacable.",
    descripcion: "Un padre y su hija quedan atrapados en un tren de alta velocidad mientras un apocalipsis zombi estalla en Corea.",
    recomendacion: "Acción trepidante. Ideal para fans del terror y el suspenso coreano.",
    detalles: "Un gran éxito internacional del cine surcoreano.",
    duracion: "1h 58min",
  },
  {
    id: 73,
    titulo: "My Name",
    anio: 2021,
    genero: "Acción / Drama",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BN2ZiZWU3MzMtNGM5OC00ZWVkLTkxNjUtMTYwZGU4MzgxYzk0XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Kim Jin-min (Director)",
    reseña: "Un drama de venganza oscuro con escenas de acción brutales y una gran actuación de su protagonista.",
    descripcion: "Una joven se une a un cartel de drogas para descubrir la verdad detrás del asesinato de su padre.",
    recomendacion: "Si disfrutas de *K-dramas* de acción y venganza con personajes femeninos fuertes.",
    detalles: "Serie de 8 episodios. Un éxito de Netflix.",
    duracion: "Serie, 8 episodios",
  },
  {
    id: 74,
    titulo: "The Glory",
    anio: 2023,
    genero: "Drama / Venganza",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHJdOzvTpI48s0esFNBVeVw849nLqtQavaZA&s",
    rangoEdad: "+16",
    autor: "An Gil-ho (Director)",
    reseña: "Un drama de venganza meticuloso y bien escrito que aborda el acoso escolar y la justicia.",
    descripcion: "Años después de ser víctima de *bullying*, una mujer ejecuta un elaborado plan de venganza contra sus acosadores.",
    recomendacion: "Uno de los *K-dramas* más aclamados y populares sobre justicia personal.",
    detalles: "Serie de 16 episodios dividida en dos partes. Protagonizada por Song Hye-kyo.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 75,
    titulo: "Extraordinary You",
    anio: 2019,
    genero: "Romance / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ2jC7TEk0s7u4RJKInfbfI_LlXTblbEdchNlmpTKBEsYHZtApNLSO-KSbzPwRpu0W7iw&usqp=CAU",
    rangoEdad: "+13",
    autor: "Kim Sang-hyeop (Director)",
    reseña: "Un *K-drama* único que juega con el concepto de la realidad dentro de un cómic.",
    descripcion: "Una estudiante descubre que es un personaje secundario en un *manhwa* y decide cambiar su destino.",
    recomendacion: "Fantasía juvenil con una premisa original y mucho romance *meta-ficcional*.",
    detalles: "Basada en un *webtoon*. Mezcla comedia, romance y fantasía.",
    duracion: "Serie, 32 episodios cortos",
  },
  {
    id: 76,
    titulo: "Start-Up",
    anio: 2020,
    genero: "Drama / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BYTJiYmE0ZGItMmU1NS00NThhLWIzODEtZmJlYjBmMzcwNmY3XkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Oh Choong-hwan (Director)",
    reseña: "Una serie inspiradora sobre jóvenes ambiciosos que buscan triunfar en el competitivo mundo de las *start-ups* tecnológicas.",
    descripcion: "Un grupo de jóvenes compite por el éxito en un distrito de Corea, enfrentando dilemas de negocios y amor.",
    recomendacion: "Ideal si te gustan las historias de emprendimiento con un triángulo amoroso central.",
    detalles: "Con Suzy y Nam Joo-hyuk. Se centra en la tecnología y la innovación.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 77,
    titulo: "Alchemy of Souls",
    anio: 2022,
    genero: "Fantasía / Aventura",
    categoria: "Asiáticas",
    imagen: "https://www.monash.edu/__data/assets/image/0006/3069096/Alchemy-of-Souls-official-poster.jpg",
    rangoEdad: "+16",
    autor: "Park Joon-hwa (Director)",
    reseña: "Una fantasía épica y compleja con hermosos escenarios, magia, acción y romance.",
    descripcion: "Una hechicera se encuentra atrapada en el cuerpo de una guerrera ciega y se convierte en sirvienta de un noble.",
    recomendacion: "Si amas la fantasía coreana con gran desarrollo de personajes y mitología.",
    detalles: "Dividida en dos partes, con un total de 30 episodios. Gran éxito de TVN.",
    duracion: "Serie, 30 episodios",
  },
  {
    id: 78,
    titulo: "Twenty-Five Twenty-One",
    anio: 2022,
    genero: "Drama / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BNDU3ODZjMzAtYTIyZi00MGExLWFhYjEtOGQ5YjVlMjU3MjNlXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Jung Ji-hyun (Director)",
    reseña: "Un drama *slice of life* conmovedor y nostálgico sobre el primer amor, los sueños y la madurez.",
    descripcion: "La historia de dos jóvenes cuyas vidas se entrelazan en 1998, durante la crisis financiera asiática.",
    recomendacion: "Un drama romántico y profundo, con una estética visual muy cuidada.",
    detalles: "Protagonizada por Kim Tae-ri y Nam Joo-hyuk.",
    duracion: "Serie, 16 episodios",
  },
  {
    id: 79,
    titulo: "Squid Game",
    anio: 2021,
    genero: "Acción / Suspenso",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BMDcxYjg1OTctYmUxZi00ZjhjLWIwNTMtNmI2M2Y4OTU1YWU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Hwang Dong-hyuk (Director)",
    reseña: "El fenómeno mundial de Netflix. Tensión extrema, crítica social y un concepto brutal.",
    descripcion: "Cientos de personas con problemas de dinero aceptan participar en juegos infantiles mortales por una gran suma de dinero.",
    recomendacion: "Un *thriller* de supervivencia imprescindible. Intenso y con mucha crítica al capitalismo.",
    detalles: "Se convirtió en la serie más vista de la historia de Netflix en su lanzamiento.",
    duracion: "Serie, 9 episodios",
  },
  {
    id: 80,
    titulo: "All of Us Are Dead",
    anio: 2022,
    genero: "Terror / Escolar",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZxay4or86F0zxdpPsmrbpXXutgSKklnYtrb9E15oPc0tzOcro4u7PDYG0idNv80StwCI&usqp=CAU",
    rangoEdad: "+18",
    autor: "Lee Jae-gyoo (Director)",
    reseña: "Un *K-drama* de zombis ultra violento y con mucha adrenalina, centrado en el drama adolescente.",
    descripcion: "Un grupo de estudiantes queda atrapado en su instituto durante el inicio de un apocalipsis zombi.",
    recomendacion: "Para fans del género zombi con mucha acción y tensión de supervivencia.",
    detalles: "Basada en el *webtoon* 'Now at Our School'.",
    duracion: "Serie, 12 episodios",
  },
  {
    id: 81,
    titulo: "Your Name",
    anio: 2016,
    genero: "Anime / Romance",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BMTIyNzFjNzItZmQ1MC00NzhjLThmMzYtZjRhN2Y3MmM2OGQyXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+13",
    autor: "Makoto Shinkai (Director)",
    reseña: "Una obra maestra visual que combina romance, fantasía y un giro narrativo sorprendente.",
    descripcion: "Un chico de Tokio y una chica de un pueblo rural comienzan a intercambiar cuerpos misteriosamente.",
    recomendacion: "Imprescindible para los fans del anime. Una película visualmente deslumbrante.",
    detalles: "Uno de los animes más taquilleros de la historia.",
    duracion: "1h 47min",
  },
  {
    id: 82,
    titulo: "A Silent Voice (Koe no Katachi)",
    anio: 2016,
    genero: "Anime / Drama",
    categoria: "Asiáticas",
    imagen: "https://upload.wikimedia.org/wikipedia/en/3/32/A_Silent_Voice_Film_Poster.jpg",
    rangoEdad: "+13",
    autor: "Naoko Yamada (Directora)",
    reseña: "Una historia conmovedora sobre el perdón, la redención y la empatía. Un retrato sensible del acoso escolar y la búsqueda de segundas oportunidades.",
    descripcion: "Shoya Ishida, un joven que en su infancia acosó a una compañera sorda llamada Shoko Nishimiya, vive atormentado por la culpa de sus acciones. Años después, decide buscarla para disculparse y reparar el daño que causó. Lo que sigue es un viaje emocional sobre la amistad, el arrepentimiento y la posibilidad de sanar. Con una animación delicada y una banda sonora emotiva, *A Silent Voice* explora la soledad y la comunicación humana desde una perspectiva profundamente humana.",
    recomendacion: "Recomendada para quienes buscan un anime con un mensaje poderoso y emocional. Ideal para reflexionar sobre la empatía y el valor del perdón.",
    detalles: "Basada en el manga de Yoshitoki Ōima. Producida por Kyoto Animation. Nominada a Mejor Película de Animación en los Japan Academy Prize.",
    duracion: "2h 10min"
  },
  {
    id: 83,
    titulo: "Spirited Away",
    anio: 2001,
    genero: "Anime / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BM2E2YzcwMTQtNWRlMC00ZGZlLWJhZTEtMDU4ZGIzMWI0NzJmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+7",
    autor: "Hayao Miyazaki (Director)",
    reseña: "Una joya de Studio Ghibli. Pura fantasía onírica con una animación magistral y una rica mitología.",
    descripcion: "Una niña se adentra en un mundo espiritual para rescatar a sus padres convertidos en cerdos.",
    recomendacion: "Un clásico del anime y una de las películas de fantasía más importantes de la historia.",
    detalles: "Ganadora del Oscar a Mejor Película de Animación (única película de anime en lograrlo).",
    duracion: "2h 5min",
  },
  {
    id: 84,
    titulo: "Demon Slayer: Mugen Train",
    anio: 2020,
    genero: "Anime / Acción",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BNzEzYjhkYTctMWNmZS00MTc5LWI4OWUtZjFkNzNkYTNkMTJlXkEyXkFqcGc@._V1_.jpg",
    rangoEdad: "+16",
    autor: "Haruo Sotozaki (Director)",
    reseña: "Una continuación directa del anime, con batallas impresionantes y un gran impacto emocional.",
    descripcion: "Tanjiro y sus compañeros se unen a un poderoso cazador de demonios para investigar misterios en un tren.",
    recomendacion: "Acción visualmente espectacular. Si te gusta el anime, es imperdible.",
    detalles: "Rompió récords de taquilla en Japón y a nivel mundial para una película de anime.",
    duracion: "1h 57min",
  },
  {
    id: 85,
    titulo: "Attack on Titan",
    anio: 2013,
    genero: "Anime / Épico",
    categoria: "Asiáticas",
    imagen: "https://m.media-amazon.com/images/M/MV5BZjliODY5MzQtMmViZC00MTZmLWFhMWMtMjMwM2I3OGY1MTRiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    rangoEdad: "+18",
    autor: "Tetsurō Araki (Director)",
    reseña: "Una serie anime brutalmente intensa, con un mundo post-apocalíptico fascinante y mucha acción.",
    descripcion: "La humanidad lucha por sobrevivir dentro de murallas contra gigantes devoradores de personas.",
    recomendacion: "Si buscas una serie con acción, misterio y un gran desarrollo de personajes.",
    detalles: "Basada en el manga de Hajime Isayama. Famosa por sus giros argumentales.",
    duracion: "Serie, 4 temporadas",
  },
  {
  id: 86,
  titulo: "El niño y la garza (The Boy and the Heron)",
  anio: 2023,
  genero: "Anime / Fantasía / Drama",
  categoria: "Asiáticas",
  imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwMhofHqKGhDKdfyTmV1HSx380uLbpTiGMlQ&s",
  rangoEdad: "Apta para todo público",
  autor: "Hayao Miyazaki (Director)",
  reseña: "Una obra maestra visual y poética del Studio Ghibli. Un viaje introspectivo sobre la pérdida, la esperanza y el renacer, envuelto en una atmósfera de ensueño.",
  descripcion: "Tras la muerte de su madre, Mahito, un niño solitario, se muda al campo con su padre y su nueva madrastra. Allí conoce a una garza parlante que lo guía hacia un mundo misterioso, lleno de criaturas fantásticas, donde los límites entre la vida y la muerte se desdibujan. A través de esta aventura simbólica, Mahito enfrenta su dolor y busca entender el ciclo de la existencia. ‘El niño y la garza’ es una carta de despedida y esperanza de Miyazaki, repleta de belleza visual y profundidad emocional.",
  recomendacion: "Perfecta para los fans de Studio Ghibli o del anime contemplativo y filosófico. Una película para ver más de una vez y descubrir nuevos significados.",
  detalles: "Ganadora del Oscar 2024 a Mejor Película de Animación. Producida por Studio Ghibli y musicalizada por Joe Hisaishi. Considerada el regreso triunfal de Hayao Miyazaki tras una década de ausencia.",
  duracion: "2h 4min"
},
  {
  id: 87,
  titulo: "Suzume",
  anio: 2023,
  genero: "Anime / Fantasía / Aventura / Drama",
  categoria: "Asiáticas",
  imagen: "https://es.web.img3.acsta.net/pictures/23/03/31/12/29/1925541.jpg",
  rangoEdad: "+13",
  autor: "Makoto Shinkai (Director)",
  reseña: "Una aventura mágica y emotiva sobre una joven que debe cerrar puertas misteriosas que desatan desastres naturales. Bellísima animación, paisajes impresionantes y una historia sobre el duelo y la esperanza.",
  descripcion: "Suzume, una adolescente japonesa, conoce a un joven que busca extrañas puertas en ruinas. Al abrir una de ellas, desata una fuerza sobrenatural que amenaza con destruir el país. Juntos emprenden un viaje por todo Japón para sellar esas puertas y restaurar el equilibrio entre el mundo de los vivos y el de los espíritus. En el camino, Suzume también enfrentará su propio pasado y aprenderá a sanar sus heridas. Con una mezcla de fantasía, aventura y emoción, ‘Suzume’ es una obra visualmente impactante y profundamente humana.",
  recomendacion: "Si te gustaron *Your Name* o *Weathering With You*, esta película te encantará. Es un viaje espiritual y visual con un mensaje de esperanza.",
  detalles: "Dirigida por Makoto Shinkai, creador de *Your Name*. Nominada al Oscar 2024 a Mejor Película de Animación. La banda sonora corre a cargo de Radwimps y Kazuma Jinnouchi.",
  duracion: "2h 1min"
},
  {
    id: 88,
    titulo: "Jujutsu Kaisen 0",
    anio: 2021,
    genero: "Anime / Sobrenatural",
    categoria: "Asiáticas",
    imagen: "https://es.web.img3.acsta.net/pictures/22/05/18/16/23/5993750.jpg",
    rangoEdad: "+16",
    autor: "Sunghoo Park (Director)",
    reseña: "Una precuela intensa y oscura que expande el universo de Jujutsu Kaisen con acción increíble.",
    descripcion: "Un joven atormentado por el espíritu de su amiga de la infancia se une a la Escuela de Hechicería Jujutsu.",
    recomendacion: "Acción oscura y sobrenatural. Excelente animación y desarrollo de personajes.",
    detalles: "Basada en el manga precuela del éxito de Gege Akutami.",
    duracion: "1h 45min",
  },
  {
    id: 89,
    titulo: "Belle",
    anio: 2021,
    genero: "Anime / Musical",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdl4BP4Nyl9D9QUlzcg6sKotOpwy93-KXApg&s",
    rangoEdad: "+13",
    autor: "Mamoru Hosoda (Director)",
    reseña: "Una reinterpretación de 'La Bella y la Bestia' en la era digital, con un diseño de personaje espectacular.",
    descripcion: "Una adolescente tímida se convierte en una superestrella musical en un mundo virtual masivo.",
    recomendacion: "Visualmente impresionante y con una banda sonora moderna y emotiva.",
    detalles: "Dirigida por el aclamado Mamoru Hosoda ('Mirai', 'Summer Wars').",
    duracion: "2h 1min",
  },
  {
    id: 91,
    titulo: "Demon Slayer – The Movie: Infinity Castle",
    anio: 2025,
    genero: "Anime / Acción / Fantasía",
    categoria: "Asiáticas",
    imagen: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuXqw5AJVusysElA39ukMOixTihN1nO-h6Uod9NMMTxj6LZvSOIlN-PMN_KV1Vgy-UM7A&usqp=CAU",
    rangoEdad: "+16",
    autor: "Koyoharu Gotōge (Manga)",
    reseña: "La esperada conclusión de la saga de Demon Slayer en formato cinematográfico. Será un evento épico.",
    descripcion: "Los Cazadores de Demonios se enfrentan a Muzan Kibutsuji y sus Lunas Superiores en el Castillo Infinito.",
    recomendacion: "La batalla final de la serie. Máxima expectación para los fans.",
    detalles: "Adaptación del arco final del manga. Dividida en varias partes.",
    duracion: "Tiempo estimado: 2h 20min (Parte 1)",
  },
];

export default peliculas;